// report.js
const app = getApp();
const { formatDateTime } = require('../../utils/formatter');

// 翻译文本
const translations = {
  zh: {
    // 标题区
    reportTitle: '卫星通信链路预算分析报告',
    frequencyBandSuffix: '频段',
    // 链路评估
    linkStatus: '链路状态',
    linkMargin: '链路余量',
    systemAvailability: '系统可用度',
    // 状态文本
    statusExcellent: '优秀',
    statusGood: '良好',
    statusQualified: '合格',
    statusPoor: '不足',
    // 系统配置
    sectionSystemConfig: 'Ⅰ. 系统配置',
    infoRate: '信息速率',
    modulation: '调制方式',
    fecCode: 'FEC编码',
    symbolRate: '符号速率',
    allocBandwidth: '占用带宽',
    uplinkFreq: '上行频率',
    downlinkFreq: '下行频率',
    threshold: '门限',
    // 卫星参数
    sectionSatellite: 'Ⅱ. 卫星参数',
    sfdRef: '卫星SFD',
    transponderBW: '转发器带宽',
    inputBackoff: '输入回退',
    outputBackoff: '输出回退',
    satelliteEIRP: 'EIRPs',
    satelliteSFD: '到达卫星通量',
    satellitePSD: 'PSDs',
    groundPFD: '到地面PFD',
    // 链路质量
    sectionLinkQuality: 'Ⅲ. 链路质量',
    totalCN: '综合C/N',
    thresholdCN: '门限C/N',
    availability: '可用度',
    ber: '误码率',
    bwUsage: '带宽占用',
    pwrUsage: '功率占用',
    // 上下行链路
    sectionUplink: 'Ⅳ. 上行链路',
    sectionDownlink: 'Ⅴ. 下行链路',
    antennaDiameter: '天线口径',
    antennaGain: '天线增益',
    txPower: '发射功率',
    gtValue: 'G/T值',
    stationEIRP: '地站EIRP',
    eirpOutput: 'EIRP输出',
    polarization: '极化方式',
    elevation: '仰角',
    polarAngle: '极化角',
    fsl: '自由空间损耗',
    rainAtten: '降雨衰减',
    feederLoss: '馈线损耗',
    uplinkCN: '上行C/N',
    downlinkCN: '下行C/N',
    // 功放配置
    sectionPA: 'Ⅵ. 功放配置建议',
    recommendedPower: '推荐功率',
    carrierBW: '载波带宽',
    powerBW: '功率带宽',
    // 页脚
    footerText: '本报告由卫星链路预算计算系统自动生成',
    // 按钮
    btnShare: '分享报告',
    btnCopy: '复制文本',
    btnLang: 'EN',
    // 提示
    tipTitle: '提示',
    tipNoResults: '请先进行链路计算',
    tipElevation: '仰角提示',
    tipOk: '知道了',
    tipShareTitle: '分享报告',
    tipShareContent: '请点击右上角菜单选择"转发"或"分享到朋友圈"',
    tipCopySuccess: '报告已复制',
    tipCopyFail: '复制失败',
    tipCopyManual: '请手动选择文本进行复制'
  },
  en: {
    // 标题区
    reportTitle: 'Satellite Link Budget Analysis Report',
    frequencyBandSuffix: 'Band',
    // 链路评估
    linkStatus: 'Link Status',
    linkMargin: 'Link Margin',
    systemAvailability: 'Availability',
    // 状态文本
    statusExcellent: 'Excellent',
    statusGood: 'Good',
    statusQualified: 'Qualified',
    statusPoor: 'Poor',
    // 系统配置
    sectionSystemConfig: 'Ⅰ. System Config',
    infoRate: 'Info Rate',
    modulation: 'Modulation',
    fecCode: 'FEC Code',
    symbolRate: 'Symbol Rate',
    allocBandwidth: 'Bandwidth',
    uplinkFreq: 'Uplink Freq',
    downlinkFreq: 'Downlink Freq',
    threshold: 'Threshold',
    // 卫星参数
    sectionSatellite: 'Ⅱ. Satellite Params',
    sfdRef: 'Effective SFD',
    transponderBW: 'Transponder BW',
    inputBackoff: 'Input Backoff',
    outputBackoff: 'Output Backoff',
    satelliteEIRP: 'EIRPs',
    satelliteSFD: 'Flux at Sat',
    satellitePSD: 'PSDs',
    groundPFD: 'PFD on Ground',
    // 链路质量
    sectionLinkQuality: 'Ⅲ. Link Quality',
    totalCN: 'Total C/N',
    thresholdCN: 'Threshold C/N',
    availability: 'Availability',
    ber: 'BER',
    bwUsage: 'BW Usage',
    pwrUsage: 'Power Usage',
    // 上下行链路
    sectionUplink: 'Ⅳ. Uplink',
    sectionDownlink: 'Ⅴ. Downlink',
    antennaDiameter: 'Antenna Dia.',
    antennaGain: 'Antenna Gain',
    txPower: 'TX Power',
    gtValue: 'G/T',
    stationEIRP: 'Station EIRP',
    eirpOutput: 'EIRP Output',
    polarization: 'Polarization',
    elevation: 'Elevation',
    polarAngle: 'Polar Angle',
    fsl: 'Free Space Loss',
    rainAtten: 'Rain Atten.',
    feederLoss: 'Feeder Loss',
    uplinkCN: 'Uplink C/N',
    downlinkCN: 'Downlink C/N',
    // 功放配置
    sectionPA: 'Ⅵ. PA Recommendation',
    recommendedPower: 'Rec. Power',
    carrierBW: 'Carrier BW',
    powerBW: 'Power BW',
    // 页脚
    footerText: 'Generated by Satellite Link Budget System',
    // 按钮
    btnShare: 'Share',
    btnCopy: 'Copy Text',
    btnLang: '中',
    // 提示
    tipTitle: 'Notice',
    tipNoResults: 'Please calculate link first',
    tipElevation: 'Elevation Notice',
    tipOk: 'OK',
    tipShareTitle: 'Share Report',
    tipShareContent: 'Please tap the menu button at top right to share',
    tipCopySuccess: 'Copied',
    tipCopyFail: 'Copy Failed',
    tipCopyManual: 'Please copy manually'
  }
};

Page({
  data: {
    linkNum: 1,
    satelliteParams: {},
    linkParams: {},
    results: null,
    reportTime: '',
    linkPerformance: {},
    noiseRatioLabel: 'Eb/N₀', // 默认显示Eb/N0
    lang: 'zh', // 当前语言
    t: translations.zh // 当前翻译文本
  },

  onLoad(options) {
    const linkNum = parseInt(options.linkNum) || 1;
    const satelliteParams = app.globalData.satelliteParams;
    const linkParams = app.globalData.linkParams[linkNum];
    const results = app.globalData.calculationResults[linkNum];
    
    if (!results) {
      wx.showModal({
        title: '提示',
        content: '请先进行链路计算',
        success: () => {
          wx.navigateBack();
        }
      });
      return;
    }
    
    // 检查仰角验证结果
    this.checkElevationWarnings(results);
    
    // 读取保存的语言偏好
    const savedLang = wx.getStorageSync('reportLanguage') || 'zh';
    const t = translations[savedLang];
    
    // 获取链路性能指标
    const linkPerformance = this.getLinkPerformance(results, t);
    
    // 根据noiseRatioMode确定显示的门限标签
    const noiseRatioMode = linkParams.noiseRatioMode || 'ebno';
    const noiseRatioLabel = noiseRatioMode === 'esno' ? 'Es/N₀' : 'Eb/N₀';
    
    this.setData({
      linkNum: linkNum,
      satelliteParams: satelliteParams,
      linkParams: linkParams,
      results: results,
      reportTime: formatDateTime(new Date(), 'YYYY-MM-DD HH:mm'),
      linkPerformance: linkPerformance,
      noiseRatioLabel: noiseRatioLabel,
      lang: savedLang,
      t: t
    });
  },

  // 检查仰角警告
  checkElevationWarnings(results) {
    const warnings = [];
    
    // 检查发信站仰角
    if (results.elevationValidation) {
      const txValidation = results.elevationValidation;
      if (txValidation.level === 'error') {
        warnings.push(txValidation.message);
      } else if (txValidation.level === 'warning') {
        warnings.push(txValidation.message);
      }
    }
    
    // 检查收信站仰角
    if (results.rxElevationValidation) {
      const rxValidation = results.rxElevationValidation;
      if (rxValidation.level === 'error') {
        warnings.push(rxValidation.message);
      } else if (rxValidation.level === 'warning') {
        warnings.push(rxValidation.message);
      }
    }
    
    // 如果有警告，显示提示
    if (warnings.length > 0) {
      wx.showModal({
        title: '仰角提示',
        content: warnings.join('\n'),
        showCancel: false,
        confirmText: '知道了'
      });
    }
  },

  // 链路性能指标
  getLinkPerformance(results, t) {
    const linkMargin = parseFloat(results.linkmargin);
    const status = linkMargin >= 3 ? 'excellent' : (linkMargin >= 1 ? 'good' : (linkMargin >= 0 ? 'qualified' : 'poor'));
    const statusTextMap = {
      excellent: t.statusExcellent,
      good: t.statusGood,
      qualified: t.statusQualified,
      poor: t.statusPoor
    };
    
    return {
      margin: results.linkmargin,
      availability: results.systemAvailabilityResult,
      status: status,
      statusText: statusTextMap[status]
    };
  },

  // 切换语言
  toggleLanguage() {
    const newLang = this.data.lang === 'zh' ? 'en' : 'zh';
    const t = translations[newLang];
    const linkPerformance = this.getLinkPerformance(this.data.results, t);
    
    this.setData({
      lang: newLang,
      t: t,
      linkPerformance: linkPerformance
    });
    
    // 保存语言偏好
    wx.setStorageSync('reportLanguage', newLang);
  },

  // 分享报告
  shareReport() {
    wx.showShareMenu({
      withShareTicket: true,
      menus: ['shareAppMessage', 'shareTimeline']
    });
    
    // 提示用户使用右上角菜单分享
    wx.showModal({
      title: '分享报告',
      content: '请点击右上角菜单选择"转发"或"分享到朋友圈"',
      showCancel: false,
      confirmText: '知道了'
    });
  },

  // 复制报告文本
  copyReportText() {
    const reportText = this.generateReportText();
    
    wx.setClipboardData({
      data: reportText,
      success: () => {
        wx.showToast({
          title: '报告已复制',
          icon: 'success',
          duration: 2000
        });
      },
      fail: () => {
        wx.showModal({
          title: '复制失败',
          content: '请手动选择文本进行复制',
          showCancel: false
        });
      }
    });
  },

  // 生成报告文本
  generateReportText() {
    const { satelliteParams, linkParams, results, reportTime, linkPerformance, noiseRatioLabel, t, lang } = this.data;
    
    if (lang === 'zh') {
      let text = `【卫星通信链路预算分析报告】\n`;
      text += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
      text += `卫星: ${satelliteParams.satelliteName} | 轨位: ${satelliteParams.orbitPosition}°E | 频段: ${satelliteParams.frequencyBand}\n`;
      text += `时间: ${reportTime}\n\n`;
      text += `【链路评估】状态: ${linkPerformance.statusText} | 余量: ${linkPerformance.margin} dB | 可用度: ${linkPerformance.availability}%\n\n`;
      text += `【Ⅰ. 系统配置】\n`;
      text += `信息速率: ${results.infoRateResult} kbps | 调制: ${results.modulationResult} | FEC: ${results.fecResult}\n`;
      text += `符号速率: ${results.symbolRateResult} ksps | 带宽: ${results.allocBandwidthResult} kHz\n`;
      text += `上行: ${results.uplinkFrequencyResult} GHz | 下行: ${results.downlinkFrequencyResult} GHz\n`;
      text += `${noiseRatioLabel}门限: ${results.ebnoResult} dB\n\n`;
      text += `【Ⅱ. 卫星参数】\n`;
      text += `SFD参考值: ${satelliteParams.sfdRef} dBW/m² | 转发器带宽: ${satelliteParams.transponderBandwidth} MHz\n`;
      text += `输入回退: ${satelliteParams.BOi} dB | 输出回退: ${satelliteParams.BOo} dB\n`;
      text += `卫星EIRP: ${results.EIRPsResult} dBW | 卫星SFD: ${results.SFDsResult} dBW/m²\n`;
      text += `卫星PSD: ${results.satellitePSDResult} dBW/Hz | 地面PFD: ${results.satellitePFD} dBW/m²\n\n`;
      text += `【Ⅲ. 链路质量】\n`;
      text += `综合C/N: ${results.carrierTotalCN}dB | 门限C/N: ${results.thresholdCN}dB | 余量: ${results.linkmargin}dB\n`;
      text += `Es/N₀: ${results.esnoResult}dB | 可用度: ${results.systemAvailabilityResult}% | BER: ${results.berResult}\n\n`;
      text += `【Ⅳ. 上行链路】${linkParams.earthStationLocation}\n`;
      text += `天线: ${results.earthAntennaDiameterResult}m / ${results.txAntennaGainResult}dB | 功率: ${results.selectedPowerWResult}W (${results.selectedPowerResult}dBW)\n`;
      text += `地站EIRP: ${results.stationEIRPResult} dBW | 仰角: ${results.elevationResult}° | 极化: ${results.uplinkPolarizationResult}\n`;
      text += `FSL: ${results.uplinkFSLResult}dB | 雨衰: ${results.uplinkRainAttenuation}dB | 上行C/N: ${results.uplinkCN}dB\n\n`;
      text += `【Ⅴ. 下行链路】${linkParams.rxEarthStationLocation}\n`;
      text += `天线: ${results.rxAntennaDiameterResult}m / ${results.rxAntennaGainResult}dB | G/T: ${results.gOverTeResult} dB/K\n`;
      text += `EIRP输出: ${results.RXeirpPerCarrierResult} dBW | 仰角: ${results.rxElevationResult}° | 极化: ${results.downlinkPolarizationResult}\n`;
      text += `FSL: ${results.downlinkFSLResult}dB | 雨衰: ${results.downlinkRainAttenuationResult}dB | 下行C/N: ${results.downlinkCN}dB\n\n`;
      text += `【Ⅵ. 资源占用】\n`;
      text += `带宽: ${results.bandwidthUsageRatio}% | 功率: ${results.powerUsageRatio}%\n`;
      text += `推荐功率: ${results.paRecommendation}W (${results.paRecommendationdBResult}dBW)\n`;
      text += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
      text += `卫星链路预算计算系统自动生成`;
      return text;
    } else {
      let text = `【SATELLITE LINK BUDGET ANALYSIS REPORT】\n`;
      text += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
      text += `Satellite: ${satelliteParams.satelliteName} | Position: ${satelliteParams.orbitPosition}°E | Band: ${satelliteParams.frequencyBand}\n`;
      text += `Time: ${reportTime}\n\n`;
      text += `【LINK ASSESSMENT】Status: ${linkPerformance.statusText} | Margin: ${linkPerformance.margin} dB | Availability: ${linkPerformance.availability}%\n\n`;
      text += `【Ⅰ. SYSTEM CONFIG】\n`;
      text += `Info Rate: ${results.infoRateResult} kbps | Modulation: ${results.modulationResult} | FEC: ${results.fecResult}\n`;
      text += `Symbol Rate: ${results.symbolRateResult} ksps | Bandwidth: ${results.allocBandwidthResult} kHz\n`;
      text += `Uplink: ${results.uplinkFrequencyResult} GHz | Downlink: ${results.downlinkFrequencyResult} GHz\n`;
      text += `${noiseRatioLabel} Threshold: ${results.ebnoResult} dB\n\n`;
      text += `【Ⅱ. SATELLITE PARAMS】\n`;
      text += `SFD Ref: ${satelliteParams.sfdRef} dBW/m² | Transponder BW: ${satelliteParams.transponderBandwidth} MHz\n`;
      text += `Input BO: ${satelliteParams.BOi} dB | Output BO: ${satelliteParams.BOo} dB\n`;
      text += `Sat EIRP: ${results.EIRPsResult} dBW | Sat SFD: ${results.SFDsResult} dBW/m²\n`;
      text += `Sat PSD: ${results.satellitePSDResult} dBW/Hz | Ground PFD: ${results.satellitePFD} dBW/m²\n\n`;
      text += `【Ⅲ. LINK QUALITY】\n`;
      text += `Total C/N: ${results.carrierTotalCN}dB | Threshold C/N: ${results.thresholdCN}dB | Margin: ${results.linkmargin}dB\n`;
      text += `Es/N₀: ${results.esnoResult}dB | Availability: ${results.systemAvailabilityResult}% | BER: ${results.berResult}\n\n`;
      text += `【Ⅳ. UPLINK】${linkParams.earthStationLocation}\n`;
      text += `Antenna: ${results.earthAntennaDiameterResult}m / ${results.txAntennaGainResult}dB | Power: ${results.selectedPowerWResult}W (${results.selectedPowerResult}dBW)\n`;
      text += `Station EIRP: ${results.stationEIRPResult} dBW | Elevation: ${results.elevationResult}° | Polar: ${results.uplinkPolarizationResult}\n`;
      text += `FSL: ${results.uplinkFSLResult}dB | Rain: ${results.uplinkRainAttenuation}dB | Uplink C/N: ${results.uplinkCN}dB\n\n`;
      text += `【Ⅴ. DOWNLINK】${linkParams.rxEarthStationLocation}\n`;
      text += `Antenna: ${results.rxAntennaDiameterResult}m / ${results.rxAntennaGainResult}dB | G/T: ${results.gOverTeResult} dB/K\n`;
      text += `EIRP Output: ${results.RXeirpPerCarrierResult} dBW | Elevation: ${results.rxElevationResult}° | Polar: ${results.downlinkPolarizationResult}\n`;
      text += `FSL: ${results.downlinkFSLResult}dB | Rain: ${results.downlinkRainAttenuationResult}dB | Downlink C/N: ${results.downlinkCN}dB\n\n`;
      text += `【Ⅵ. RESOURCE USAGE】\n`;
      text += `Bandwidth: ${results.bandwidthUsageRatio}% | Power: ${results.powerUsageRatio}%\n`;
      text += `Recommended Power: ${results.paRecommendation}W (${results.paRecommendationdBResult}dBW)\n`;
      text += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
      text += `Generated by Satellite Link Budget System`;
      return text;
    }
  },

  // 分享给朋友
  onShareAppMessage() {
    return {
      title: `卫星链路预算报告 - ${this.data.satelliteParams.satelliteName}`,
      path: `/pages/report/report?linkNum=${this.data.linkNum}`,
      imageUrl: ''
    };
  }
});
