// report.js
const app = getApp();
const { formatDateTime } = require('../../utils/formatter');

// 翻译文本
const translations = {
  zh: {
    // 标题区
    reportTitle: '卫星通信链路预算分析报告',
    frequencyBandSuffix: '频段',
    // 链路评估
    linkStatus: '链路状态',
    linkMargin: '链路余量',
    systemAvailability: '系统可用度',
    // 状态文本
    statusExcellent: '优秀',
    statusGood: '良好',
    statusQualified: '合格',
    statusPoor: '不足',
    // 系统配置
    sectionSystemConfig: 'Ⅰ. 系统配置',
    infoRate: '信息速率',
    modulation: '调制方式',
    fecCode: 'FEC码率',
    symbolRate: '符号速率',
    allocBandwidth: '占用带宽',
    uplinkFreq: '上行频率',
    downlinkFreq: '下行频率',
    threshold: '门限',
    // 卫星参数
    sectionSatellite: 'Ⅱ. 卫星参数',
    sfdRef: '卫星SFD',
    transponderBW: '转发器带宽',
    inputBackoff: '转发器IBO',
    outputBackoff: '转发器OBO',
    satelliteEIRP: 'EIRPs',
    satelliteSFD: '到达卫星通量',
    satellitePSD: 'PSDs',
    groundPFD: '到地面PFD',
    // 链路质量
    sectionLinkQuality: 'Ⅲ. 链路质量',
    totalCN: '综合C/N',
    thresholdCN: '门限C/N',
    availability: '可用度',
    ber: '误码率',
    bwUsage: '带宽占用',
    pwrUsage: '功率占用',
    // 上下行链路
    sectionUplink: 'Ⅳ. 上行链路',
    sectionDownlink: 'Ⅴ. 下行链路',
    antennaDiameter: '天线口径',
    antennaGain: '天线增益',
    txPower: '发射功率',
    gtValue: 'G/T值',
    stationEIRP: '地站EIRP',
    eirpOutput: 'EIRP输出',
    polarization: '极化方式',
    elevation: '仰角',
    polarAngle: '方位角',
    fsl: '自由空间损耗',
    rainAtten: '降雨衰减',
    feederLoss: '馈线损耗',
    uplinkCN: '上行C/N',
    downlinkCN: '下行C/N',
    // 功放配置
    sectionPA: 'Ⅵ. 功放配置建议',
    recommendedPower: '推荐功率',
    carrierBW: '载波带宽',
    powerBW: '功率带宽',
    // 页脚
    footerText: '本报告由卫星链路预算计算系统自动生成',
    // 按钮
    btnShare: '生成PDF',
    btnCopy: '复制文本',
    btnLang: 'EN',
    // 提示
    tipTitle: '提示',
    tipNoResults: '请先进行链路计算',
    tipElevation: '仰角提示',
    tipOk: '知道了',
    tipShareTitle: '分享报告',
    tipShareContent: '请点击右上角菜单选择"转发"或"分享到朋友圈"',
    tipCopySuccess: '报告已复制',
    tipCopyFail: '复制失败',
    tipCopyManual: '请手动选择文本进行复制'
  },
  en: {
    // 标题区
    reportTitle: 'Satellite Link Budget Analysis Report',
    frequencyBandSuffix: 'Band',
    // 链路评估
    linkStatus: 'Link Status',
    linkMargin: 'Link Margin',
    systemAvailability: 'Availability',
    // 状态文本
    statusExcellent: 'Excellent',
    statusGood: 'Good',
    statusQualified: 'Qualified',
    statusPoor: 'Poor',
    // 系统配置
    sectionSystemConfig: 'Ⅰ. System Config',
    infoRate: 'Info Rate',
    modulation: 'Modulation',
    fecCode: 'FEC Code',
    symbolRate: 'Symbol Rate',
    allocBandwidth: 'Bandwidth',
    uplinkFreq: 'Uplink Freq',
    downlinkFreq: 'Downlink Freq',
    threshold: 'Threshold',
    // 卫星参数
    sectionSatellite: 'Ⅱ. Satellite Params',
    sfdRef: 'Effective SFD',
    transponderBW: 'Transponder BW',
    inputBackoff: 'Input Backoff',
    outputBackoff: 'Output Backoff',
    satelliteEIRP: 'EIRPs',
    satelliteSFD: 'Flux at Sat',
    satellitePSD: 'PSDs',
    groundPFD: 'PFD on Ground',
    // 链路质量
    sectionLinkQuality: 'Ⅲ. Link Quality',
    totalCN: 'Total C/N',
    thresholdCN: 'Threshold C/N',
    availability: 'Availability',
    ber: 'BER',
    bwUsage: 'BW Usage',
    pwrUsage: 'Power Usage',
    // 上下行链路
    sectionUplink: 'Ⅳ. Uplink',
    sectionDownlink: 'Ⅴ. Downlink',
    antennaDiameter: 'Antenna Dia.',
    antennaGain: 'Antenna Gain',
    txPower: 'TX Power',
    gtValue: 'G/T',
    stationEIRP: 'Station EIRP',
    eirpOutput: 'EIRP Output',
    polarization: 'Polarization',
    elevation: 'Elevation',
    polarAngle: 'Azimuth',
    fsl: 'Free Space Loss',
    rainAtten: 'Rain Atten.',
    feederLoss: 'Feeder Loss',
    uplinkCN: 'Uplink C/N',
    downlinkCN: 'Downlink C/N',
    // 功放配置
    sectionPA: 'Ⅵ. PA Recommendation',
    recommendedPower: 'Rec. Power',
    carrierBW: 'Carrier BW',
    powerBW: 'Power BW',
    // 页脚
    footerText: 'Generated by Satellite Link Budget System',
    // 按钮
    btnShare: 'Export PDF',
    btnCopy: 'Copy Text',
    btnLang: '中',
    // 提示
    tipTitle: 'Notice',
    tipNoResults: 'Please calculate link first',
    tipElevation: 'Elevation Notice',
    tipOk: 'OK',
    tipShareTitle: 'Share Report',
    tipShareContent: 'Please tap the menu button at top right to share',
    tipCopySuccess: 'Copied',
    tipCopyFail: 'Copy Failed',
    tipCopyManual: 'Please copy manually'
  }
};

Page({
  data: {
    linkNum: 1,
    satelliteParams: {},
    linkParams: {},
    results: null,
    reportTime: '',
    linkPerformance: {},
    noiseRatioLabel: 'Eb/N₀', // 默认显示Eb/N0
    lang: 'zh', // 当前语言
    t: translations.zh // 当前翻译文本
  },

  onLoad(options) {
    const linkNum = parseInt(options.linkNum) || 1;
    const satelliteParams = app.globalData.satelliteParams;
    const linkParams = app.globalData.linkParams[linkNum];
    const results = app.globalData.calculationResults[linkNum];
    
    if (!results) {
      wx.showModal({
        title: '提示',
        content: '请先进行链路计算',
        success: () => {
          wx.navigateBack();
        }
      });
      return;
    }
    
    // 检查仰角验证结果
    this.checkElevationWarnings(results);
    
    // 读取保存的语言偏好
    const savedLang = wx.getStorageSync('reportLanguage') || 'zh';
    const t = translations[savedLang];
    
    // 获取链路性能指标
    const linkPerformance = this.getLinkPerformance(results, t);
    
    // 根据noiseRatioMode确定显示的门限标签
    const noiseRatioMode = linkParams.noiseRatioMode || 'ebno';
    const noiseRatioLabel = noiseRatioMode === 'esno' ? 'Es/N₀' : 'Eb/N₀';
    
    this.setData({
      linkNum: linkNum,
      satelliteParams: satelliteParams,
      linkParams: linkParams,
      results: results,
      reportTime: formatDateTime(new Date(), 'YYYY-MM-DD HH:mm'),
      linkPerformance: linkPerformance,
      noiseRatioLabel: noiseRatioLabel,
      lang: savedLang,
      t: t
    });
  },

  // 检查仰角警告
  checkElevationWarnings(results) {
    const warnings = [];
    
    // 检查发信站仰角
    if (results.elevationValidation) {
      const txValidation = results.elevationValidation;
      if (txValidation.level === 'error') {
        warnings.push(txValidation.message);
      } else if (txValidation.level === 'warning') {
        warnings.push(txValidation.message);
      }
    }
    
    // 检查收信站仰角
    if (results.rxElevationValidation) {
      const rxValidation = results.rxElevationValidation;
      if (rxValidation.level === 'error') {
        warnings.push(rxValidation.message);
      } else if (rxValidation.level === 'warning') {
        warnings.push(rxValidation.message);
      }
    }
    
    // 如果有警告，显示提示
    if (warnings.length > 0) {
      wx.showModal({
        title: '仰角提示',
        content: warnings.join('\n'),
        showCancel: false,
        confirmText: '知道了'
      });
    }
  },

  // 链路性能指标
  getLinkPerformance(results, t) {
    const linkMargin = parseFloat(results.linkmargin);
    const status = linkMargin >= 3 ? 'excellent' : (linkMargin >= 1 ? 'good' : (linkMargin >= 0 ? 'qualified' : 'poor'));
    const statusTextMap = {
      excellent: t.statusExcellent,
      good: t.statusGood,
      qualified: t.statusQualified,
      poor: t.statusPoor
    };
    
    return {
      margin: results.linkmargin,
      availability: results.systemAvailabilityResult,
      status: status,
      statusText: statusTextMap[status]
    };
  },

  // 切换语言
  toggleLanguage() {
    const newLang = this.data.lang === 'zh' ? 'en' : 'zh';
    const t = translations[newLang];
    const linkPerformance = this.getLinkPerformance(this.data.results, t);
    
    this.setData({
      lang: newLang,
      t: t,
      linkPerformance: linkPerformance
    });
    
    // 保存语言偏好
    wx.setStorageSync('reportLanguage', newLang);
  },

  // 分享报告 - 生成PDF并分享
  async shareReport() {
    const { satelliteParams, linkParams, results, lang, linkNum } = this.data;
    const t = this.data.t;
    
    // 显示加载中
    wx.showLoading({
      title: lang === 'zh' ? '正在生成PDF...' : 'Generating PDF...',
      mask: true
    });
    
    try {
      // 构建配置数据，与云函数期望的格式一致
      const configData = {
        configName: `${satelliteParams.satelliteName}_${satelliteParams.frequencyBand}`,
        satelliteParams: satelliteParams,
        linkParams: {
          [linkNum]: linkParams
        },
        calculationResults: {
          [linkNum]: results
        }
      };
      
      // 从本地存储读取上次生成的文件ID
      const lastReportPdfFileID = wx.getStorageSync('lastReportPdfFileID') || null;
      
      // 调用云函数生成PDF，如果有旧文件则删除
      const res = await wx.cloud.callFunction({
        name: 'generateReport',
        data: {
          configs: [configData],
          format: 'pdf',
          lang: lang,
          oldFileID: lastReportPdfFileID
        }
      });
      
      wx.hideLoading();
      
      if (res.result && res.result.success) {
        const { tempFileURL, fileID, fileName } = res.result;
        
        // 保存新文件ID到本地存储用于下次清理
        wx.setStorageSync('lastReportPdfFileID', fileID);
        
        // 显示操作菜单
        wx.showActionSheet({
          itemList: [
            lang === 'zh' ? '预览PDF' : 'Preview PDF',
            lang === 'zh' ? '保存到手机' : 'Save to Device',
            lang === 'zh' ? '转发给好友' : 'Share to Friend'
          ],
          success: async (actionRes) => {
            if (actionRes.tapIndex === 0) {
              // 预览PDF
              this.previewPDF(tempFileURL, fileName);
            } else if (actionRes.tapIndex === 1) {
              // 保存PDF到手机
              this.savePDFToDevice(tempFileURL, fileName);
            } else if (actionRes.tapIndex === 2) {
              // 转发给好友 - 分享PDF文件
              this.shareFileToFriend(tempFileURL, fileName);
            }
          }
        });
        
      } else {
        throw new Error(res.result?.error || (lang === 'zh' ? '生成PDF失败' : 'Failed to generate PDF'));
      }
    } catch (error) {
      wx.hideLoading();
      console.error('生成PDF失败:', error);
      wx.showModal({
        title: lang === 'zh' ? '生成失败' : 'Generation Failed',
        content: error.message || (lang === 'zh' ? '请稍后重试' : 'Please try again later'),
        showCancel: false,
        confirmText: t.tipOk
      });
    }
  },

  // 预览PDF
  async previewPDF(url, fileName) {
    const { lang } = this.data;
    wx.showLoading({
      title: lang === 'zh' ? '加载中...' : 'Loading...',
      mask: true
    });
    
    try {
      // 下载文件到临时路径
      const downloadRes = await new Promise((resolve, reject) => {
        wx.downloadFile({
          url: url,
          success: resolve,
          fail: reject
        });
      });
      
      wx.hideLoading();
      
      if (downloadRes.statusCode === 200) {
        // 打开文档预览
        wx.openDocument({
          filePath: downloadRes.tempFilePath,
          fileType: 'pdf',
          showMenu: true,
          fail: (err) => {
            console.error('打开文档失败:', err);
            wx.showToast({
              title: lang === 'zh' ? '预览失败' : 'Preview failed',
              icon: 'none'
            });
          }
        });
      } else {
        throw new Error('Download failed');
      }
    } catch (error) {
      wx.hideLoading();
      console.error('下载PDF失败:', error);
      wx.showToast({
        title: lang === 'zh' ? '下载失败' : 'Download failed',
        icon: 'none'
      });
    }
  },

  // 保存PDF到手机
  async savePDFToDevice(url, fileName) {
    const { lang } = this.data;
    wx.showLoading({
      title: lang === 'zh' ? '保存中...' : 'Saving...',
      mask: true
    });
    
    try {
      // 下载文件
      const downloadRes = await new Promise((resolve, reject) => {
        wx.downloadFile({
          url: url,
          success: resolve,
          fail: reject
        });
      });
      
      if (downloadRes.statusCode === 200) {
        // 保存到用户相册/文件系统
        const fs = wx.getFileSystemManager();
        const savedPath = `${wx.env.USER_DATA_PATH}/${fileName}`;
        
        // 复制到用户目录
        fs.saveFile({
          tempFilePath: downloadRes.tempFilePath,
          filePath: savedPath,
          success: () => {
            wx.hideLoading();
            wx.showModal({
              title: lang === 'zh' ? '保存成功' : 'Saved Successfully',
              content: lang === 'zh' ? `报告已保存为 ${fileName}，可在"文件管理-微信"中查看` : `Report saved as ${fileName}`,
              showCancel: false,
              confirmText: lang === 'zh' ? '知道了' : 'OK'
            });
          },
          fail: (err) => {
            // 如果保存失败，尝试直接分享临时文件
            wx.hideLoading();
            console.error('保存文件失败:', err);
            // 尝试打开文档让用户手动保存
            wx.openDocument({
              filePath: downloadRes.tempFilePath,
              fileType: 'pdf',
              showMenu: true,
              success: () => {
                wx.showToast({
                  title: lang === 'zh' ? '请点击右上角保存' : 'Tap menu to save',
                  icon: 'none',
                  duration: 3000
                });
              }
            });
          }
        });
      } else {
        throw new Error('Download failed');
      }
    } catch (error) {
      wx.hideLoading();
      console.error('保存PDF失败:', error);
      wx.showToast({
        title: lang === 'zh' ? '保存失败' : 'Save failed',
        icon: 'none'
      });
    }
  },

  // 分享PDF文件给好友
  async shareFileToFriend(url, fileName) {
    const { lang } = this.data;
    wx.showLoading({
      title: lang === 'zh' ? '准备中...' : 'Preparing...',
      mask: true
    });
    
    try {
      // 下载文件到临时路径
      const downloadRes = await new Promise((resolve, reject) => {
        wx.downloadFile({
          url: url,
          success: resolve,
          fail: reject
        });
      });
      
      wx.hideLoading();
      
      if (downloadRes.statusCode === 200) {
        // 使用 shareFileMessage 分享文件给好友
        wx.shareFileMessage({
          filePath: downloadRes.tempFilePath,
          fileName: fileName,
          success: () => {
            wx.showToast({
              title: lang === 'zh' ? '分享成功' : 'Shared',
              icon: 'success'
            });
          },
          fail: (err) => {
            console.error('分享文件失败:', err);
            // 如果分享失败，回退到提示用户使用右上角菜单
            if (err.errMsg && err.errMsg.includes('cancel')) {
              // 用户取消，不提示
              return;
            }
            wx.showModal({
              title: lang === 'zh' ? '分享提示' : 'Share Tip',
              content: lang === 'zh' ? '请点击右上角菜单选择"转发"分享给好友' : 'Please tap the menu button at top right to share',
              showCancel: false,
              confirmText: lang === 'zh' ? '知道了' : 'OK'
            });
          }
        });
      } else {
        throw new Error('Download failed');
      }
    } catch (error) {
      wx.hideLoading();
      console.error('下载文件失败:', error);
      wx.showToast({
        title: lang === 'zh' ? '准备失败' : 'Preparation failed',
        icon: 'none'
      });
    }
  },

  // 复制报告文本
  copyReportText() {
    const reportText = this.generateReportText();
    
    wx.setClipboardData({
      data: reportText,
      success: () => {
        wx.showToast({
          title: '报告已复制',
          icon: 'success',
          duration: 2000
        });
      },
      fail: () => {
        wx.showModal({
          title: '复制失败',
          content: '请手动选择文本进行复制',
          showCancel: false
        });
      }
    });
  },

  // 生成报告文本（专业咨询风格的自然语言描述）
  generateReportText() {
    const { satelliteParams, linkParams, results, reportTime, linkPerformance, noiseRatioLabel, t, lang } = this.data;
    
    if (lang === 'zh') {
      // 麦肯锡风格：结论先行，数据支撑，简洁有力
      let text = `基于${satelliteParams.satelliteName}卫星（${satelliteParams.orbitPosition}°E）${satelliteParams.frequencyBand}频段的链路预算分析，`;
      text += `本方案链路状态评估为"${linkPerformance.statusText}"，系统可用度达${results.systemAvailabilityResult}%，链路余量${results.linkmargin}dB，满足通信需求。`;
      text += `具体而言，该链路采用${results.modulationResult}+${results.fecResult}编码体制，信息速率${results.infoRateResult}kbps，符号速率${results.symbolRateResult}ksps，占用带宽${results.allocBandwidthResult}kHz，`;
      text += `上行${results.uplinkFrequencyResult}GHz、下行${results.downlinkFrequencyResult}GHz。`;
      text += `上行段（${linkParams.earthStationLocation}）配置${results.earthAntennaDiameterResult}m天线、${results.selectedPowerWResult}W功放，地球站EIRP ${results.stationEIRPResult}dBW，仰角${results.elevationResult}°条件下上行C/N达${results.uplinkCN}dB；`;
      text += `下行段（${linkParams.rxEarthStationLocation}）采用${results.rxAntennaDiameterResult}m天线，G/T值${results.gOverTeResult}dB/K，仰角${results.rxElevationResult}°条件下下行C/N达${results.downlinkCN}dB。`;
      text += `综合载噪比${results.carrierTotalCN}dB，较门限${results.thresholdCN}dB具备${results.linkmargin}dB余量。`;
      text += `资源占用方面，带宽利用率${results.bandwidthUsageRatio}%，功率利用率${results.powerUsageRatio}%，建议功放配置${results.paRecommendation}W以确保链路裕度。`;
      return text;
    } else {
      // McKinsey style: conclusion first, data-driven, concise and impactful
      let text = `Based on link budget analysis for ${satelliteParams.satelliteName} satellite (${satelliteParams.orbitPosition}°E) ${satelliteParams.frequencyBand} band, `;
      text += `the proposed solution achieves "${linkPerformance.statusText}" link status with ${results.systemAvailabilityResult}% system availability and ${results.linkmargin}dB link margin, meeting communication requirements. `;
      text += `Specifically, the link employs ${results.modulationResult}+${results.fecResult} coding scheme at ${results.infoRateResult}kbps information rate, ${results.symbolRateResult}ksps symbol rate, occupying ${results.allocBandwidthResult}kHz bandwidth, `;
      text += `with ${results.uplinkFrequencyResult}GHz uplink and ${results.downlinkFrequencyResult}GHz downlink. `;
      text += `The uplink segment (${linkParams.earthStationLocation}) is configured with ${results.earthAntennaDiameterResult}m antenna and ${results.selectedPowerWResult}W HPA, achieving EIRP of ${results.stationEIRPResult}dBW, yielding uplink C/N of ${results.uplinkCN}dB at ${results.elevationResult}° elevation; `;
      text += `the downlink segment (${linkParams.rxEarthStationLocation}) utilizes ${results.rxAntennaDiameterResult}m antenna with G/T of ${results.gOverTeResult}dB/K, achieving downlink C/N of ${results.downlinkCN}dB at ${results.rxElevationResult}° elevation. `;
      text += `The total C/N of ${results.carrierTotalCN}dB provides ${results.linkmargin}dB margin over the ${results.thresholdCN}dB threshold. `;
      text += `Resource utilization stands at ${results.bandwidthUsageRatio}% bandwidth and ${results.powerUsageRatio}% power, with recommended HPA capacity of ${results.paRecommendation}W to ensure adequate link margin.`;
      return text;
    }
  },

  // 分享给朋友
  onShareAppMessage() {
    return {
      title: `卫星链路预算报告 - ${this.data.satelliteParams.satelliteName}`,
      path: `/pages/report/report?linkNum=${this.data.linkNum}`,
      imageUrl: ''
    };
  }
});
