// configs.js
// 配置管理页面 - 使用云端存储配置，支持云端分享

const app = getApp();
const { formatDateTime } = require('../../utils/formatter');

// 翻译文本（用于导出报告 - 云函数版本已内置翻译，此处仅保留UI显示用）
const exportTranslations = {
  zh: {
    reportTitle: '卫星通信链路预算分析报告',
    frequencyBandSuffix: '频段',
    linkStatus: '链路状态',
    linkMargin: '链路余量',
    systemAvailability: '系统可用度',
    statusExcellent: '优秀',
    statusGood: '良好',
    statusQualified: '合格',
    statusPoor: '不足',
    sectionSystemConfig: '系统配置',
    infoRate: '信息速率',
    modulation: '调制方式',
    fecCode: 'FEC码率',
    symbolRate: '符号速率',
    allocBandwidth: '占用带宽',
    uplinkFreq: '上行频率',
    downlinkFreq: '下行频率',
    threshold: '门限',
    sectionSatellite: '卫星参数',
    sfdRef: '卫星SFD',
    transponderBW: '转发器带宽',
    inputBackoff: '输入回退',
    outputBackoff: '输出回退',
    satelliteEIRP: '卫星EIRP',
    sectionLinkQuality: '链路质量',
    totalCN: '综合C/N',
    thresholdCN: '门限C/N',
    availability: '可用度',
    ber: '误码率',
    bwUsage: '带宽占用',
    pwrUsage: '功率占用',
    sectionUplink: '上行链路',
    sectionDownlink: '下行链路',
    antennaDiameter: '天线口径',
    antennaGain: '天线增益',
    txPower: '发射功率',
    gtValue: 'G/T值',
    stationEIRP: '地站EIRP',
    polarization: '极化方式',
    elevation: '仰角',
    fsl: '自由空间损耗',
    rainAtten: '降雨衰减',
    feederLoss: '馈线损耗',
    uplinkCN: '上行C/N',
    downlinkCN: '下行C/N',
    recommendedPower: '推荐功率',
    footerText: '由卫星链路预算计算系统生成',
    excelSheetName: '链路预算报告',
    configName: '配置名称',
    satellite: '卫星',
    orbitPosition: '轨道位置',
    frequencyBand: '频段',
    txStation: '发信站',
    rxStation: '收信站'
  },
  en: {
    reportTitle: 'Satellite Link Budget Analysis Report',
    frequencyBandSuffix: 'Band',
    linkStatus: 'Link Status',
    linkMargin: 'Link Margin',
    systemAvailability: 'Availability',
    statusExcellent: 'Excellent',
    statusGood: 'Good',
    statusQualified: 'Qualified',
    statusPoor: 'Poor',
    sectionSystemConfig: 'System Config',
    infoRate: 'Info Rate',
    modulation: 'Modulation',
    fecCode: 'FEC Code',
    symbolRate: 'Symbol Rate',
    allocBandwidth: 'Bandwidth',
    uplinkFreq: 'Uplink Freq',
    downlinkFreq: 'Downlink Freq',
    threshold: 'Threshold',
    sectionSatellite: 'Satellite Params',
    sfdRef: 'Satellite SFD',
    transponderBW: 'Transponder BW',
    inputBackoff: 'Input Backoff',
    outputBackoff: 'Output Backoff',
    satelliteEIRP: 'Satellite EIRP',
    sectionLinkQuality: 'Link Quality',
    totalCN: 'Total C/N',
    thresholdCN: 'Threshold C/N',
    availability: 'Availability',
    ber: 'BER',
    bwUsage: 'BW Usage',
    pwrUsage: 'Power Usage',
    sectionUplink: 'Uplink',
    sectionDownlink: 'Downlink',
    antennaDiameter: 'Antenna Dia.',
    antennaGain: 'Antenna Gain',
    txPower: 'TX Power',
    gtValue: 'G/T',
    stationEIRP: 'Station EIRP',
    polarization: 'Polarization',
    elevation: 'Elevation',
    fsl: 'Free Space Loss',
    rainAtten: 'Rain Atten.',
    feederLoss: 'Feeder Loss',
    uplinkCN: 'Uplink C/N',
    downlinkCN: 'Downlink C/N',
    recommendedPower: 'Rec. Power',
    footerText: 'Generated by Satellite Link Budget System',
    excelSheetName: 'Link Budget Report',
    configName: 'Config Name',
    satellite: 'Satellite',
    orbitPosition: 'Orbit Position',
    frequencyBand: 'Freq Band',
    txStation: 'TX Station',
    rxStation: 'RX Station'
  }
};

Page({
  data: {
    configs: [],
    loading: false,
    currentShareConfig: null, // 当前要分享的配置
    page: 1,
    pageSize: 1000,
    hasMore: false,
    // 拖拽排序相关
    isDragging: false,
    dragOrigIndex: -1,
    dragTargetIndex: -1,
    dragGhostTop: 0,
    dragGhostLeft: 0,
    dragGhostWidth: 0,
    dragItemHeight: 0,
    dragConfig: null,
    dragScrollTop: 0,
    isCloudReady: false, // 云开发是否就绪
    // 导航栏相关数据
    statusBarHeight: 20,
    navBarTop: 0,
    navBarHeight: 32,
    navBarRight: 16,
    contentPaddingTop: 0,
    // 多选相关
    selectMode: false, // 是否处于多选模式
    selectedConfigs: [], // 选中的配置ID数组
    showExportPanel: false, // 是否显示导出面板
    showSharePanel: false, // 是否显示分享面板
    exportLang: 'zh', // 导出语言
    // 批量分享二维码相关
    showBatchQRPanel: false, // 是否显示批量分享面板
    batchQRLoading: false, // 批量分享加载中
    batchShareData: null, // 批量分享数据 { batchCode, qrCodeUrl, configCount, configNames }
    lastBatchQRFileID: null, // 上次生成的二维码文件ID（用于删除旧文件）
    // 批量导入相关
    showBatchImportPanel: false,
    batchImportData: null, // 待导入的批量配置数据
    showOverwritePicker: false, // 覆盖配置选择面板
    // 筛选相关
    showFilterPanel: false,
    filterSatellite: '', // 当前选中的卫星名称筛选
    filterBand: '', // 当前选中的频段筛选
    filterActive: false, // 筛选是否激活
    satelliteList: [], // 可选的卫星名称列表
    bandList: [], // 可选的频段列表
    allConfigs: [] // 完整配置列表（筛选前）
  },

  onLoad(options) {
    // 初始化导航栏参数
    this.initNavBarParams();
    
    // 检查云开发是否初始化
    this.checkCloudReady();
    
    // 如果是保存操作
    if (options.action === 'save') {
      this.saveCurrentConfig();
    } else if (options.shareCode) {
      // 如果是从分享链接进入，自动导入配置
      this.importFromShareCode(options.shareCode);
    } else if (options.scene) {
      // 如果是从小程序码进入，解析 scene 参数
      const scene = decodeURIComponent(options.scene);
      console.log('从小程序码进入，scene:', scene);
      
      // 判断是批次码还是单个分享码
      if (scene.startsWith('B')) {
        // 批次码，批量导入
        this.importFromBatchCode(scene);
      } else {
        // 普通分享码
        this.importFromShareCode(scene);
      }
    } else {
      this.loadConfigs();
    }
  },

  // 初始化导航栏参数
  initNavBarParams() {
    try {
      const windowInfo = wx.getWindowInfo();
      const menuButton = wx.getMenuButtonBoundingClientRect();
      
      // 计算导航栏位置
      const statusBarHeight = windowInfo.statusBarHeight || 20;
      const navBarTop = menuButton.top;
      const navBarHeight = menuButton.height;
      const navBarRight = windowInfo.windowWidth - menuButton.right + menuButton.width + 16;
      const contentPaddingTop = menuButton.bottom + 16;
      
      this.setData({
        statusBarHeight,
        navBarTop,
        navBarHeight,
        navBarRight,
        contentPaddingTop
      });
    } catch (e) {
      console.error('获取导航栏参数失败:', e);
      // 使用默认值
      this.setData({
        statusBarHeight: 20,
        navBarTop: 48,
        navBarHeight: 32,
        navBarRight: 16,
        contentPaddingTop: 96
      });
    }
  },

  onShow() {
    // 每次显示页面时刷新列表
    if (this.data.configs.length > 0) {
      this.loadConfigs();
    }
  },

  // 返回上一页
  goBack() {
    const pages = getCurrentPages();
    // 如果是通过扫码进入的（页面栈只有一页），直接跳转到主页
    if (pages.length === 1) {
      wx.reLaunch({
        url: '/pages/index/index'
      });
      return;
    }
    
    // 否则正常返回上一页
    wx.navigateBack({
      delta: 1,
      fail: () => {
        // 如果没有上一页，返回主页
        wx.reLaunch({
          url: '/pages/index/index'
        });
      }
    });
  },

  // 返回主界面
  goToCalculate() {
    const pages = getCurrentPages();
    // 如果是通过扫码进入的（页面栈只有一页），直接跳转到主页
    if (pages.length === 1) {
      wx.reLaunch({
        url: '/pages/index/index'
      });
      return;
    }
    
    // 否则正常返回上一页
    wx.navigateBack({
      delta: 1,
      fail: () => {
        wx.reLaunch({
          url: '/pages/index/index'
        });
      }
    });
  },

  // 检查云开发是否就绪
  checkCloudReady() {
    if (wx.cloud) {
      this.setData({ isCloudReady: true });
    } else {
      console.error('云开发未初始化');
      this.setData({ isCloudReady: false });
    }
  },

  // 分享给朋友
  onShareAppMessage() {
    const { currentShareConfig } = this.data;
    
    if (currentShareConfig) {
      return {
        title: `分享配置：${currentShareConfig.configName}`,
        path: `/pages/configs/configs?shareCode=${currentShareConfig.shareCode}`,
        imageUrl: ''
      };
    }
    
    return {
      title: '卫星链路预算配置',
      path: '/pages/configs/configs'
    };
  },

  // 分享到朋友圈
  onShareTimeline() {
    const { currentShareConfig } = this.data;
    
    if (currentShareConfig) {
      return {
        title: `卫星链路配置：${currentShareConfig.configName}`,
        query: `shareCode=${currentShareConfig.shareCode}`,
        imageUrl: ''
      };
    }
    
    return {
      title: '卫星链路预算',
      query: ''
    };
  },

  // 配置卡片滑动开始
  onConfigTouchStart(e) {
    const touch = e.touches[0];
    this._configTouchStartX = touch.clientX;
    this._configTouchStartY = touch.clientY;
    this._configTouchId = e.currentTarget.dataset.id;
    this._configTouchMoved = false;
    
    // 获取当前项的偏移量
    const config = this.data.configs.find(c => c._id === this._configTouchId);
    this._configStartOffsetX = config ? (config.offsetX || 0) : 0;
  },

  // 长按配置卡片 - 进入拖拽排序模式
  onConfigLongPress(e) {
    if (this.data.selectMode || this.data.isDragging) return;
    
    const index = e.currentTarget.dataset.index;
    const touch = e.touches[0];
    
    wx.vibrateShort({ type: 'heavy' });
    
    // 记录屏幕高度，用于边缘自动滚动
    const windowInfo = wx.getWindowInfo();
    this._windowHeight = windowInfo.windowHeight;
    this._autoScrollTimer = null;
    this._autoScrollSpeed = 0;
    
    // 合并滚动位置和列表项位置的查询，避免异步回调时序问题（iOS上两个exec可能乱序）
    const query = wx.createSelectorQuery();
    query.selectViewport().scrollOffset();
    query.selectAll('.config-card-wrapper').boundingClientRect();
    query.exec(results => {
      const scrollRes = results[0];
      const rects = results[1];
      
      if (!rects || rects.length === 0) return;
      
      const scrollTop = scrollRes.scrollTop || 0;
      this._savedScrollTop = scrollTop;
      this._dragInitScrollTop = scrollTop; // 初始滚动位置，拖拽期间不变
      
      const itemRect = rects[index];
      const itemHeight = itemRect.height;
      
      // 手指到卡片顶部的偏移，用于跟手计算
      this._dragTouchOffsetY = touch.clientY - itemRect.top;
      this._dragStartTouchY = touch.clientY;
      this._dragOrigIndex = index;
      this._dragItemHeight = itemHeight;
      this._isDraggingMode = true;
      
      this.setData({
        dragScrollTop: scrollTop,
        isDragging: true,
        dragOrigIndex: index,
        dragTargetIndex: index,
        dragGhostTop: itemRect.top,
        dragGhostLeft: itemRect.left,
        dragGhostWidth: itemRect.width,
        dragItemHeight: itemHeight,
        dragConfig: this.data.configs[index],
      });
    });
  },

  // 配置卡片滑动移动
  onConfigTouchMove(e) {
    // 拖拽排序模式 - 幽灵跟手 + 计算目标位置 + 边缘自动滚动
    if (this._isDraggingMode && this.data.isDragging) {
      const touch = e.touches[0];
      const currentY = touch.clientY;
      this._lastTouchY = currentY;
      
      // 边缘自动滚动检测
      const edgeZone = 80; // 边缘区域大小(px)
      const maxSpeed = 8; // 最大滚动速度(px/帧)
      
      if (currentY < edgeZone) {
        // 接近顶部 - 向上滚动
        this._autoScrollSpeed = -maxSpeed * (1 - currentY / edgeZone);
        this._startAutoScroll();
      } else if (currentY > this._windowHeight - edgeZone) {
        // 接近底部 - 向下滚动
        this._autoScrollSpeed = maxSpeed * (1 - (this._windowHeight - currentY) / edgeZone);
        this._startAutoScroll();
      } else {
        this._stopAutoScroll();
      }
      
      this._updateDragPosition(currentY);
      return;
    }

    const touch = e.touches[0];
    const deltaX = touch.clientX - this._configTouchStartX;
    const deltaY = touch.clientY - this._configTouchStartY;
    
    // 判断是横向滑动还是纵向滑动
    if (!this._configTouchMoved) {
      if (Math.abs(deltaX) > Math.abs(deltaY) && Math.abs(deltaX) > 10) {
        this._configTouchMoved = true;
        this._configIsHorizontal = true;
      } else if (Math.abs(deltaY) > 10) {
        this._configTouchMoved = true;
        this._configIsHorizontal = false;
      }
    }
    
    // 只处理横向滑动
    if (this._configIsHorizontal) {
      let newOffsetX = this._configStartOffsetX + deltaX;
      
      // 限制滑动范围
      const maxOffset = 0;
      const minOffset = -80; // 删除按钮的宽度 (160rpx ≈ 80px)
      
      newOffsetX = Math.max(minOffset, Math.min(maxOffset, newOffsetX));
      
      // 更新当前项的偏移量
      const index = this.data.configs.findIndex(c => c._id === this._configTouchId);
      if (index !== -1) {
        this.setData({
          [`configs[${index}].offsetX`]: newOffsetX
        });
      }
    }
  },

  // 配置卡片滑动结束
  onConfigTouchEnd(e) {
    // 拖拽排序模式结束
    if (this._isDraggingMode && this.data.isDragging) {
      this._isDraggingMode = false;
      this._stopAutoScroll();
      
      const origIndex = this.data.dragOrigIndex;
      const targetIndex = this.data.dragTargetIndex;
      
      // 重新排序数组：将拖拽项从原位置移动到目标位置
      const configs = [...this.data.configs];
      const [movedItem] = configs.splice(origIndex, 1);
      configs.splice(targetIndex, 0, movedItem);
      
      // 恢复滚动位置（使用拖拽结束时的滚动位置）
      const finalScrollTop = this.data.dragScrollTop || 0;
      
      this.setData({
        configs,
        isDragging: false,
        dragOrigIndex: -1,
        dragTargetIndex: -1,
        dragConfig: null,
        dragScrollTop: 0,
      });
      
      if (finalScrollTop > 0) {
        wx.pageScrollTo({ scrollTop: finalScrollTop, duration: 0 });
      }
      
      // 保存自定义排序
      this.saveConfigOrder();
      return;
    }

    const index = this.data.configs.findIndex(c => c._id === this._configTouchId);
    if (index === -1) return;
    
    const currentOffsetX = this.data.configs[index].offsetX || 0;
    const threshold = -30; // 阈值
    
    // 重置其他项并决定当前项的最终位置
    const configs = this.data.configs.map((item, i) => {
      if (i === index) {
        return {
          ...item,
          offsetX: currentOffsetX < threshold ? -80 : 0,
          animating: true
        };
      }
      return {
        ...item,
        offsetX: 0,
        animating: true
      };
    });
    
    this.setData({ configs: configs });
    
    // 动画结束后移除标记
    setTimeout(() => {
      const resetConfigs = this.data.configs.map(item => ({
        ...item,
        animating: false
      }));
      this.setData({ configs: resetConfigs });
    }, 150);
    
    // 重置状态
    this._configIsHorizontal = false;
  },

  // 重置所有配置卡片的滑动状态
  resetConfigsSlideState() {
    const configs = this.data.configs.map(item => ({
      ...item,
      offsetX: 0,
      animating: false
    }));
    this.setData({ configs: configs });
  },

  // 更新拖拽位置（幽灵 + 目标索引）
  _updateDragPosition(touchY) {
    const ghostTop = touchY - this._dragTouchOffsetY;
    
    // scrollDelta: 拖拽期间自动滚动累计的偏移量
    const scrollDelta = (this.data.dragScrollTop || 0) - (this._dragInitScrollTop || 0);
    
    // 将屏幕触摸坐标转换为文档坐标来计算目标索引
    const docY = touchY + scrollDelta;
    const docStartY = this._dragStartTouchY;
    
    const deltaSlots = Math.round((docY - docStartY) / this._dragItemHeight);
    let targetIndex = this._dragOrigIndex + deltaSlots;
    targetIndex = Math.max(0, Math.min(this.data.configs.length - 1, targetIndex));
    
    const updateData = { dragGhostTop: ghostTop };
    if (targetIndex !== this.data.dragTargetIndex) {
      updateData.dragTargetIndex = targetIndex;
    }
    this.setData(updateData);
  },

  // 开始自动滚动
  _startAutoScroll() {
    if (this._autoScrollTimer) return;
    
    // 计算最大可滚动距离
    const totalItems = this.data.configs.length;
    const listHeight = totalItems * this._dragItemHeight;
    const contentPadding = this.data.contentPaddingTop || 0;
    const maxScroll = Math.max(0, listHeight + contentPadding - this._windowHeight + 50);
    
    this._autoScrollTimer = setInterval(() => {
      if (!this._isDraggingMode || !this.data.isDragging) {
        this._stopAutoScroll();
        return;
      }
      
      let newScrollTop = this.data.dragScrollTop + this._autoScrollSpeed;
      newScrollTop = Math.max(0, Math.min(maxScroll, newScrollTop));
      
      if (newScrollTop !== this.data.dragScrollTop) {
        this.setData({ dragScrollTop: newScrollTop });
        
        // 用最近一次触摸位置更新拖拽状态
        if (this._lastTouchY !== undefined) {
          this._updateDragPosition(this._lastTouchY);
        }
      }
    }, 16);
  },

  // 停止自动滚动
  _stopAutoScroll() {
    if (this._autoScrollTimer) {
      clearInterval(this._autoScrollTimer);
      this._autoScrollTimer = null;
    }
    this._autoScrollSpeed = 0;
  },

  // 保存配置排序到本地
  saveConfigOrder() {
    const order = this.data.configs.map(c => c._id);
    try {
      wx.setStorageSync('configOrder', order);
    } catch (e) {
      console.error('保存排序失败:', e);
    }
  },

  // 对配置列表应用保存的排序
  applyConfigOrder(configs) {
    try {
      const order = wx.getStorageSync('configOrder');
      if (!order || !order.length) return configs;
      
      const orderMap = {};
      order.forEach((id, idx) => { orderMap[id] = idx; });
      
      return [...configs].sort((a, b) => {
        const oa = orderMap[a._id] !== undefined ? orderMap[a._id] : -1;
        const ob = orderMap[b._id] !== undefined ? orderMap[b._id] : -1;
        if (oa === -1 && ob === -1) return 0;
        return oa - ob;
      });
    } catch (e) {
      return configs;
    }
  },

  // 加载配置列表（优先云端，失败则本地）
  async loadConfigs() {
    if (this.data.loading) return;
    
    this.setData({ loading: true });
    
    wx.showLoading({
      title: '加载中...',
      mask: true
    });
    
    try {
      // 尝试调用云函数获取配置列表
      const res = await wx.cloud.callFunction({
        name: 'configManager',
        data: {
          action: 'list',
          data: {
            page: 1,
            pageSize: this.data.pageSize
          }
        }
      });
      
      console.log('云函数返回:', res);
      
      if (res.result && res.result.success) {
        // 云端配置
        const cloudConfigs = res.result.configs.map(item => ({
          ...item,
          createTimeFormatted: formatDateTime(item.updateTime || item.createTime, 'YYYY-MM-DD HH:mm'),
          isLocal: false
        }));
        
        // 同时加载本地配置
        const localConfigs = this.getLocalConfigs();
        
        // 合并显示：云端配置在前，本地配置在后
        const allConfigs = this.applyConfigOrder([...cloudConfigs, ...localConfigs]);
        
        this.updateFilterLists(allConfigs);
        this.setData({
          allConfigs: allConfigs,
          configs: this.getFilteredConfigs(allConfigs),
          page: 1,
          hasMore: false
        });
        
        if (allConfigs.length === 0) {
          wx.showToast({
            title: '暂无配置',
            icon: 'none'
          });
        }
      } else {
        throw new Error(res.result?.error || '加载失败');
      }
    } catch (error) {
      console.error('加载云端配置失败:', error);
      
      // 检查是否是云函数未部署的错误
      const errorMsg = error.message || '';
      const isCloudFunctionMissing = errorMsg.includes('-501000') || 
                                      errorMsg.includes('FUNCTION_NOT_FOUND') ||
                                      errorMsg.includes('FunctionName');
      
      if (isCloudFunctionMissing) {
        console.log('云函数未部署，使用本地存储模式');
      }
      
      // 云端加载失败时，从本地加载
      this.loadLocalConfigs();
    } finally {
      this.setData({ loading: false });
      wx.hideLoading();
    }
  },

  // 获取本地配置列表（不更新UI）
  getLocalConfigs() {
    try {
      const configs = wx.getStorageSync('savedConfigs') || [];
      return configs.map(item => ({
        ...item,
        createTimeFormatted: formatDateTime(item.updateTime || item.createTime, 'YYYY-MM-DD HH:mm'),
        isLocal: true
      }));
    } catch (error) {
      console.error('获取本地配置失败:', error);
      return [];
    }
  },

  // 从本地加载配置（备用方案，更新UI）
  loadLocalConfigs() {
    try {
      const formattedConfigs = this.applyConfigOrder(this.getLocalConfigs());
      
      this.updateFilterLists(formattedConfigs);
      this.setData({
        allConfigs: formattedConfigs,
        configs: this.getFilteredConfigs(formattedConfigs)
      });
      
      if (formattedConfigs.length === 0) {
        wx.showToast({
          title: '暂无配置',
          icon: 'none'
        });
      }
    } catch (error) {
      console.error('加载本地配置失败:', error);
    }
  },

  // 从配置列表中提取卫星名称和频段列表
  updateFilterLists(configs) {
    const satelliteSet = new Set();
    const bandSet = new Set();
    configs.forEach(item => {
      const name = item.satelliteParams && item.satelliteParams.satelliteName;
      const band = item.satelliteParams && item.satelliteParams.frequencyBand;
      if (name) satelliteSet.add(name);
      if (band) bandSet.add(band);
    });
    this.setData({
      satelliteList: Array.from(satelliteSet).sort(),
      bandList: Array.from(bandSet).sort()
    });
  },

  // 根据当前筛选条件过滤配置
  getFilteredConfigs(configs) {
    const { filterSatellite, filterBand } = this.data;
    if (!filterSatellite && !filterBand) return configs;
    return configs.filter(item => {
      const name = item.satelliteParams && item.satelliteParams.satelliteName;
      const band = item.satelliteParams && item.satelliteParams.frequencyBand;
      if (filterSatellite && name !== filterSatellite) return false;
      if (filterBand && band !== filterBand) return false;
      return true;
    });
  },

  // 显示/隐藏筛选面板
  toggleFilterPanel() {
    this.setData({ showFilterPanel: !this.data.showFilterPanel });
  },

  hideFilterPanel() {
    this.setData({ showFilterPanel: false });
  },

  // 选择卫星筛选
  selectFilterSatellite(e) {
    this.setData({ filterSatellite: e.currentTarget.dataset.value });
  },

  // 选择频段筛选
  selectFilterBand(e) {
    this.setData({ filterBand: e.currentTarget.dataset.value });
  },

  // 重置筛选
  resetFilter() {
    this.setData({
      filterSatellite: '',
      filterBand: '',
      filterActive: false,
      configs: this.data.allConfigs,
      showFilterPanel: false
    });
  },

  // 应用筛选
  applyFilter() {
    const { filterSatellite, filterBand, allConfigs } = this.data;
    const active = !!(filterSatellite || filterBand);
    this.setData({
      filterActive: active,
      configs: this.getFilteredConfigs(allConfigs),
      showFilterPanel: false
    });
  },

  // 保存当前配置
  async saveCurrentConfig() {
    // 先加载现有配置列表
    await this.loadConfigsForSave();
    
    // 显示保存选项
    wx.showActionSheet({
      itemList: ['另存为新配置', '覆盖现有配置'],
      success: (res) => {
        if (res.tapIndex === 0) {
          // 另存为新配置
          this.showSaveAsNewDialog();
        } else if (res.tapIndex === 1) {
          // 覆盖现有配置
          this.showOverwriteConfigPicker();
        }
      },
      fail: () => {
        wx.navigateBack();
      }
    });
  },

  // 加载配置列表用于保存时选择
  async loadConfigsForSave() {
    try {
      // 尝试从云端获取配置列表
      const res = await wx.cloud.callFunction({
        name: 'configManager',
        data: {
          action: 'list',
          data: {
            page: 1,
            pageSize: 100
          }
        }
      });
      
      if (res.result && res.result.success) {
        const cloudConfigs = res.result.configs.map(item => ({
          ...item,
          createTimeFormatted: formatDateTime(item.updateTime || item.createTime, 'YYYY-MM-DD HH:mm'),
          isLocal: false
        }));
        
        const localConfigs = this.getLocalConfigs();
        const allConfigs = [...cloudConfigs, ...localConfigs];
        
        this.setData({ configs: allConfigs });
      } else {
        // 云端失败，仅加载本地配置
        const localConfigs = this.getLocalConfigs();
        this.setData({ configs: localConfigs });
      }
    } catch (error) {
      console.error('加载配置列表失败:', error);
      const localConfigs = this.getLocalConfigs();
      this.setData({ configs: localConfigs });
    }
  },

  // 显示另存为新配置对话框
  showSaveAsNewDialog() {
    // 优先使用用户修改的配置名，如果没有则生成默认名称
    const defaultName = app.globalData.currentEditingConfigName || 
                        `卫星链路配置_${formatDateTime(new Date(), 'YYYY-MM-DD')}`;
    
    wx.showModal({
      title: '保存配置到云端',
      editable: true,
      placeholderText: '请输入配置名称',
      content: defaultName,
      success: async (res) => {
        if (res.confirm) {
          await this.doSaveConfig(res.content || `配置_${Date.now()}`);
        } else {
          wx.navigateBack();
        }
      }
    });
  },

  // 显示覆盖配置选择器
  showOverwriteConfigPicker() {
    const configs = this.data.configs;
    
    if (configs.length === 0) {
      wx.showModal({
        title: '提示',
        content: '暂无已保存的配置，请选择另存为新配置',
        showCancel: false,
        success: () => {
          this.showSaveAsNewDialog();
        }
      });
      return;
    }
    
    this.setData({ showOverwritePicker: true });
  },

  hideOverwritePicker() {
    this.setData({ showOverwritePicker: false });
    wx.navigateBack();
  },

  onOverwritePickerSelect(e) {
    const index = e.currentTarget.dataset.index;
    const selectedConfig = this.data.configs[index];
    this.setData({ showOverwritePicker: false });
    this.confirmOverwriteConfig(selectedConfig);
  },

  // 确认覆盖配置
  confirmOverwriteConfig(config) {
    wx.showModal({
      title: '确认覆盖',
      content: `确定要覆盖配置"${config.configName}"吗？此操作不可恢复。`,
      success: async (res) => {
        if (res.confirm) {
          await this.doOverwriteConfig(config);
        } else {
          wx.navigateBack();
        }
      }
    });
  },

  // 执行覆盖保存操作
  async doOverwriteConfig(config) {
    wx.showLoading({
      title: '保存中...',
      mask: true
    });
    
    try {
      if (config.isLocal) {
        // 覆盖本地配置
        await this.overwriteLocalConfig(config._id);
      } else {
        // 覆盖云端配置
        await this.overwriteCloudConfig(config._id);
      }
    } catch (error) {
      console.error('覆盖配置失败:', error);
      wx.hideLoading();
      wx.showModal({
        title: '保存失败',
        content: error.message || '无法覆盖配置',
        showCancel: false
      });
    }
  },

  // 覆盖云端配置
  async overwriteCloudConfig(configId) {
    try {
      // 获取当前编辑的配置名（用户可能已修改）
      const configName = app.globalData.currentEditingConfigName;
      console.log('覆盖云端配置，配置名:', configName, 'configId:', configId);
      
      const res = await wx.cloud.callFunction({
        name: 'configManager',
        data: {
          action: 'update',
          data: {
            configId: configId,
            configName: configName, // 传递配置名以支持改名
            satelliteParams: app.globalData.satelliteParams,
            linkParams: app.globalData.linkParams,
            calculationResults: app.globalData.calculationResults || {},
            noiseRatioMode: app.globalData.noiseRatioMode || 'ebno',
            markedParams: app.globalData.markedParams || [],
            highlightedRows: app.globalData.highlightedRows || []
          }
        }
      });
      
      console.log('云函数返回结果:', res.result);
      
      if (res.result && res.result.success) {
        wx.hideLoading();
        wx.showToast({
          title: '已覆盖保存',
          icon: 'success'
        });
        
        setTimeout(() => {
          this.loadConfigs();
        }, 1000);
      } else {
        throw new Error(res.result?.error || '覆盖失败');
      }
    } catch (error) {
      throw error;
    }
  },

  // 覆盖本地配置
  async overwriteLocalConfig(configId) {
    try {
      const configs = wx.getStorageSync('savedConfigs') || [];
      const index = configs.findIndex(item => item._id === configId);
      
      if (index === -1) {
        throw new Error('配置不存在');
      }
      
      // 获取当前编辑的配置名（用户可能已修改）
      const configName = app.globalData.currentEditingConfigName;
      console.log('覆盖本地配置，配置名:', configName, '原配置名:', configs[index].configName);
      
      // 更新配置内容，包括配置名称
      configs[index] = {
        ...configs[index],
        configName: configName || configs[index].configName, // 支持改名
        satelliteParams: app.globalData.satelliteParams,
        linkParams: app.globalData.linkParams,
        calculationResults: app.globalData.calculationResults || {},
        noiseRatioMode: app.globalData.noiseRatioMode || 'ebno',
        markedParams: app.globalData.markedParams || [],
        highlightedRows: app.globalData.highlightedRows || [],
        updateTime: new Date()
      };
      
      console.log('更新后的配置名:', configs[index].configName);
      
      wx.setStorageSync('savedConfigs', configs);
      
      wx.hideLoading();
      wx.showToast({
        title: '已覆盖保存',
        icon: 'success'
      });
      
      setTimeout(() => {
        this.loadConfigs();
      }, 1000);
    } catch (error) {
      throw error;
    }
  },

  // 执行保存操作（优先云端，失败则本地）
  async doSaveConfig(configName) {
    wx.showLoading({
      title: '保存中...',
      mask: true
    });
    
    try {
      // 尝试调用云函数保存配置
      const res = await wx.cloud.callFunction({
        name: 'configManager',
        data: {
          action: 'save',
          data: {
            configName: configName,
            satelliteParams: app.globalData.satelliteParams,
            linkParams: app.globalData.linkParams,
            calculationResults: app.globalData.calculationResults || {},
            noiseRatioMode: app.globalData.noiseRatioMode || 'ebno',
            markedParams: app.globalData.markedParams || [],
            highlightedRows: app.globalData.highlightedRows || []
          }
        }
      });
      
      console.log('保存结果:', res);
      
      if (res.result && res.result.success) {
        // 云端保存成功，不需要本地保存
        wx.showToast({
          title: '已保存到云端',
          icon: 'success'
        });
        
        // 刷新列表
        setTimeout(() => {
          this.loadConfigs();
        }, 1000);
      } else {
        throw new Error(res.result?.error || '保存失败');
      }
    } catch (error) {
      console.error('保存到云端失败:', error);
      
      // 云端保存失败时，保存到本地
      this.saveToLocal(configName);
      
      // 检查是否是云函数未部署的错误
      const errorMsg = error.message || '';
      const isCloudFunctionMissing = errorMsg.includes('-501000') || 
                                      errorMsg.includes('FUNCTION_NOT_FOUND') ||
                                      errorMsg.includes('FunctionName');
      
      if (isCloudFunctionMissing) {
        wx.showModal({
          title: '提示',
          content: '云函数尚未部署，配置已保存到本地。\n\n请在微信开发者工具中右键点击 cloudfunctions/configManager 文件夹，选择"上传并部署：云端安装依赖"',
          showCancel: false,
          confirmText: '知道了'
        });
      } else {
        wx.showToast({
          title: '已保存到本地',
          icon: 'success'
        });
      }
      
      // 刷新列表显示本地配置
      setTimeout(() => {
        this.loadConfigs();
      }, 1000);
    } finally {
      wx.hideLoading();
    }
  },

  // 保存到本地存储（备份）
  saveToLocal(configName) {
    try {
      const configs = wx.getStorageSync('savedConfigs') || [];
      
      const newConfig = {
        _id: `local_${Date.now()}`,
        configName: configName,
        satelliteParams: app.globalData.satelliteParams,
        linkParams: app.globalData.linkParams,
        calculationResults: app.globalData.calculationResults || {},
        noiseRatioMode: app.globalData.noiseRatioMode || 'ebno',
        markedParams: app.globalData.markedParams || [],
        highlightedRows: app.globalData.highlightedRows || [],
        createTime: new Date(),
        updateTime: new Date(),
        isLocal: true
      };
      
      configs.unshift(newConfig);
      wx.setStorageSync('savedConfigs', configs);
    } catch (error) {
      console.error('保存到本地失败:', error);
    }
  },

  // 编辑配置
  async editConfig(e) {
    const configId = e.currentTarget.dataset.id;
    const isLocal = e.currentTarget.dataset.local;
    const configName = e.currentTarget.dataset.name;
    
    // 直接加载配置进行编辑，不弹出确认对话框
    if (isLocal) {
      await this.doEditLocalConfig(configId, configName);
    } else {
      await this.doEditCloudConfig(configId, configName);
    }
  },

  // 从云端加载配置进行编辑
  async doEditCloudConfig(configId, configName) {
    wx.showLoading({
      title: '加载中...',
      mask: true
    });
    
    try {
      const res = await wx.cloud.callFunction({
        name: 'configManager',
        data: {
          action: 'load',
          data: { configId }
        }
      });
      
      if (res.result && res.result.success) {
        const config = res.result.config;
        
        // 更新全局数据
        app.globalData.satelliteParams = config.satelliteParams;
        app.globalData.linkParams = config.linkParams;
        app.globalData.calculationResults = config.calculationResults || {};
        app.globalData.noiseRatioMode = config.noiseRatioMode || 'ebno';
        app.globalData.markedParams = config.markedParams || [];
        app.globalData.highlightedRows = config.highlightedRows || [];
        
        // 保存当前编辑的配置ID，用于后续保存更新
        app.globalData.currentEditingConfigId = configId;
        app.globalData.currentEditingConfigIsLocal = false;
        app.globalData.currentEditingConfigName = configName;
        
        // 同时保存到本地存储
        wx.setStorageSync('noiseRatioMode', config.noiseRatioMode || 'ebno');
        
        wx.showToast({
          title: '已加载配置',
          icon: 'success'
        });
        
        setTimeout(() => {
          wx.navigateBack();
        }, 1000);
      } else {
        throw new Error(res.result?.error || '加载失败');
      }
    } catch (error) {
      console.error('从云端加载失败:', error);
      wx.showModal({
        title: '加载失败',
        content: error.message || '无法加载配置',
        showCancel: false
      });
    } finally {
      wx.hideLoading();
    }
  },

  // 从本地加载配置进行编辑
  async doEditLocalConfig(configId, configName) {
    wx.showLoading({
      title: '加载中...',
      mask: true
    });
    
    try {
      const configs = wx.getStorageSync('savedConfigs') || [];
      const config = configs.find(item => item._id === configId);
      
      if (config) {
        app.globalData.satelliteParams = config.satelliteParams;
        app.globalData.linkParams = config.linkParams;
        app.globalData.calculationResults = config.calculationResults || {};
        app.globalData.noiseRatioMode = config.noiseRatioMode || 'ebno';
        app.globalData.markedParams = config.markedParams || [];
        app.globalData.highlightedRows = config.highlightedRows || [];
        
        // 保存当前编辑的配置ID，用于后续保存更新
        app.globalData.currentEditingConfigId = configId;
        app.globalData.currentEditingConfigIsLocal = true;
        app.globalData.currentEditingConfigName = configName;
        
        wx.setStorageSync('noiseRatioMode', config.noiseRatioMode || 'ebno');
        
        wx.showToast({
          title: '已加载配置',
          icon: 'success'
        });
        
        setTimeout(() => {
          wx.navigateBack();
        }, 1000);
      } else {
        throw new Error('配置不存在');
      }
    } catch (error) {
      console.error('加载本地配置失败:', error);
      wx.showModal({
        title: '加载失败',
        content: error.message || '无法加载配置',
        showCancel: false
      });
    } finally {
      wx.hideLoading();
    }
  },

  // 加载配置（纯加载，不进入编辑模式）
  async loadConfig(e) {
    const configId = e.currentTarget.dataset.id;
    const isLocal = e.currentTarget.dataset.local;
    
    wx.showModal({
      title: '确认加载',
      content: '加载此配置将覆盖当前参数，是否继续？',
      success: async (res) => {
        if (res.confirm) {
          if (isLocal) {
            await this.doLoadLocalConfig(configId);
          } else {
            await this.doLoadCloudConfig(configId);
          }
        }
      }
    });
  },

  // 从云端加载配置（不进入编辑模式）
  async doLoadCloudConfig(configId) {
    wx.showLoading({
      title: '加载中...',
      mask: true
    });
    
    try {
      const res = await wx.cloud.callFunction({
        name: 'configManager',
        data: {
          action: 'load',
          data: { configId }
        }
      });
      
      if (res.result && res.result.success) {
        const config = res.result.config;
        
        // 更新全局数据
        app.globalData.satelliteParams = config.satelliteParams;
        app.globalData.linkParams = config.linkParams;
        app.globalData.calculationResults = config.calculationResults || {};
        app.globalData.noiseRatioMode = config.noiseRatioMode || 'ebno';
        app.globalData.markedParams = config.markedParams || [];
        app.globalData.highlightedRows = config.highlightedRows || [];
        
        // 清除编辑状态（纯加载不进入编辑模式）
        app.globalData.currentEditingConfigId = null;
        app.globalData.currentEditingConfigIsLocal = false;
        app.globalData.currentEditingConfigName = null;
        
        wx.setStorageSync('noiseRatioMode', config.noiseRatioMode || 'ebno');
        
        wx.showToast({
          title: '加载成功',
          icon: 'success'
        });
        
        setTimeout(() => {
          wx.navigateBack();
        }, 1000);
      } else {
        throw new Error(res.result?.error || '加载失败');
      }
    } catch (error) {
      console.error('从云端加载失败:', error);
      wx.showModal({
        title: '加载失败',
        content: error.message || '无法加载配置',
        showCancel: false
      });
    } finally {
      wx.hideLoading();
    }
  },

  // 从本地加载配置（不进入编辑模式）
  async doLoadLocalConfig(configId) {
    wx.showLoading({
      title: '加载中...',
      mask: true
    });
    
    try {
      const configs = wx.getStorageSync('savedConfigs') || [];
      const config = configs.find(item => item._id === configId);
      
      if (config) {
        app.globalData.satelliteParams = config.satelliteParams;
        app.globalData.linkParams = config.linkParams;
        app.globalData.calculationResults = config.calculationResults || {};
        app.globalData.noiseRatioMode = config.noiseRatioMode || 'ebno';
        app.globalData.markedParams = config.markedParams || [];
        app.globalData.highlightedRows = config.highlightedRows || [];
        
        // 清除编辑状态（纯加载不进入编辑模式）
        app.globalData.currentEditingConfigId = null;
        app.globalData.currentEditingConfigIsLocal = false;
        app.globalData.currentEditingConfigName = null;
        
        wx.setStorageSync('noiseRatioMode', config.noiseRatioMode || 'ebno');
        
        wx.showToast({
          title: '加载成功',
          icon: 'success'
        });
        
        setTimeout(() => {
          wx.navigateBack();
        }, 1000);
      } else {
        throw new Error('配置不存在');
      }
    } catch (error) {
      console.error('加载本地配置失败:', error);
      wx.showModal({
        title: '加载失败',
        content: error.message || '无法加载配置',
        showCancel: false
      });
    } finally {
      wx.hideLoading();
    }
  },

  // 删除配置
  async deleteConfig(e) {
    const configId = e.currentTarget.dataset.id;
    const isLocal = e.currentTarget.dataset.local;
    
    wx.showModal({
      title: '确认删除',
      content: '删除后无法恢复，是否继续？',
      success: async (res) => {
        if (res.confirm) {
          if (isLocal) {
            await this.doDeleteLocalConfig(configId);
          } else {
            await this.doDeleteCloudConfig(configId);
          }
        }
      }
    });
  },

  // 删除云端配置
  async doDeleteCloudConfig(configId) {
    wx.showLoading({
      title: '删除中...',
      mask: true
    });
    
    try {
      const res = await wx.cloud.callFunction({
        name: 'configManager',
        data: {
          action: 'delete',
          data: { configId }
        }
      });
      
      if (res.result && res.result.success) {
        wx.showToast({
          title: '删除成功',
          icon: 'success'
        });
        
        this.loadConfigs();
      } else {
        throw new Error(res.result?.error || '删除失败');
      }
    } catch (error) {
      console.error('删除云端配置失败:', error);
      wx.showModal({
        title: '删除失败',
        content: error.message || '无法删除配置',
        showCancel: false
      });
    } finally {
      wx.hideLoading();
    }
  },

  // 删除本地配置
  async doDeleteLocalConfig(configId) {
    wx.showLoading({
      title: '删除中...',
      mask: true
    });
    
    try {
      const configs = wx.getStorageSync('savedConfigs') || [];
      const updatedConfigs = configs.filter(item => item._id !== configId);
      wx.setStorageSync('savedConfigs', updatedConfigs);
      
      wx.showToast({
        title: '删除成功',
        icon: 'success'
      });
      
      this.loadConfigs();
    } catch (error) {
      console.error('删除本地配置失败:', error);
      wx.showModal({
        title: '删除失败',
        content: error.message || '无法删除配置',
        showCancel: false
      });
    } finally {
      wx.hideLoading();
    }
  },

  // 分享配置（生成云端分享链接）
  async shareConfig(e) {
    const configId = e.currentTarget.dataset.id;
    const isLocal = e.currentTarget.dataset.local;
    
    if (isLocal) {
      // 本地配置需要先上传到云端才能分享
      wx.showModal({
        title: '提示',
        content: '本地配置需要先上传到云端才能分享，是否上传？',
        success: async (res) => {
          if (res.confirm) {
            await this.uploadLocalConfigThenShare(configId);
          }
        }
      });
      return;
    }
    
    wx.showLoading({
      title: '生成分享链接...',
      mask: true
    });
    
    try {
      const res = await wx.cloud.callFunction({
        name: 'configManager',
        data: {
          action: 'share',
          data: { configId }
        }
      });
      
      console.log('分享结果:', res);
      
      if (res.result && res.result.success) {
        const shareCode = res.result.shareCode;
        const urlLink = res.result.urlLink;
        
        // 获取配置名称
        const config = this.data.configs.find(c => c._id === configId);
        
        // 设置当前分享配置并显示分享面板
        this.setData({
          currentShareConfig: {
            configId: configId,
            configName: config?.configName || '卫星链路配置',
            shareCode: shareCode,
            urlLink: urlLink
          },
          showSharePanel: true
        });
        
        wx.hideLoading();
      } else {
        throw new Error(res.result?.error || '生成分享链接失败');
      }
    } catch (error) {
      console.error('分享失败:', error);
      wx.hideLoading();
      wx.showModal({
        title: '分享失败',
        content: error.message || '无法生成分享链接',
        showCancel: false
      });
    }
  },

  // 分享Excel参数设置文档
  async shareExcel() {
    const { currentShareConfig, exportLang } = this.data;
    if (!currentShareConfig || !currentShareConfig.configId) {
      wx.showToast({ title: '配置信息异常', icon: 'none' });
      return;
    }

    this.hideSharePanel();
    wx.showLoading({ title: '生成Excel参数文档...', mask: true });

    try {
      const configsToExport = await this.getConfigsData([currentShareConfig.configId]);

      if (configsToExport.length === 0) {
        wx.hideLoading();
        wx.showToast({ title: '没有可导出的数据', icon: 'none' });
        return;
      }

      const lastExcelParamsFileID = wx.getStorageSync('lastExcelParamsFileID') || null;

      const res = await wx.cloud.callFunction({
        name: 'generateReport',
        data: {
          configs: configsToExport,
          format: 'excel-params',
          lang: exportLang,
          oldFileID: lastExcelParamsFileID
        }
      });

      if (!res.result || !res.result.success) {
        throw new Error(res.result?.error || '云函数返回错误');
      }

      wx.setStorageSync('lastExcelParamsFileID', res.result.fileID);

      const downloadRes = await wx.cloud.downloadFile({
        fileID: res.result.fileID
      });

      if (!downloadRes.tempFilePath) {
        throw new Error('文件下载失败');
      }

      wx.hideLoading();

      this._lastExportedFile = downloadRes.tempFilePath;
      this._lastExportedFileName = res.result.fileName;

      wx.openDocument({
        filePath: downloadRes.tempFilePath,
        showMenu: true,
        fileType: 'xlsx',
        success: () => {
          wx.showToast({
            title: '点击右上角可转发',
            icon: 'none',
            duration: 3000
          });
        },
        fail: (err) => {
          console.error('打开文档失败:', err);
          wx.showModal({
            title: '导出成功',
            content: `Excel参数文档已生成\n\n文件名: ${res.result.fileName}\n\n请点击右上角菜单转发或保存`,
            showCancel: false
          });
        }
      });
    } catch (error) {
      console.error('分享Excel参数文档失败:', error);
      wx.hideLoading();
      wx.showModal({
        title: '分享失败',
        content: error.message || '无法生成Excel参数文档，请稍后重试',
        showCancel: false
      });
    }
  },

  // 分享PDF参数设置文档
  async sharePdf() {
    const { currentShareConfig, exportLang } = this.data;
    if (!currentShareConfig || !currentShareConfig.configId) {
      wx.showToast({ title: '配置信息异常', icon: 'none' });
      return;
    }

    this.hideSharePanel();
    wx.showLoading({ title: '生成PDF参数文档...', mask: true });

    try {
      const configsToExport = await this.getConfigsData([currentShareConfig.configId]);

      if (configsToExport.length === 0) {
        wx.hideLoading();
        wx.showToast({ title: '没有可导出的数据', icon: 'none' });
        return;
      }

      const lastPdfParamsFileID = wx.getStorageSync('lastPdfParamsFileID') || null;

      const res = await wx.cloud.callFunction({
        name: 'generateReport',
        data: {
          configs: configsToExport,
          format: 'pdf-params',
          lang: exportLang,
          oldFileID: lastPdfParamsFileID
        }
      });

      if (!res.result || !res.result.success) {
        throw new Error(res.result?.error || '云函数返回错误');
      }

      wx.setStorageSync('lastPdfParamsFileID', res.result.fileID);

      const downloadRes = await wx.cloud.downloadFile({
        fileID: res.result.fileID
      });

      if (!downloadRes.tempFilePath) {
        throw new Error('文件下载失败');
      }

      wx.hideLoading();

      this._lastExportedFile = downloadRes.tempFilePath;
      this._lastExportedFileName = res.result.fileName;

      wx.openDocument({
        filePath: downloadRes.tempFilePath,
        showMenu: true,
        fileType: 'pdf',
        success: () => {
          wx.showToast({
            title: '点击右上角可转发',
            icon: 'none',
            duration: 3000
          });
        },
        fail: (err) => {
          console.error('打开文档失败:', err);
          wx.showModal({
            title: '导出成功',
            content: `PDF参数文档已生成\n\n文件名: ${res.result.fileName}\n\n请点击右上角菜单转发或保存`,
            showCancel: false
          });
        }
      });
    } catch (error) {
      console.error('分享PDF参数文档失败:', error);
      wx.hideLoading();
      wx.showModal({
        title: '分享失败',
        content: error.message || '无法生成PDF参数文档，请稍后重试',
        showCancel: false
      });
    }
  },

  // 一键复制参数设置
  async copyParamsText() {
    const { currentShareConfig } = this.data;
    if (!currentShareConfig || !currentShareConfig.configId) {
      wx.showToast({ title: '配置信息异常', icon: 'none' });
      return;
    }

    wx.showLoading({ title: '读取参数...', mask: true });

    try {
      const configsToExport = await this.getConfigsData([currentShareConfig.configId]);
      if (configsToExport.length === 0) {
        wx.hideLoading();
        wx.showToast({ title: '没有可复制的数据', icon: 'none' });
        return;
      }

      const text = this.formatConfigParamsText(configsToExport[0]);

      wx.setClipboardData({
        data: text,
        success: () => {
          wx.hideLoading();
          this.hideSharePanel();
          wx.showToast({ title: '参数已复制', icon: 'success' });
        },
        fail: () => {
          wx.hideLoading();
          wx.showToast({ title: '复制失败', icon: 'none' });
        }
      });
    } catch (error) {
      console.error('复制参数失败:', error);
      wx.hideLoading();
      wx.showToast({ title: '复制失败', icon: 'none' });
    }
  },

  // 格式化配置参数为纯文本
  // 获取配置中第一条有效链路的参数
  _getFirstLinkParams(config) {
    const links = config.linkParams || {};
    const linkNums = Object.keys(links).filter(k => typeof links[k] === 'object');
    return linkNums.length > 0 ? links[linkNums[0]] : {};
  },

  formatConfigParamsText(config) {
    const sat = config.satelliteParams || {};
    const lp = this._getFirstLinkParams(config);
    const v = (val) => (val !== undefined && val !== null && val !== '') ? String(val) : '--';
    const dvbLabel = lp.dvbStandard === 'DVB-S' ? 'DVB-S' : lp.dvbStandard === 'DVB-S2' ? 'DVB-S2' : lp.dvbStandard === 'DVB-S2X' ? 'DVB-S2X' : '自定义';
    const isForward = lp.calcMode === 'forward';
    const lastLabel = isForward ? '功放功率' : '链路余量';
    const lastValue = isForward ? (v(lp.inputPaPower) + 'W') : (v(lp.margin) + 'dB');
    const upcDisplay = lp.uplinkPowerControl === '自定义' ? '自定义(' + v(lp.upcValue) + 'dB)' : v(lp.uplinkPowerControl);
    const noiseMode = config.noiseRatioMode || 'ebno';
    const noiseLabel = noiseMode === 'esno' ? 'Es/N₀门限' : 'Eb/N₀门限';

    // 每个section用两列表格展示
    const sections = [
      { title: '卫星参数', rows: [
        ['卫星名称', v(sat.satelliteName), '轨道位置', v(sat.orbitPosition) + '°E'],
        ['工作频段', v(sat.frequencyBand), 'SFD', v(sat.sfdRef) + 'dBW/m²'],
        ['转发器带宽', v(sat.transponderBandwidth) + 'MHz', '邻星离轴角', v(sat.deltaTheta) + '°'],
        ['转发器IBO', v(sat.BOi) + 'dB', '转发器OBO', v(sat.BOo) + 'dB'],
      ]},
      { title: '干扰因子(dB)', rows: [
        ['上行C/ACI', v(sat.aciUplinkFactor), '上行C/ASI', v(sat.adjUplinkFactor)],
        ['上行C/XPI', v(sat.xpolUplinkFactor), 'HPA C/IM', v(sat.hpaIntermodFactor)],
        ['下行C/ACI', v(sat.aciDownlinkFactor), '下行C/ASI', v(sat.adjDownlinkFactor)],
        ['下行C/XPI', v(sat.xpolDownlinkFactor), 'Xpdr C/IM', v(sat.xpdrIntermodFactor)],
      ]},
      { title: '上行站', rows: [
        ['地面站位置', v(lp.earthStationLocation), '极化方式', v(lp.uplinkPolarization)],
        ['天线口径', v(lp.antennaDiameter) + 'm', '天线效率', v(lp.antennaEfficiency) + '%'],
        ['经度', v(lp.longitude) + '°E', '纬度', v(lp.latitude) + '°N'],
        ['上行频率', v(lp.centerFrequency) + 'GHz', '卫星G/T', v(lp.G_Ts) + 'dB/K'],
        ['海拔', v(lp.altitude) + 'm', '降雨率', v(lp.rainRate) + 'mm/h'],
        ['功放回退', v(lp.paBackoff) + 'dB', '馈线损耗', v(lp.feederLoss) + 'dB'],
        ['UPC', upcDisplay, '可用度', v(lp.uplinkAvailability) + '%'],
      ]},
      { title: '接收站', rows: [
        ['地面站位置', v(lp.rxEarthStationLocation), '极化方式', v(lp.downlinkPolarization)],
        ['天线口径', v(lp.rxAntennaDiameter) + 'm', '天线效率', v(lp.rxAntennaEfficiency) + '%'],
        ['经度', v(lp.rxLongitude) + '°E', '纬度', v(lp.rxLatitude) + '°N'],
        ['下行频率', v(lp.rxCenterFrequency) + 'GHz', '卫星EIRP', v(lp.rxEIRP) + 'dBW'],
        ['海拔', v(lp.rxAltitude) + 'm', '降雨率', v(lp.rxRainRate) + 'mm/h'],
        ['天线噪温', v(lp.rxAntennaNoiseTemp) + 'K', '接收机噪温', v(lp.rxReceiverNoiseTemp) + 'K'],
        ['馈线损耗', v(lp.rxFeederLoss) + 'dB', '可用度', v(lp.rxDownlinkAvailability) + '%'],
      ]},
      { title: '载波参数', rows: [
        ['标准', dvbLabel, '调制方式', v(lp.modulation)],
        ['信息速率', v(lp.infoRate) + 'kbps', 'FEC码率', v(lp.fec)],
        ['帧效率', v(lp.rsCode), '滚降系数(1+α)', v(lp.bandwidthFactor)],
        ['误码率', '1E-' + v(lp.ber), noiseLabel, v(lp.ebno) + 'dB'],
        [lastLabel, lastValue],
      ]},
    ];

    const lines = [(config.configName || '卫星链路配置')];
    for (const sec of sections) {
      lines.push('┌ ' + sec.title);
      for (const r of sec.rows) {
        if (r.length === 4) {
          lines.push('  ' + r[0] + ': ' + r[1] + '  /  ' + r[2] + ': ' + r[3]);
        } else {
          lines.push('  ' + r[0] + ': ' + r[1]);
        }
      }
    }
    return lines.join('\n');
  },

  // 隐藏分享面板
  hideSharePanel() {
    this.setData({
      showSharePanel: false
    });
  },

  // 复制分享链接
  copyShareLink() {
    const { urlLink } = this.data.currentShareConfig || {};
    if (urlLink) {
      wx.setClipboardData({
        data: urlLink,
        success: () => {
          wx.showToast({
            title: '链接已复制',
            icon: 'success'
          });
          this.hideSharePanel();
        }
      });
    }
  },

  // 复制分享码
  copyShareCode() {
    const { shareCode } = this.data.currentShareConfig || {};
    if (shareCode) {
      wx.setClipboardData({
        data: shareCode,
        success: () => {
          wx.showToast({
            title: '分享码已复制',
            icon: 'success'
          });
          this.hideSharePanel();
        }
      });
    }
  },

  // 上传本地配置到云端然后分享
  async uploadLocalConfigThenShare(configId) {
    wx.showLoading({
      title: '上传中...',
      mask: true
    });
    
    try {
      const configs = wx.getStorageSync('savedConfigs') || [];
      const config = configs.find(item => item._id === configId);
      
      if (!config) {
        throw new Error('配置不存在');
      }
      
      // 上传到云端
      const saveRes = await wx.cloud.callFunction({
        name: 'configManager',
        data: {
          action: 'save',
          data: {
            configName: config.configName,
            satelliteParams: config.satelliteParams,
            linkParams: config.linkParams,
            calculationResults: config.calculationResults || {},
            noiseRatioMode: config.noiseRatioMode || 'ebno',
            markedParams: config.markedParams || [],
            highlightedRows: config.highlightedRows || []
          }
        }
      });
      
      if (saveRes.result && saveRes.result.success) {
        const cloudConfigId = saveRes.result.configId;
        
        // 生成分享码
        const shareRes = await wx.cloud.callFunction({
          name: 'configManager',
          data: {
            action: 'share',
            data: { configId: cloudConfigId }
          }
        });
        
        if (shareRes.result && shareRes.result.success) {
          wx.hideLoading();
          
          const shareCode = shareRes.result.shareCode;
          
          wx.setClipboardData({
            data: shareCode,
            success: () => {
              wx.showModal({
                title: '分享码已生成',
                content: `分享码：${shareCode}\n\n已复制到剪贴板，可直接发送给好友`,
                showCancel: false
              });
            }
          });
          
          // 刷新列表
          this.loadConfigs();
        } else {
          throw new Error(shareRes.result?.error || '生成分享码失败');
        }
      } else {
        throw new Error(saveRes.result?.error || '上传失败');
      }
    } catch (error) {
      console.error('上传并分享失败:', error);
      wx.hideLoading();
      wx.showModal({
        title: '操作失败',
        content: error.message || '无法完成操作',
        showCancel: false
      });
    }
  },

  // 导入配置
  importConfig() {
    wx.showActionSheet({
      itemList: ['输入分享码', '扫描二维码'],
      success: (res) => {
        if (res.tapIndex === 0) {
          this.inputShareCode();
        } else if (res.tapIndex === 1) {
          this.scanQRCode();
        }
      }
    });
  },

  // 输入分享码导入
  inputShareCode() {
    wx.showModal({
      title: '导入配置',
      editable: true,
      placeholderText: '请输入分享码或批次码',
      content: '',
      success: async (res) => {
        if (res.confirm && res.content) {
          let code = res.content.trim();
          
          // 判断是批次码还是单个分享码
          if (code.startsWith('B')) {
            await this.importFromBatchCode(code);
          } else {
            await this.importFromShareCode(code);
          }
        }
      }
    });
  },

  // 扫描二维码导入
  scanQRCode() {
    wx.scanCode({
      onlyFromCamera: false,
      success: async (res) => {
        console.log('扫码结果:', res);
        console.log('扫码类型:', res.scanType);
        console.log('扫码结果值:', res.result);
        console.log('扫码路径:', res.path);
        
        // 小程序码在小程序内扫描时，result 为空，需要从 path 中提取
        if (res.scanType === 'WX_CODE') {
          // 小程序码：尝试从 path 中提取 scene 参数
          if (res.path) {
            const sceneMatch = res.path.match(/scene=([^&]+)/);
            if (sceneMatch) {
              const code = decodeURIComponent(sceneMatch[1]);
              console.log('从 path 提取的 scene:', code);
              
              if (code.startsWith('B')) {
                await this.importFromBatchCode(code);
                return;
              } else {
                await this.importFromShareCode(code);
                return;
              }
            }
          }
          
          // 如果无法从 path 提取，提示用户使用微信扫一扫
          wx.showModal({
            title: '提示',
            content: '请使用微信"扫一扫"功能扫描此小程序码，或直接输入分享码导入',
            confirmText: '输入分享码',
            cancelText: '取消',
            success: (modalRes) => {
              if (modalRes.confirm) {
                this.inputShareCode();
              }
            }
          });
          return;
        }
        
        // 普通二维码
        if (res.result) {
          let code = res.result;
          
          // 如果是完整URL，提取分享码
          if (code.includes('shareCode=')) {
            const match = code.match(/shareCode=([^&]+)/);
            if (match) {
              code = match[1];
            }
          }
          
          // 判断是批次码还是单个分享码
          if (code.startsWith('B')) {
            await this.importFromBatchCode(code);
          } else {
            await this.importFromShareCode(code);
          }
        } else {
          wx.showToast({
            title: '无法识别二维码',
            icon: 'none'
          });
        }
      },
      fail: (error) => {
        console.error('扫码失败:', error);
        wx.showToast({
          title: '扫码失败',
          icon: 'none'
        });
      }
    });
  },

  // 从分享码导入配置
  async importFromShareCode(shareCode) {
    wx.showLoading({
      title: '导入中...',
      mask: true
    });
    
    try {
      // 先尝试从云端获取
      const res = await wx.cloud.callFunction({
        name: 'configManager',
        data: {
          action: 'getShared',
          data: { shareCode }
        }
      });
      
      console.log('获取分享配置结果:', res);
      
      if (res.result && res.result.success) {
        const config = res.result.config;
        const importedConfigName = `[导入] ${config.configName}`;
        
        // 优先尝试保存到云端
        try {
          const saveRes = await wx.cloud.callFunction({
            name: 'configManager',
            data: {
              action: 'save',
              data: {
                configName: importedConfigName,
                satelliteParams: config.satelliteParams,
                linkParams: config.linkParams,
                calculationResults: config.calculationResults || {},
                noiseRatioMode: config.noiseRatioMode || 'ebno',
                markedParams: config.markedParams || [],
                highlightedRows: config.highlightedRows || []
              }
            }
          });
          
          if (saveRes.result && saveRes.result.success) {
            console.log('分享码导入配置已保存到云端:', saveRes.result.configId);
            wx.showToast({
              title: '导入并已上云',
              icon: 'success'
            });
          } else {
            throw new Error('云端保存失败');
          }
        } catch (cloudError) {
          console.error('导入配置保存到云端失败，保存到本地:', cloudError);
          
          // 云端保存失败，保存到本地
          const configs = wx.getStorageSync('savedConfigs') || [];
          
          const newConfig = {
            _id: `imported_${Date.now()}`,
            configName: importedConfigName,
            satelliteParams: config.satelliteParams,
            linkParams: config.linkParams,
            calculationResults: config.calculationResults || {},
            noiseRatioMode: config.noiseRatioMode || 'ebno',
            markedParams: config.markedParams || [],
            highlightedRows: config.highlightedRows || [],
            createTime: new Date(),
            updateTime: new Date(),
            isLocal: true,
            importedFrom: shareCode
          };
          
          configs.unshift(newConfig);
          wx.setStorageSync('savedConfigs', configs);
          
          wx.showToast({
            title: '已保存到本地',
            icon: 'success'
          });
        }
        
        // 刷新列表
        setTimeout(() => {
          this.loadConfigs();
        }, 1000);
      } else {
        // 如果云端获取失败，尝试解析Base64格式（兼容旧版）
        await this.importFromBase64(shareCode);
      }
    } catch (error) {
      console.error('从云端导入失败:', error);
      
      // 尝试旧版Base64格式
      try {
        await this.importFromBase64(shareCode);
      } catch (e) {
        wx.showModal({
          title: '导入失败',
          content: '分享码无效或已过期',
          showCancel: false,
          success: () => {
            // 刷新配置列表
            this.loadConfigs();
          }
        });
      }
    } finally {
      wx.hideLoading();
    }
  },

  // 从Base64格式导入（兼容旧版）
  async importFromBase64(shareCode) {
    try {
      const decodedStr = this.arrayBufferToString(wx.base64ToArrayBuffer(shareCode));
      const configData = JSON.parse(decodedStr);
      
      if (!configData.satelliteParams || !configData.linkParams) {
        throw new Error('配置数据不完整');
      }
      
      const importedConfigName = `[导入] ${configData.configName || '未命名配置'}`;
      
      // 优先尝试保存到云端
      try {
        const saveRes = await wx.cloud.callFunction({
          name: 'configManager',
          data: {
            action: 'save',
            data: {
              configName: importedConfigName,
              satelliteParams: configData.satelliteParams,
              linkParams: configData.linkParams,
              calculationResults: configData.calculationResults || {},
              noiseRatioMode: configData.noiseRatioMode || 'ebno',
              markedParams: configData.markedParams || [],
              highlightedRows: configData.highlightedRows || []
            }
          }
        });
        
        if (saveRes.result && saveRes.result.success) {
          console.log('Base64导入配置已保存到云端:', saveRes.result.configId);
          wx.showToast({
            title: '导入并已上云',
            icon: 'success'
          });
        } else {
          throw new Error('云端保存失败');
        }
      } catch (cloudError) {
        console.error('Base64导入配置保存到云端失败，保存到本地:', cloudError);
        
        // 云端保存失败，保存到本地
        const configs = wx.getStorageSync('savedConfigs') || [];
        
        const newConfig = {
          _id: `imported_${Date.now()}`,
          configName: importedConfigName,
          satelliteParams: configData.satelliteParams,
          linkParams: configData.linkParams,
          calculationResults: configData.calculationResults || {},
          noiseRatioMode: configData.noiseRatioMode || 'ebno',
          markedParams: configData.markedParams || [],
          highlightedRows: configData.highlightedRows || [],
          createTime: new Date(),
          updateTime: new Date(),
          isLocal: true
        };
        
        configs.unshift(newConfig);
        wx.setStorageSync('savedConfigs', configs);
        
        wx.showToast({
          title: '已保存到本地',
          icon: 'success'
        });
      }
      
      // 刷新列表
      setTimeout(() => {
        this.loadConfigs();
      }, 1000);
    } catch (error) {
      console.error('Base64解析失败:', error);
      throw error;
    }
  },

  // 生成报告
  async generateReport(e) {
    const configId = e.currentTarget.dataset.id;
    const isLocal = e.currentTarget.dataset.local;
    
    wx.showLoading({
      title: '准备生成报告...',
      mask: true
    });
    
    try {
      let config;
      
      if (isLocal) {
        const configs = wx.getStorageSync('savedConfigs') || [];
        config = configs.find(item => item._id === configId);
      } else {
        const res = await wx.cloud.callFunction({
          name: 'configManager',
          data: {
            action: 'load',
            data: { configId }
          }
        });
        
        if (res.result && res.result.success) {
          config = res.result.config;
        }
      }
      
      if (!config) {
        throw new Error('配置不存在');
      }
      
      if (!config.calculationResults || Object.keys(config.calculationResults).length === 0) {
        wx.hideLoading();
        wx.showModal({
          title: '无法生成报告',
          content: '该配置没有计算结果，请先加载配置并进行计算后再保存',
          showCancel: false
        });
        return;
      }
      
      app.globalData.satelliteParams = config.satelliteParams;
      app.globalData.linkParams = config.linkParams;
      app.globalData.calculationResults = config.calculationResults;
      app.globalData.noiseRatioMode = config.noiseRatioMode || 'ebno';
      app.globalData.markedParams = config.markedParams || [];
      
      wx.hideLoading();
      
      const linkNumbers = Object.keys(config.calculationResults).map(k => parseInt(k));
      const firstLinkNum = linkNumbers.length > 0 ? linkNumbers[0] : 1;
      
      wx.navigateTo({
        url: `/pages/report/report?linkNum=${firstLinkNum}&fromConfig=true`
      });
    } catch (error) {
      console.error('生成报告失败:', error);
      wx.hideLoading();
      wx.showModal({
        title: '生成报告失败',
        content: error.message || '无法生成报告',
        showCancel: false
      });
    }
  },

  // 同步本地配置到云端
  async syncLocalToCloud() {
    const localConfigs = wx.getStorageSync('savedConfigs') || [];
    const localOnlyConfigs = localConfigs.filter(c => c.isLocal && !c._id.startsWith('imported_'));
    
    if (localOnlyConfigs.length === 0) {
      wx.showToast({
        title: '没有需要同步的配置',
        icon: 'none'
      });
      return;
    }
    
    wx.showModal({
      title: '同步到云端',
      content: `发现 ${localOnlyConfigs.length} 个本地配置，是否同步到云端？`,
      success: async (res) => {
        if (res.confirm) {
          await this.doSyncToCloud(localOnlyConfigs);
        }
      }
    });
  },

  // 执行同步
  async doSyncToCloud(configs) {
    wx.showLoading({
      title: '同步中...',
      mask: true
    });
    
    let successCount = 0;
    let failCount = 0;
    
    for (const config of configs) {
      try {
        await wx.cloud.callFunction({
          name: 'configManager',
          data: {
            action: 'save',
            data: {
              configName: config.configName,
              satelliteParams: config.satelliteParams,
              linkParams: config.linkParams,
              calculationResults: config.calculationResults || {},
              noiseRatioMode: config.noiseRatioMode || 'ebno',
              markedParams: config.markedParams || [],
              highlightedRows: config.highlightedRows || []
            }
          }
        });
        successCount++;
      } catch (error) {
        console.error('同步配置失败:', config.configName, error);
        failCount++;
      }
    }
    
    wx.hideLoading();
    
    wx.showModal({
      title: '同步完成',
      content: `成功：${successCount} 个，失败：${failCount} 个`,
      showCancel: false
    });
    
    this.loadConfigs();
  },

  // ArrayBuffer转字符串 (使用 UTF-8 解码)
  arrayBufferToString(buffer) {
    if (typeof TextDecoder !== 'undefined') {
      const decoder = new TextDecoder('utf-8');
      return decoder.decode(buffer);
    }
    
    const view = new Uint8Array(buffer);
    let str = '';
    for (let i = 0; i < view.length; i++) {
      str += String.fromCharCode(view[i]);
    }
    try {
      return decodeURIComponent(escape(str));
    } catch (e) {
      return str;
    }
  },

  // ============ 多选和导出功能 ============

  // 切换多选模式
  toggleSelectMode() {
    const newMode = !this.data.selectMode;
    this.setData({
      selectMode: newMode,
      selectedConfigs: newMode ? [] : [],
      showExportPanel: false
    });
    // 重置所有配置卡片的滑动状态
    this.resetConfigsSlideState();
  },

  // 切换单个配置的选中状态
  toggleConfigSelection(e) {
    if (!this.data.selectMode) return;
    
    const configId = e.currentTarget.dataset.id;
    const selectedConfigs = [...this.data.selectedConfigs];
    const index = selectedConfigs.indexOf(configId);
    
    if (index > -1) {
      selectedConfigs.splice(index, 1);
    } else {
      selectedConfigs.push(configId);
    }
    
    this.setData({ selectedConfigs });
  },

  // 显示导出面板
  showExportOptions() {
    if (this.data.selectedConfigs.length === 0) {
      wx.showToast({
        title: '请先选择配置',
        icon: 'none'
      });
      return;
    }
    this.setData({ showExportPanel: true });
  },

  // 隐藏导出面板
  hideExportPanel() {
    this.setData({ showExportPanel: false });
  },

  // 选择导出语言
  selectExportLang(e) {
    const lang = e.currentTarget.dataset.lang;
    this.setData({ exportLang: lang });
  },

  // 导出Excel
  async exportExcel() {
    const { selectedConfigs, exportLang } = this.data;
    if (selectedConfigs.length === 0) {
      wx.showToast({ title: '请先选择配置', icon: 'none' });
      return;
    }

    wx.showLoading({ title: '生成Excel中...', mask: true });

    try {
      const configsToExport = await this.getConfigsData(selectedConfigs);
      
      if (configsToExport.length === 0) {
        wx.hideLoading();
        wx.showToast({ title: '没有可导出的数据', icon: 'none' });
        return;
      }

      // 调用云函数生成 Excel 文件
      // 从本地存储读取上次生成的文件ID
      const lastExcelFileID = wx.getStorageSync('lastExcelFileID') || null;
      
      const res = await wx.cloud.callFunction({
        name: 'generateReport',
        data: {
          configs: configsToExport,
          format: 'excel',
          lang: exportLang,
          oldFileID: lastExcelFileID
        }
      });

      if (!res.result || !res.result.success) {
        throw new Error(res.result?.error || '云函数返回错误');
      }

      // 保存新文件ID到本地存储用于下次清理
      wx.setStorageSync('lastExcelFileID', res.result.fileID);

      // 使用云存储下载文件（比 wx.downloadFile 更可靠）
      const downloadRes = await wx.cloud.downloadFile({
        fileID: res.result.fileID
      });

      if (!downloadRes.tempFilePath) {
        throw new Error('文件下载失败');
      }

      wx.hideLoading();
      this.setData({ showExportPanel: false });
      
      // 保存文件信息
      this._lastExportedFile = downloadRes.tempFilePath;
      this._lastExportedFileName = res.result.fileName;
      
      // 使用openDocument打开文件，用户可通过菜单分享
      wx.openDocument({
        filePath: downloadRes.tempFilePath,
        showMenu: true, // 显示右上角菜单，可转发
        fileType: 'xlsx',
        success: () => {
          wx.showToast({ 
            title: '点击右上角可转发', 
            icon: 'none',
            duration: 3000
          });
        },
        fail: (err) => {
          console.error('打开文档失败:', err);
          wx.showModal({
            title: '导出成功',
            content: `Excel文件已生成\n\n文件名: ${res.result.fileName}\n\n请点击右上角菜单转发或保存`,
            showCancel: false
          });
        }
      });
    } catch (error) {
      console.error('导出Excel失败:', error);
      wx.hideLoading();
      
      wx.showModal({
        title: '导出失败',
        content: error.message || '无法导出Excel，请稍后重试',
        showCancel: false
      });
    }
  },

  // 导出PDF（调用云函数生成真正的PDF文件）
  async exportPDF() {
    const { selectedConfigs, exportLang } = this.data;
    if (selectedConfigs.length === 0) {
      wx.showToast({ title: '请先选择配置', icon: 'none' });
      return;
    }

    wx.showLoading({ title: '生成PDF中...', mask: true });

    try {
      const configsToExport = await this.getConfigsData(selectedConfigs);
      
      if (configsToExport.length === 0) {
        wx.hideLoading();
        wx.showToast({ title: '没有可导出的数据', icon: 'none' });
        return;
      }

      // 调用云函数生成 PDF 文件
      // 从本地存储读取上次生成的文件ID
      const lastPdfFileID = wx.getStorageSync('lastPdfFileID') || null;
      
      const res = await wx.cloud.callFunction({
        name: 'generateReport',
        data: {
          configs: configsToExport,
          format: 'pdf',
          lang: exportLang,
          oldFileID: lastPdfFileID
        }
      });

      if (!res.result || !res.result.success) {
        throw new Error(res.result?.error || '云函数返回错误');
      }

      // 保存新文件ID到本地存储用于下次清理
      wx.setStorageSync('lastPdfFileID', res.result.fileID);

      // 使用云存储下载文件（比 wx.downloadFile 更可靠）
      const downloadRes = await wx.cloud.downloadFile({
        fileID: res.result.fileID
      });

      if (!downloadRes.tempFilePath) {
        throw new Error('文件下载失败');
      }

      wx.hideLoading();
      this.setData({ showExportPanel: false });
      
      // 保存文件信息
      this._lastExportedFile = downloadRes.tempFilePath;
      this._lastExportedFileName = res.result.fileName;
      
      // 使用openDocument打开文件，用户可通过菜单分享
      wx.openDocument({
        filePath: downloadRes.tempFilePath,
        showMenu: true, // 显示右上角菜单，可转发
        fileType: 'pdf',
        success: () => {
          wx.showToast({ 
            title: '点击右上角可转发', 
            icon: 'none',
            duration: 3000
          });
        },
        fail: (err) => {
          console.error('打开文档失败:', err);
          wx.showModal({
            title: '导出成功',
            content: `PDF文件已生成\n\n文件名: ${res.result.fileName}\n\n请点击右上角菜单转发或保存`,
            showCancel: false
          });
        }
      });
    } catch (error) {
      console.error('导出PDF失败:', error);
      wx.hideLoading();
      
      wx.showModal({
        title: '导出失败',
        content: error.message || '无法导出PDF，请稍后重试',
        showCancel: false
      });
    }
  },

  // 导出Word（调用云函数生成Word文件）
  async exportWord() {
    const { selectedConfigs, exportLang } = this.data;
    if (selectedConfigs.length === 0) {
      wx.showToast({ title: '请先选择配置', icon: 'none' });
      return;
    }

    wx.showLoading({ title: '生成Word中...', mask: true });

    try {
      const configsToExport = await this.getConfigsData(selectedConfigs);
      
      if (configsToExport.length === 0) {
        wx.hideLoading();
        wx.showToast({ title: '没有可导出的数据', icon: 'none' });
        return;
      }

      // 调用云函数生成 Word 文件
      // 从本地存储读取上次生成的文件ID
      const lastWordFileID = wx.getStorageSync('lastWordFileID') || null;
      
      const res = await wx.cloud.callFunction({
        name: 'generateReport',
        data: {
          configs: configsToExport,
          format: 'word',
          lang: exportLang,
          oldFileID: lastWordFileID
        }
      });

      if (!res.result || !res.result.success) {
        throw new Error(res.result?.error || '云函数返回错误');
      }

      // 保存新文件ID到本地存储用于下次清理
      wx.setStorageSync('lastWordFileID', res.result.fileID);

      // 使用云存储下载文件（比 wx.downloadFile 更可靠）
      const downloadRes = await wx.cloud.downloadFile({
        fileID: res.result.fileID
      });

      if (!downloadRes.tempFilePath) {
        throw new Error('文件下载失败');
      }

      wx.hideLoading();
      this.setData({ showExportPanel: false });
      
      // 保存文件信息
      this._lastExportedFile = downloadRes.tempFilePath;
      this._lastExportedFileName = res.result.fileName;
      
      // 使用openDocument打开文件，用户可通过菜单分享
      wx.openDocument({
        filePath: downloadRes.tempFilePath,
        showMenu: true, // 显示右上角菜单，可转发
        fileType: 'docx',
        success: () => {
          wx.showToast({ 
            title: '点击右上角可转发', 
            icon: 'none',
            duration: 3000
          });
        },
        fail: (err) => {
          console.error('打开文档失败:', err);
          wx.showModal({
            title: '导出成功',
            content: `Word文件已生成\n\n文件名: ${res.result.fileName}\n\n请点击右上角菜单转发或保存`,
            showCancel: false
          });
        }
      });
    } catch (error) {
      console.error('导出Word失败:', error);
      wx.hideLoading();
      
      wx.showModal({
        title: '导出失败',
        content: error.message || '无法导出Word，请稍后重试',
        showCancel: false
      });
    }
  },

  // 获取配置数据（从本地或云端）
  async getConfigsData(configIds) {
    const configsData = [];
    
    for (const configId of configIds) {
      const config = this.data.configs.find(c => c._id === configId);
      if (!config) continue;
      
      if (config.isLocal) {
        // 本地配置，直接从storage获取完整数据
        const localConfigs = wx.getStorageSync('savedConfigs') || [];
        const fullConfig = localConfigs.find(c => c._id === configId);
        if (fullConfig) {
          configsData.push(fullConfig);
        }
      } else {
        // 云端配置，调用云函数获取
        try {
          const res = await wx.cloud.callFunction({
            name: 'configManager',
            data: {
              action: 'load',
              data: { configId }
            }
          });
          if (res.result && res.result.success && res.result.config) {
            configsData.push(res.result.config);
          }
        } catch (error) {
          console.error('获取云端配置失败:', configId, error);
        }
      }
    }
    
    return configsData;
  },

  // ============ 批量分享二维码功能 ============

  // 批量分享配置（生成二维码）
  async batchShareConfigs() {
    const { selectedConfigs, configs } = this.data;
    
    if (selectedConfigs.length === 0) {
      wx.showToast({
        title: '请先选择配置',
        icon: 'none'
      });
      return;
    }
    
    // 检查是否有本地配置
    const hasLocalConfig = selectedConfigs.some(id => {
      const config = configs.find(c => c._id === id);
      return config && config.isLocal;
    });
    
    if (hasLocalConfig) {
      wx.showModal({
        title: '提示',
        content: '选中的配置包含本地配置，本地配置需要先同步到云端才能分享。是否先同步？',
        confirmText: '去同步',
        success: (res) => {
          if (res.confirm) {
            this.syncLocalToCloud();
          }
        }
      });
      return;
    }
    
    // 显示面板并开始加载
    this.setData({
      showBatchQRPanel: true,
      batchQRLoading: true,
      batchShareData: null
    });
    
    try {
      const res = await wx.cloud.callFunction({
        name: 'configManager',
        data: {
          action: 'batchShare',
          data: { 
            configIds: selectedConfigs,
            oldQRFileID: this.data.lastBatchQRFileID // 传递旧的二维码文件ID以便删除
          }
        }
      });
      
      console.log('批量分享结果:', res);
      
      if (res.result && res.result.success) {
        this.setData({
          batchQRLoading: false,
          batchShareData: {
            batchCode: res.result.batchCode,
            qrCodeUrl: res.result.qrCodeUrl,
            qrCodeFileID: res.result.qrCodeFileID,
            configCount: res.result.configCount,
            configNames: res.result.configNames
          },
          lastBatchQRFileID: res.result.qrCodeFileID // 保存新的文件ID供下次删除
        });
      } else {
        throw new Error(res.result?.error || '生成失败');
      }
    } catch (error) {
      console.error('批量分享失败:', error);
      this.setData({
        batchQRLoading: false
      });
      wx.showToast({
        title: error.message || '分享失败',
        icon: 'none'
      });
    }
  },

  // 隐藏批量分享面板
  hideBatchQRPanel() {
    this.setData({
      showBatchQRPanel: false
    });
  },

  // 复制批次码
  copyBatchCode() {
    const { batchShareData } = this.data;
    if (batchShareData && batchShareData.batchCode) {
      wx.setClipboardData({
        data: batchShareData.batchCode,
        success: () => {
          wx.showToast({
            title: '分享码已复制',
            icon: 'success'
          });
        }
      });
    }
  },

  // ============ 批量导入功能 ============

  // 从批次码导入配置
  async importFromBatchCode(batchCode) {
    wx.showLoading({
      title: '获取配置中...',
      mask: true
    });
    
    try {
      const res = await wx.cloud.callFunction({
        name: 'configManager',
        data: {
          action: 'getBatchShared',
          data: { batchCode }
        }
      });
      
      console.log('获取批量分享结果:', res);
      
      if (res.result && res.result.success) {
        wx.hideLoading();
        
        // 显示批量导入确认面板
        this.setData({
          showBatchImportPanel: true,
          batchImportData: {
            configs: res.result.configs,
            configCount: res.result.configCount
          }
        });
      } else {
        throw new Error(res.result?.error || '获取失败');
      }
    } catch (error) {
      console.error('获取批量分享失败:', error);
      wx.hideLoading();
      wx.showModal({
        title: '导入失败',
        content: error.message || '无法获取分享的配置',
        showCancel: false,
        success: () => {
          // 刷新配置列表
          this.loadConfigs();
        }
      });
    }
  },

  // 隐藏批量导入面板
  hideBatchImportPanel() {
    this.setData({
      showBatchImportPanel: false,
      batchImportData: null
    });
    // 刷新配置列表
    this.loadConfigs();
  },

  // 确认批量导入
  async confirmBatchImport() {
    const { batchImportData } = this.data;
    
    if (!batchImportData || !batchImportData.configs) {
      return;
    }
    
    wx.showLoading({
      title: '导入中...',
      mask: true
    });
    
    let successCount = 0;
    let failCount = 0;
    
    for (const config of batchImportData.configs) {
      try {
        const importedName = `[导入] ${config.configName}`;
        
        // 优先保存到云端
        const saveRes = await wx.cloud.callFunction({
          name: 'configManager',
          data: {
            action: 'save',
            data: {
              configName: importedName,
              satelliteParams: config.satelliteParams,
              linkParams: config.linkParams,
              calculationResults: config.calculationResults || {},
              noiseRatioMode: config.noiseRatioMode || 'ebno',
              markedParams: config.markedParams || [],
              highlightedRows: config.highlightedRows || []
            }
          }
        });
        
        if (saveRes.result && saveRes.result.success) {
          successCount++;
        } else {
          throw new Error('保存失败');
        }
      } catch (error) {
        console.error('导入单个配置失败:', config.configName, error);
        
        // 云端失败，保存到本地
        try {
          const localConfigs = wx.getStorageSync('savedConfigs') || [];
          const newConfig = {
            _id: `imported_batch_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
            configName: `[导入] ${config.configName}`,
            satelliteParams: config.satelliteParams,
            linkParams: config.linkParams,
            calculationResults: config.calculationResults || {},
            noiseRatioMode: config.noiseRatioMode || 'ebno',
            markedParams: config.markedParams || [],
            highlightedRows: config.highlightedRows || [],
            createTime: new Date(),
            updateTime: new Date(),
            isLocal: true
          };
          localConfigs.unshift(newConfig);
          wx.setStorageSync('savedConfigs', localConfigs);
          successCount++;
        } catch (e) {
          failCount++;
        }
      }
    }
    
    wx.hideLoading();
    
    this.setData({
      showBatchImportPanel: false,
      batchImportData: null
    });
    
    wx.showToast({
      title: `成功导入 ${successCount} 个`,
      icon: successCount > 0 ? 'success' : 'none'
    });
    
    // 刷新列表
    setTimeout(() => {
      this.loadConfigs();
    }, 500);
  }
});
