// 云函数入口文件 - 生成卫星链路预算报告（Excel/PDF/Word）
const cloud = require('wx-server-sdk');
const ExcelJS = require('exceljs');
const PDFDocument = require('pdfkit');
const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, Table, TableRow, TableCell, WidthType, BorderStyle, TableLayoutType, VerticalAlign, ShadingType } = require('docx');
const path = require('path');
const fs = require('fs');

cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV });

// 翻译文本（与报告页面完全一致）
const TRANSLATIONS = {
  zh: {
    // 标题区
    reportTitle: '卫星通信链路预算分析报告',
    institutionLine: 'LinkLab Satellite Analysis',
    frequencyBandSuffix: '频段',
    // 链路评估
    linkStatus: '链路状态',
    linkMargin: '链路余量',
    systemAvailability: '系统可用度',
    // 状态文本
    statusExcellent: '优秀',
    statusGood: '良好',
    statusQualified: '合格',
    statusPoor: '不足',
    // 系统配置
    sectionSystemConfig: 'I. 系统配置',
    infoRate: '信息速率',
    modulation: '调制方式',
    fecCode: 'FEC码率',
    symbolRate: '符号速率',
    allocBandwidth: '占用带宽',
    uplinkFreq: '上行频率',
    downlinkFreq: '下行频率',
    threshold: '门限',
    // 卫星参数
    sectionSatellite: 'II. 卫星参数',
    sfdRef: '卫星SFD',
    transponderBW: '转发器带宽',
    inputBackoff: '转发器IBO',
    outputBackoff: '转发器OBO',
    satelliteEIRP: 'EIRPs',
    satelliteSFD: '信号到星通量密度',
    satellitePSD: '卫星输出功率谱密度',
    groundPFD: '卫星到地通量密度',
    // 链路质量
    sectionLinkQuality: 'III. 链路质量',
    totalCN: '综合C/N',
    thresholdCN: '门限C/N',
    availability: '可用度',
    ber: '误码率',
    bwUsage: '带宽占用',
    pwrUsage: '功率占用',
    // 上下行链路
    sectionUplink: 'IV. 上行链路',
    sectionDownlink: 'V. 下行链路',
    antennaDiameter: '天线口径',
    antennaGain: '天线增益',
    txPower: '发射功率',
    gtValue: 'G/T值',
    stationEIRP: '地面站EIRP',
    eirpOutput: 'EIRP输出',
    polarization: '极化方式',
    elevation: '仰角',
    polarAngle: '方位角',
    fsl: '自由空间损耗',
    rainAtten: '降雨衰减',
    feederLoss: '馈线损耗',
    uplinkCN: '上行C/N',
    downlinkCN: '下行C/N',
    // 功放配置
    sectionPA: 'VI. 功放配置建议',
    recommendedPower: '推荐功率',
    carrierBW: '载波带宽',
    powerBW: '功率带宽',
    // 汇总
    summaryTitle: '汇总',
    equivalentBwTotal: '等效转发器带宽占用总计',
    linkCount: '链路数量',
    // 页脚
    footerText: '本报告由卫星链路预算计算系统自动生成',
    excelSheetName: '链路预算报告',
    // Excel 专用
    configName: '配置名称',
    satellite: '卫星',
    orbitPosition: '轨道位置',
    frequencyBand: '频段',
    parameter: '参数',
    value: '数值',
    unit: '单位'
  },
  en: {
    // 标题区
    reportTitle: 'Satellite Link Budget Analysis Report',
    institutionLine: 'LinkLab Satellite Analysis',
    frequencyBandSuffix: 'Band',
    // 链路评估
    linkStatus: 'Link Status',
    linkMargin: 'Link Margin',
    systemAvailability: 'Availability',
    // 状态文本
    statusExcellent: 'Excellent',
    statusGood: 'Good',
    statusQualified: 'Qualified',
    statusPoor: 'Poor',
    // 系统配置
    sectionSystemConfig: 'I. System Config',
    infoRate: 'Info Rate',
    modulation: 'Modulation',
    fecCode: 'FEC Code',
    symbolRate: 'Symbol Rate',
    allocBandwidth: 'Bandwidth',
    uplinkFreq: 'Uplink Freq',
    downlinkFreq: 'Downlink Freq',
    threshold: 'Threshold',
    // 卫星参数
    sectionSatellite: 'II. Satellite Params',
    sfdRef: 'Effective SFD',
    transponderBW: 'Transponder BW',
    inputBackoff: 'Input Backoff',
    outputBackoff: 'Output Backoff',
    satelliteEIRP: 'EIRPs',
    satelliteSFD: 'Flux to Satellite',
    satellitePSD: 'Sat Output PSD',
    groundPFD: 'Sat to Ground PFD',
    // 链路质量
    sectionLinkQuality: 'III. Link Quality',
    totalCN: 'Total C/N',
    thresholdCN: 'Threshold C/N',
    availability: 'Availability',
    ber: 'BER',
    bwUsage: 'BW Usage',
    pwrUsage: 'Power Usage',
    // 上下行链路
    sectionUplink: 'IV. Uplink',
    sectionDownlink: 'V. Downlink',
    antennaDiameter: 'Antenna Dia.',
    antennaGain: 'Antenna Gain',
    txPower: 'TX Power',
    gtValue: 'G/T',
    stationEIRP: 'Ground Station EIRP',
    eirpOutput: 'EIRP Output',
    polarization: 'Polarization',
    elevation: 'Elevation',
    polarAngle: 'Azimuth',
    fsl: 'Free Space Loss',
    rainAtten: 'Rain Atten.',
    feederLoss: 'Feeder Loss',
    uplinkCN: 'Uplink C/N',
    downlinkCN: 'Downlink C/N',
    // 功放配置
    sectionPA: 'VI. PA Recommendation',
    recommendedPower: 'Rec. Power',
    carrierBW: 'Carrier BW',
    powerBW: 'Power BW',
    // 汇总
    summaryTitle: 'Summary',
    equivalentBwTotal: 'Total Equivalent Transponder BW',
    linkCount: 'Link Count',
    // 页脚
    footerText: 'Generated by Satellite Link Budget System',
    excelSheetName: 'Link Budget Report',
    // Excel 专用
    configName: 'Config Name',
    satellite: 'Satellite',
    orbitPosition: 'Orbit Position',
    frequencyBand: 'Freq Band',
    parameter: 'Parameter',
    value: 'Value',
    unit: 'Unit'
  }
};

// 获取链路状态
function getLinkStatus(linkMargin) {
  try {
    const margin = parseFloat(linkMargin);
    if (margin >= 3) return 'excellent';
    if (margin >= 1) return 'good';
    if (margin >= 0) return 'qualified';
    return 'poor';
  } catch (e) {
    return 'poor';
  }
}

// 格式化日期时间
function formatDateTime(date, format) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  const hours = String(date.getHours()).padStart(2, '0');
  const minutes = String(date.getMinutes()).padStart(2, '0');
  const seconds = String(date.getSeconds()).padStart(2, '0');
  
  return format
    .replace('YYYY', year)
    .replace('MM', month)
    .replace('DD', day)
    .replace('HH', hours)
    .replace('mm', minutes)
    .replace('ss', seconds);
}

// 自适应格式化带宽（输入为kHz，自动选择合适的单位）
function formatBandwidth(bandwidthKHz) {
  const bw = parseFloat(bandwidthKHz) || 0;
  
  // 转换为MHz
  const bwMHz = bw / 1000;
  if (bwMHz >= 0.01) {
    // MHz显示（保留2位小数，至少0.01MHz）
    return `${bwMHz.toFixed(2)}MHz`;
  }
  
  // kHz显示
  if (bw >= 0.01) {
    return `${bw.toFixed(2)}kHz`;
  }
  
  // Hz显示
  const bwHz = bw * 1000;
  return `${bwHz.toFixed(2)}Hz`;
}

// 生成 Excel 报告（简洁格式：两列布局，左标题右数值+单位）
// 共享辅助：在 workbook 中添加计算结果 Sheet（4列三线表：参数标题 | 参数值 | 参数标题 | 参数值）
function _writeResultsToSheet(workbook, sheetName, configs, lang, compareMode) {
  const isZh = (lang !== 'en');
  const t = TRANSLATIONS[lang] || TRANSLATIONS.zh;
  const sheet = workbook.addWorksheet(sheetName.substring(0, 31));

  const u = (val, unit) => {
    if (val === '' || val === null || val === undefined) return '--';
    return unit ? `${val} ${unit}` : String(val);
  };

  const FONT = 'Times New Roman';
  const headerFont = { bold: true, size: 11, name: FONT, color: { argb: 'FF000000' } };
  const sectionFont = { bold: true, italic: true, size: 11, name: FONT, color: { argb: 'FF000000' } };
  const labelFont = { size: 11, name: FONT, color: { argb: 'FF333333' } };
  const valFont = { size: 11, name: FONT, color: { argb: 'FF000000' } };
  const topRule = { style: 'medium', color: { argb: 'FF000000' } };
  const bottomRule = { style: 'medium', color: { argb: 'FF000000' } };
  const thinRule = { style: 'thin', color: { argb: 'FF000000' } };
  const noBorder = { style: 'none' };
  const headerBorder = { top: topRule, bottom: thinRule, left: noBorder, right: noBorder };
  const sectionBorder = { top: thinRule, bottom: thinRule, left: noBorder, right: noBorder };
  const dataBorder = { top: noBorder, bottom: noBorder, left: noBorder, right: noBorder };
  const lastRowBorder = { top: noBorder, bottom: bottomRule, left: noBorder, right: noBorder };
  const yellowFill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFFF00' } };
  const redFont = { size: 11, name: FONT, color: { argb: 'FFCC0000' } };
  const redBoldFont = { bold: true, size: 11, name: FONT, color: { argb: 'FFCC0000' } };

  const S = 'section', D = 'data';
  const allLinksData = [];
  let totalEquivalentBW = 0;

  for (const config of configs) {
    const calc = config.calculationResults || {};
    if (Object.keys(calc).length === 0) continue;
    const sat = config.satelliteParams || {};
    const links = config.linkParams || {};

    for (const linkNum of Object.keys(calc)) {
      const r = calc[linkNum];
      const lp = links[linkNum] || {};
      const linkMargin = r.linkmargin || '0';
      const status = getLinkStatus(linkMargin);
      const statusText = t[`status${status.charAt(0).toUpperCase() + status.slice(1)}`];
      const availWeather = parseFloat(r.systemAvailabilityResult) >= 100
        ? (isZh ? '（晴天）' : ' (Clear Sky)') : (isZh ? '（雨天）' : ' (Rain)');
      const allocBW = parseFloat(r.allocBandwidthResult) || 0;
      const powerBW = parseFloat(r.PowerBWResult) || 0;
      const equivalentBW = Math.max(allocBW, powerBW);
      totalEquivalentBW += equivalentBW;
      const eqBWFmt = formatBandwidth(equivalentBW);
      const configTitle = `${config.configName || 'Unknown'} | ${sat.satelliteName || ''} | ${sat.frequencyBand || ''}${t.frequencyBandSuffix}`;

      // 4列配对行：[type, label1, val1, label2?, val2?]
      const rows = [
        [S, isZh ? '卫星参数' : 'Satellite Parameters'],
        [D, isZh ? '卫星名称' : 'Satellite', u(sat.satelliteName), isZh ? '轨道位置' : 'Orbit', u(sat.orbitPosition, '°E')],
        [D, isZh ? '频段' : 'Band', u(sat.frequencyBand), isZh ? '上行频率/极化' : 'UL Freq/Pol', `${u(r.uplinkFrequencyResult, 'GHz')} (${r.uplinkPolarizationResult || ''})`],
        [D, isZh ? '下行频率/极化' : 'DL Freq/Pol', `${u(r.downlinkFrequencyResult, 'GHz')} (${r.downlinkPolarizationResult || ''})`, isZh ? '转发器带宽' : 'Xpdr BW', u(sat.transponderBandwidth, 'MHz')],
        [D, isZh ? '卫星EIRP' : 'Sat. EIRP', u(r.EIRPsResult, 'dBW'), isZh ? '卫星SFD' : 'Sat. SFD', u(r.SFDsResult, 'dBW/m²')],
        [D, isZh ? '转发器IBO' : 'BOi', u(sat.BOi, 'dB'), isZh ? '转发器OBO' : 'BOo', u(sat.BOo, 'dB')],
        [S, isZh ? '载波参数' : 'Carrier Parameters'],
        [D, isZh ? '信息速率' : 'Info Rate', u(r.infoRateResult, 'kbps'), isZh ? '调制方式' : 'Modulation', u(r.modulationResult)],
        [D, 'FEC', u(r.fecResult), isZh ? '符号速率' : 'Symbol Rate', u(r.symbolRateResult, 'ksps')],
        [D, isZh ? '上行频率' : 'UL Freq.', u(r.uplinkFrequencyResult, 'GHz'), isZh ? '下行频率' : 'DL Freq.', u(r.downlinkFrequencyResult, 'GHz')],
        [D, isZh ? '门限Eb/N0' : 'Thresh. Eb/N0', u(r.ebnoResult, 'dB'), isZh ? '门限Es/N0' : 'Thresh. Es/N0', u(r.esnoResult, 'dB')],
        [S, isZh ? '上行链路' : 'Uplink'],
        [D, isZh ? '发信站位置' : 'TX Station', u(lp.earthStationLocation), isZh ? '天线口径' : 'Antenna Dia.', u(r.earthAntennaDiameterResult, 'm')],
        [D, isZh ? '天线增益' : 'Antenna Gain', u(r.txAntennaGainResult, 'dB'), isZh ? '发射功率' : 'TX Power', `${u(r.selectedPowerWResult, 'W')} (${u(r.selectedPowerResult, 'dBW')})`],
        [D, isZh ? '地面站EIRP' : 'Station EIRP', u(r.stationEIRPResult, 'dBW'), isZh ? '仰角' : 'Elevation', u(r.elevationResult, '°')],
        [D, isZh ? '方位角' : 'Azimuth', u(r.azimuthResult, '°'), isZh ? '自由空间损耗' : 'FSL', u(r.uplinkFSLResult, 'dB')],
        [D, isZh ? '降雨衰减' : 'Rain Atten.', u(r.uplinkRainAttenuation, 'dB'), isZh ? '馈线损耗' : 'Feeder Loss', u(r.feederLossResult, 'dB')],
        [D, isZh ? '上行C/N' : 'Uplink C/N', u(r.uplinkCN, 'dB')],
        [S, isZh ? '下行链路' : 'Downlink'],
        [D, isZh ? '收信站位置' : 'RX Station', u(lp.rxEarthStationLocation), isZh ? '天线口径' : 'Antenna Dia.', u(r.rxAntennaDiameterResult, 'm')],
        [D, isZh ? '天线增益' : 'Antenna Gain', u(r.rxAntennaGainResult, 'dB'), 'G/T', u(r.gOverTeResult, 'dB/K')],
        [D, isZh ? '仰角' : 'Elevation', u(r.rxElevationResult, '°'), isZh ? '方位角' : 'Azimuth', u(r.rxAzimuthResult, '°')],
        [D, isZh ? '自由空间损耗' : 'FSL', u(r.downlinkFSLResult, 'dB'), isZh ? '降雨衰减' : 'Rain Atten.', u(r.downlinkRainAttenuationResult, 'dB')],
        [D, isZh ? '馈线损耗' : 'Feeder Loss', u(r.rxFeederLossResult, 'dB'), isZh ? '下行C/N' : 'Downlink C/N', u(r.downlinkCN, 'dB')],
        [S, isZh ? '结论' : 'Conclusion'],
        [D, isZh ? '综合C/N' : 'Total C/N', u(r.carrierTotalCN, 'dB'), isZh ? '门限C/N' : 'Thresh. C/N', u(r.thresholdCN, 'dB')],
        [D, isZh ? '链路余量' : 'Link Margin', u(linkMargin, 'dB'), isZh ? '链路状态' : 'Link Status', statusText],
        [D, isZh ? '系统可用度' : 'Availability', u(r.systemAvailabilityResult, '%') + availWeather, isZh ? '推荐功放功率' : 'Rec. PA Power', u(r.paRecommendation, 'W')],
        [D, isZh ? '占用带宽' : 'Alloc. BW', u(r.allocBandwidthResult, 'kHz'), isZh ? '功率带宽' : 'Power BW', u(r.PowerBWResult, 'kHz')],
        ['red', isZh ? '带宽占用' : 'BW Usage', u(r.bandwidthUsageRatio, '%'), isZh ? '功率占用' : 'Power Usage', u(r.powerUsageRatio, '%')],
        [D, isZh ? '等效占用带宽' : 'Equiv. BW', eqBWFmt]
      ];
      allLinksData.push({ configTitle, rows, equivalentBW });
    }
  }

  if (allLinksData.length === 0) return { totalEquivalentBW: 0, linkCount: 0 };

  const linkCount = allLinksData.length;
  const C4 = 4; // 每链路4列
  const columns = [];
  for (let i = 0; i < linkCount; i++) {
    columns.push({ width: 14 }, { width: 16 }, { width: 14 }, { width: 16 });
  }
  sheet.columns = columns;

  const baseRows = compareMode && linkCount > 1 ? allLinksData[0].rows : null;

  // 标题行（合并4列，顶粗线）
  let ci = 1;
  for (const ld of allLinksData) {
    sheet.mergeCells(1, ci, 1, ci + C4 - 1);
    const cell = sheet.getCell(1, ci);
    cell.value = `${ld.configTitle}    ${new Date().toISOString().slice(0, 10)}`;
    cell.font = headerFont;
    cell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };
    for (let c = ci; c < ci + C4; c++) sheet.getCell(1, c).border = headerBorder;
    ci += C4;
  }
  sheet.getRow(1).height = 20;

  // 数据行
  const maxRows = Math.max(...allLinksData.map(d => d.rows.length));
  let lastDataRowNum = 2;

  for (let ri = 0; ri < maxRows; ri++) {
    const rowNum = ri + 2;
    ci = 1;
    for (let li = 0; li < linkCount; li++) {
      const ld = allLinksData[li];
      const rd = ld.rows[ri];
      if (!rd) { ci += C4; continue; }

      if (rd[0] === S) {
        sheet.mergeCells(rowNum, ci, rowNum, ci + C4 - 1);
        const cell = sheet.getCell(rowNum, ci);
        cell.value = rd[1];
        cell.font = sectionFont;
        cell.border = sectionBorder;
        cell.alignment = { vertical: 'middle' };
        for (let c = ci + 1; c < ci + C4; c++) sheet.getCell(rowNum, c).border = sectionBorder;
      } else {
        const isRed = rd[0] === 'red';
        const lf = isRed ? redBoldFont : labelFont;
        const vf = isRed ? redFont : valFont;
        const l1 = sheet.getCell(rowNum, ci);
        l1.value = rd[1]; l1.font = lf; l1.border = dataBorder; l1.alignment = { vertical: 'middle' };
        const v1 = sheet.getCell(rowNum, ci + 1);
        v1.value = rd[2]; v1.font = vf; v1.border = dataBorder; v1.alignment = { vertical: 'middle' };

        if (rd.length >= 5) {
          const l2 = sheet.getCell(rowNum, ci + 2);
          l2.value = rd[3]; l2.font = lf; l2.border = dataBorder; l2.alignment = { vertical: 'middle' };
          const v2 = sheet.getCell(rowNum, ci + 3);
          v2.value = rd[4]; v2.font = vf; v2.border = dataBorder; v2.alignment = { vertical: 'middle' };
          if (baseRows && li > 0) {
            const br = baseRows[ri] || [];
            if (rd[2] !== '--' && br[2] !== '--' && rd[2] !== br[2]) { l1.fill = yellowFill; v1.fill = yellowFill; }
            if (rd[4] !== '--' && br[4] !== '--' && rd[4] !== br[4]) { l2.fill = yellowFill; v2.fill = yellowFill; }
          }
        } else {
          sheet.mergeCells(rowNum, ci + 2, rowNum, ci + 3);
          sheet.getCell(rowNum, ci + 2).border = dataBorder;
          if (baseRows && li > 0) {
            const br = baseRows[ri] || [];
            if (rd[2] !== '--' && br[2] !== '--' && rd[2] !== br[2]) { l1.fill = yellowFill; v1.fill = yellowFill; }
          }
        }
        lastDataRowNum = rowNum;
      }
      ci += C4;
    }
    const fr = allLinksData[0].rows[ri];
    sheet.getRow(rowNum).height = (fr && fr[0] === S) ? 18 : 17;
  }

  // 底粗线
  for (let c = 1; c <= linkCount * C4; c++) {
    sheet.getCell(lastDataRowNum, c).border = lastRowBorder;
  }

  // 汇总行（非对比模式）
  if (!compareMode) {
    const sumRow = lastDataRowNum + 2;
    sheet.mergeCells(sumRow, 1, sumRow, linkCount * C4);
    const sumCell = sheet.getCell(sumRow, 1);
    const totalFmt = formatBandwidth(totalEquivalentBW);
    sumCell.value = isZh
      ? `本报告共包含 ${linkCount} 条链路，等效转发器带宽占用总计为 ${totalFmt}。`
      : `This report contains ${linkCount} links with a total equivalent transponder bandwidth of ${totalFmt}.`;
    sumCell.font = { bold: true, size: 11, name: FONT };
    sumCell.alignment = { horizontal: 'center', vertical: 'middle' };
    sumCell.border = { top: topRule, bottom: bottomRule, left: noBorder, right: noBorder };
    sheet.getRow(sumRow).height = 22;
  }

  return { totalEquivalentBW, linkCount };
}

async function generateExcel(configs, lang, compareMode = false) {
  const t = TRANSLATIONS[lang] || TRANSLATIONS.zh;
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Satellite Link Budget System';
  workbook.created = new Date();

  _writeResultsToSheet(workbook, t.excelSheetName.substring(0, 31), configs, lang, compareMode);

  const buffer = await workbook.xlsx.writeBuffer();
  return buffer;
}

// 生成 PDF 报告（优化版 - 专业样式）
async function generatePDF(configs, lang) {
  const t = TRANSLATIONS[lang] || TRANSLATIONS.zh;
  
  // 加载字体
  const chineseFontPath = path.join(__dirname, 'fonts', 'NotoSansSC-Regular.ttf');
  const englishFontPath = path.join(__dirname, 'fonts', 'GoogleSansFlex-VariableFont_GRAD,ROND,opsz,slnt,wdth,wght.ttf');
  const hasChinese = fs.existsSync(chineseFontPath);
  const hasEnglish = fs.existsSync(englishFontPath);
  
  return new Promise((resolve, reject) => {
    const chunks = [];
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 40, bottom: 40, left: 45, right: 45 },
      info: { Title: t.reportTitle, Author: 'LinkLab Satellite Analysis' }
    });
    
    // 注册中文字体和英文字体
    if (hasChinese) {
      doc.registerFont('Chinese', chineseFontPath);
    }
    if (hasEnglish) {
      doc.registerFont('English', englishFontPath);
    }
    
    // 字体辅助函数
    const font = (size) => {
      doc.font(hasChinese ? 'Chinese' : 'Helvetica').fontSize(size);
      return doc;
    };
    const fontBold = (size) => {
      doc.font(hasChinese ? 'Chinese' : 'Helvetica-Bold').fontSize(size);
      return doc;
    };
    const fontEn = (size) => {
      doc.font(hasEnglish ? 'English' : 'Helvetica').fontSize(size);
      return doc;
    };
    const fontEnBold = (size) => {
      doc.font(hasEnglish ? 'English' : 'Helvetica-Bold').fontSize(size);
      return doc;
    };
    
    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    
    // 颜色
    const C = {
      primary: '#0d47a1',
      accent: '#c9a227',
      excellent: '#1b5e20',
      good: '#f57f17',
      qualified: '#e65100',
      poor: '#b71c1c',
      text: '#1a1a2e',
      gray: '#546e7a',
      light: '#90a4ae',
      bg: '#f5f5f5',
      white: '#ffffff',
      border: '#e0e0e0'
    };
    
    const W = 505; // page width
    const L = 45;  // left margin
    let page = 0;
    
    // ===== 预定义格式化函数（移到循环外部提升性能）=====
    const formatPFD = (val) => {
      if (!val) return '';
      const num = String(val).replace(/[^0-9.-]/g, '');
      return num ? `${num} dBW/m2` : val;
    };
    const formatPSD = (val) => {
      if (!val) return '';
      const num = String(val).replace(/[^0-9.-]/g, '');
      return num ? `${num} dBW/Hz` : val;
    };
    const superscriptToNormal = {
      '⁰': '0', '¹': '1', '²': '2', '³': '3', '⁴': '4',
      '⁵': '5', '⁶': '6', '⁷': '7', '⁸': '8', '⁹': '9', '⁻': '-'
    };
    const formatBER = (val) => {
      if (!val) return '';
      let str = String(val);
      for (const [sup, norm] of Object.entries(superscriptToNormal)) {
        str = str.replace(new RegExp(sup, 'g'), norm);
      }
      return str.replace(/×/g, 'x');
    };
    
    // 预先计算等效转发器带宽总计
    let totalEquivalentBW = 0;
    let totalLinkCount = 0;
    for (const config of configs) {
      const calc = config.calculationResults || {};
      for (const linkNum of Object.keys(calc)) {
        const r = calc[linkNum];
        const allocBW = parseFloat(r.allocBandwidthResult) || 0;
        const powerBW = parseFloat(r.PowerBWResult) || 0;
        totalEquivalentBW += Math.max(allocBW, powerBW);
        totalLinkCount++;
      }
    }
    const totalEquivalentBWFormatted = formatBandwidth(totalEquivalentBW);
    
    for (const config of configs) {
      const calc = config.calculationResults || {};
      if (Object.keys(calc).length === 0) continue;
      
      const sat = config.satelliteParams || {};
      const links = config.linkParams || {};
      
      for (const linkNum of Object.keys(calc)) {
        const r = calc[linkNum];
        const lp = links[linkNum] || {};
        
        if (page > 0) doc.addPage();
        page++;
        
        let y = 35;
        
        // ===== 页眉装饰 =====
        doc.rect(L, y, W, 3).fill(C.primary);
        doc.rect(L, y + 3, W * 0.25, 1).fill(C.accent);
        
        // 左上角配置名称
        const configName = config.configName || 'Configuration';
        font(8).fillColor(C.gray).text(configName, L + 5, y + 6, { width: W * 0.4 });
        
        // 右上角品牌标识
        fontEnBold(7).fillColor(C.light).text('LINKLAB', L + W - 100, y + 6, { width: 100, align: 'right' });
        
        y += 18;
        
        // ===== 标题 =====
        fontBold(20).fillColor(C.primary).text(t.reportTitle, L, y, { width: W, align: 'center' });
        y += 28;
        
        // 分隔线
        doc.rect(L + W * 0.35, y, W * 0.3, 2).fill(C.accent);
        y += 10;
        
        // 副标题
        font(10).fillColor(C.gray).text(
          `${sat.satelliteName || ''} · ${sat.orbitPosition || ''}°E · ${sat.frequencyBand || ''} ${t.frequencyBandSuffix}`,
          L, y, { width: W, align: 'center' }
        );
        y += 14;
        font(8).fillColor(C.light).text(formatDateTime(new Date(), 'YYYY-MM-DD HH:mm'), L, y, { width: W, align: 'center' });
        y += 20;
        
        // ===== 核心指标 =====
        const margin = r.linkmargin || '0';
        const status = getLinkStatus(margin);
        const statusText = t[`status${status.charAt(0).toUpperCase() + status.slice(1)}`];
        const statusColor = C[status] || C.qualified;
        
        doc.rect(L, y, W, 50).fill(C.bg);
        
        const cw = W / 3;
        // 链路状态
        font(8).fillColor(C.light).text(t.linkStatus, L + 10, y + 8, { width: cw - 20 });
        fontBold(16).fillColor(statusColor).text(statusText, L + 10, y + 24, { width: cw - 20 });
        
        // 链路余量
        doc.rect(L + cw, y, cw, 50).fill(C.primary);
        font(8).fillColor(C.white).text(t.linkMargin, L + cw + 10, y + 8, { width: cw - 20 });
        fontBold(18).fillColor(C.white).text(`${margin} dB`, L + cw + 10, y + 24, { width: cw - 20 });
        
        // 可用度
        const weatherText = parseFloat(r.systemAvailabilityResult) >= 100 ? (lang === 'zh' ? '（晴天）' : ' (Clear)') : (lang === 'zh' ? '（雨天）' : ' (Rain)');
        font(8).fillColor(C.light).text(t.systemAvailability, L + cw * 2 + 10, y + 8, { width: cw - 20 });
        fontBold(16).fillColor(C.text).text(`${r.systemAvailabilityResult || ''}%${weatherText}`, L + cw * 2 + 10, y + 24, { width: cw - 20 });
        
        y += 58;
        
        // ===== 简化的表格绘制函数 =====
        const drawTable = (x, ty, w, title, rows, color = C.primary) => {
          doc.rect(x, ty, w, 20).fill(color);
          doc.rect(x, ty + 4, 3, 12).fill(C.accent);
          fontBold(9).fillColor(C.white).text(title, x + 10, ty + 5, { width: w - 15 });
          ty += 22;
          
          rows.forEach((row, i) => {
            doc.rect(x, ty, w, 16).fill(i % 2 === 0 ? C.white : C.bg);
            font(7).fillColor(C.gray).text(row[0], x + 5, ty + 4, { width: w * 0.55 });
            font(7).fillColor(row[2] ? C.primary : C.text).text(row[1], x + w * 0.55, ty + 4, { width: w * 0.42, align: 'right' });
            ty += 16;
          });
          doc.rect(x, y + 22, w, ty - y - 22).lineWidth(0.5).stroke(C.border);
          return ty + 5;
        };
        
        // ===== 三列表格 =====
        const c3w = (W - 12) / 3;
        
        const sysRows = [
          [t.infoRate, `${r.infoRateResult || ''} kbps`],
          [t.modulation, r.modulationResult || ''],
          [t.fecCode, r.fecResult || ''],
          [t.symbolRate, `${r.symbolRateResult || ''} ksps`],
          [t.allocBandwidth, `${r.allocBandwidthResult || ''} kHz`],
          [t.uplinkFreq, `${r.uplinkFrequencyResult || ''} GHz`],
          [t.downlinkFreq, `${r.downlinkFrequencyResult || ''} GHz`],
          [t.threshold, `${r.ebnoResult || ''} dB`]
        ];
        
        const satRows = [
          [t.sfdRef, r.SFDsResult || ''],
          [t.transponderBW, `${sat.transponderBandwidth || ''} MHz`],
          [t.inputBackoff, `${sat.BOi || ''} dB`],
          [t.outputBackoff, `${sat.BOo || ''} dB`],
          [t.satelliteEIRP, `${r.EIRPsResult || ''} dBW`],
          [t.satelliteSFD, formatPFD(r.PFDcResult)],
          [t.satellitePSD, formatPSD(r.satellitePSDResult)],
          [t.groundPFD, formatPFD(r.satellitePFD)]
        ];
        
        const qualRows = [
          [t.totalCN, `${r.carrierTotalCN || ''} dB`, true],
          [t.thresholdCN, `${r.thresholdCN || ''} dB`],
          [t.linkMargin, `${r.linkmargin || ''} dB`, true],
          ['Es/N0', `${r.esnoResult || ''} dB`],
          [t.availability, `${r.systemAvailabilityResult || ''}%` + (parseFloat(r.systemAvailabilityResult) >= 100 ? (lang === 'zh' ? '（晴天）' : '(Clear)') : (lang === 'zh' ? '（雨天）' : '(Rain)'))],
          [t.ber, formatBER(r.berResult)],
          [t.bwUsage, `${r.bandwidthUsageRatio || ''}%`],
          [t.pwrUsage, `${r.powerUsageRatio || ''}%`]
        ];
        
        const y1 = drawTable(L, y, c3w, t.sectionSystemConfig, sysRows);
        const y2 = drawTable(L + c3w + 6, y, c3w, t.sectionSatellite, satRows, '#1565c0');
        const y3 = drawTable(L + c3w * 2 + 12, y, c3w, t.sectionLinkQuality, qualRows);
        y = Math.max(y1, y2, y3);
        
        // ===== 双列表格：上下行链路 =====
        const c2w = (W - 8) / 2;
        
        const upRows = [
          [t.antennaDiameter, `${r.earthAntennaDiameterResult || ''} m`],
          [t.antennaGain, `${r.txAntennaGainResult || ''} dB`],
          [t.txPower, `${r.selectedPowerWResult || ''} W`],
          [t.stationEIRP, `${r.stationEIRPResult || ''} dBW`],
          [t.polarization, r.uplinkPolarizationResult || ''],
          [t.elevation, `${r.elevationResult || ''}°`],
          [t.polarAngle, `${r.azimuthResult || ''}°`],
          [t.fsl, `${r.uplinkFSLResult || ''} dB`],
          [t.rainAtten, `${r.uplinkRainAttenuation || ''} dB`],
          [t.feederLoss, `${r.feederLossResult || ''} dB`],
          [t.uplinkCN, `${r.uplinkCN || ''} dB`, true]
        ];
        
        const downRows = [
          [t.antennaDiameter, `${r.rxAntennaDiameterResult || ''} m`],
          [t.antennaGain, `${r.rxAntennaGainResult || ''} dB`],
          [t.gtValue, `${r.gOverTeResult || ''} dB/K`],
          [t.eirpOutput, `${r.RXeirpPerCarrierResult || ''} dBW`],
          [t.polarization, r.downlinkPolarizationResult || ''],
          [t.elevation, `${r.rxElevationResult || ''}°`],
          [t.polarAngle, `${r.rxAzimuthResult || ''}°`],
          [t.fsl, `${r.downlinkFSLResult || ''} dB`],
          [t.rainAtten, `${r.downlinkRainAttenuationResult || ''} dB`],
          [t.feederLoss, `${r.rxFeederLossResult || ''} dB`],
          [t.downlinkCN, `${r.downlinkCN || ''} dB`, true]
        ];
        
        const upY = drawTable(L, y, c2w, `${t.sectionUplink} · ${lp.earthStationLocation || ''}`, upRows, '#1565c0');
        const downY = drawTable(L + c2w + 8, y, c2w, `${t.sectionDownlink} · ${lp.rxEarthStationLocation || ''}`, downRows, '#1565c0');
        y = Math.max(upY, downY);
        
        // ===== 功放配置 =====
        doc.rect(L, y, W, 42).fill(C.bg);
        doc.rect(L, y, 3, 42).fill(C.accent);
        fontBold(9).fillColor(C.primary).text(t.sectionPA, L + 12, y + 6);
        
        const pw = (W - 140) / 3;
        font(7).fillColor(C.light).text(t.recommendedPower, L + 130, y + 6);
        fontBold(11).fillColor(C.text).text(`${r.paRecommendation || ''} W`, L + 130, y + 18);
        font(7).fillColor(C.gray).text(`(${r.paRecommendationdBResult || ''} dBW)`, L + 130, y + 32);
        
        font(7).fillColor(C.light).text(t.carrierBW, L + 130 + pw, y + 6);
        fontBold(11).fillColor(C.text).text(`${r.allocBandwidthResult || ''} kHz`, L + 130 + pw, y + 18);
        
        font(7).fillColor(C.light).text(t.powerBW, L + 130 + pw * 2, y + 6);
        fontBold(11).fillColor(C.text).text(`${r.PowerBWResult || ''} kHz`, L + 130 + pw * 2, y + 18);
        
        y += 50;
        
        // ===== 页脚 =====
        doc.rect(L, 780, W, 0.5).fill(C.border);
        font(7).fillColor(C.light).text(t.footerText, L, 785, { width: W * 0.7 });
        font(7).fillColor(C.light).text(`Page ${page}`, L, 785, { width: W, align: 'right' });
        doc.rect(L, 795, W, 2).fill(C.primary);
        doc.rect(L + W * 0.75, 795, W * 0.25, 2).fill(C.accent);
      }
    }
    
    // ===== 在最后一页末尾添加汇总信息 =====
    if (totalLinkCount > 1) {
      // 获取当前页面的y位置（功放配置后，页脚前）
      // 在页脚上方添加汇总信息
      const summaryY = 745; // 页脚上方位置
      
      const summaryText = lang === 'zh' 
        ? `本报告共包含 ${totalLinkCount} 条链路，等效转发器带宽占用总计为 ${totalEquivalentBWFormatted}。`
        : `This report contains ${totalLinkCount} links with a total equivalent transponder bandwidth of ${totalEquivalentBWFormatted}.`;
      
      // 绘制汇总框
      doc.rect(L, summaryY, W, 28).fill(C.bg);
      doc.rect(L, summaryY, 3, 28).fill(C.accent);
      fontBold(10).fillColor(C.text).text(summaryText, L + 10, summaryY + 8, { width: W - 20, align: 'center' });
    }
    
    doc.end();
  });
}

// 生成 Word 报告（仿宋四号字，单倍行距，首行缩进）
async function generateWord(configs, lang) {
  const t = TRANSLATIONS[lang] || TRANSLATIONS.zh;
  
  // 计算等效转发器带宽总计
  let totalEquivalentBW = 0;
  let linkIndex = 0;
  
  const children = [];
  
  for (const config of configs) {
    const calc = config.calculationResults || {};
    if (Object.keys(calc).length === 0) continue;
    
    const sat = config.satelliteParams || {};
    const links = config.linkParams || {};
    
    for (const linkNum of Object.keys(calc)) {
      const r = calc[linkNum];
      const lp = links[linkNum] || {};
      linkIndex++;
      
      // 计算等效带宽
      const allocBW = parseFloat(r.allocBandwidthResult) || 0;
      const powerBW = parseFloat(r.PowerBWResult) || 0;
      const equivalentBW = Math.max(allocBW, powerBW);
      totalEquivalentBW += equivalentBW;
      
      // 链路状态
      const linkMargin = r.linkmargin || '0';
      const status = getLinkStatus(linkMargin);
      const statusText = t[`status${status.charAt(0).toUpperCase() + status.slice(1)}`];
      
      // 链路标题
      const linkTitle = lang === 'zh' 
        ? `链路${linkIndex}：${config.configName || '未命名配置'}`
        : `Link ${linkIndex}: ${config.configName || 'Unnamed Config'}`;
      
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: linkTitle,
              font: 'FangSong',
              size: 28, // 四号字 = 14pt = 28 half-points
              bold: true
            })
          ],
          spacing: { before: 240, after: 120, line: 240 } // 单倍行距
        })
      );
      
      // 卫星参数段落
      const satParamsText = lang === 'zh'
        ? `卫星参数：本链路使用${sat.satelliteName || ''}卫星，轨道位置${sat.orbitPosition || ''}°E，${sat.frequencyBand || ''}频段，频率：${r.uplinkFrequencyResult || ''}GHz（${r.uplinkPolarizationResult || ''}）/${r.downlinkFrequencyResult || ''}GHz（${r.downlinkPolarizationResult || ''}），转发器带宽${sat.transponderBandwidth || ''}MHz，卫星EIRP为${r.EIRPsResult || ''}dBW，卫星SFD为${r.SFDsResult || ''}dBW/m²，转发器IBO ${sat.BOi || ''}dB，转发器OBO ${sat.BOo || ''}dB。`
        : `Satellite Parameters: This link uses ${sat.satelliteName || ''} satellite at ${sat.orbitPosition || ''}°E, ${sat.frequencyBand || ''} band, frequency: ${r.uplinkFrequencyResult || ''}GHz (${r.uplinkPolarizationResult || ''}) / ${r.downlinkFrequencyResult || ''}GHz (${r.downlinkPolarizationResult || ''}), transponder bandwidth ${sat.transponderBandwidth || ''}MHz, satellite EIRP ${r.EIRPsResult || ''}dBW, satellite SFD ${r.SFDsResult || ''}dBW/m², input backoff ${sat.BOi || ''}dB, output backoff ${sat.BOo || ''}dB.`;
      
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: satParamsText,
              font: 'FangSong',
              size: 28
            })
          ],
          indent: { firstLine: 560 }, // 首行缩进2字符 (280 twips per char)
          spacing: { line: 240 }
        })
      );
      
      // 载波参数段落
      const carrierParamsText = lang === 'zh'
        ? `载波参数：信息速率${r.infoRateResult || ''}kbps，调制方式${r.modulationResult || ''}，FEC码率${r.fecResult || ''}，符号速率${r.symbolRateResult || ''}ksps，占用带宽${r.allocBandwidthResult || ''}kHz，功率带宽${r.PowerBWResult || ''}kHz，上行频率${r.uplinkFrequencyResult || ''}GHz，下行频率${r.downlinkFrequencyResult || ''}GHz，门限Eb/N0为${r.ebnoResult || ''}dB，门限Es/N0为${r.esnoResult || ''}dB。`
        : `Carrier Parameters: Information rate ${r.infoRateResult || ''}kbps, modulation ${r.modulationResult || ''}, FEC code ${r.fecResult || ''}, symbol rate ${r.symbolRateResult || ''}ksps, allocated bandwidth ${r.allocBandwidthResult || ''}kHz, power bandwidth ${r.PowerBWResult || ''}kHz, uplink frequency ${r.uplinkFrequencyResult || ''}GHz, downlink frequency ${r.downlinkFrequencyResult || ''}GHz, threshold Eb/N0 ${r.ebnoResult || ''}dB, threshold Es/N0 ${r.esnoResult || ''}dB.`;
      
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: carrierParamsText,
              font: 'FangSong',
              size: 28
            })
          ],
          indent: { firstLine: 560 },
          spacing: { line: 240 }
        })
      );
      
      // 上行链路段落
      const uplinkText = lang === 'zh'
        ? `上行链路：发信站位于${lp.earthStationLocation || ''}，天线口径${r.earthAntennaDiameterResult || ''}m，天线增益${r.txAntennaGainResult || ''}dB，发射功率${r.selectedPowerWResult || ''}W（${r.selectedPowerResult || ''}dBW），地面站EIRP${r.stationEIRPResult || ''}dBW，仰角${r.elevationResult || ''}°，方位角${r.azimuthResult || ''}°，自由空间损耗${r.uplinkFSLResult || ''}dB，降雨衰减${r.uplinkRainAttenuation || ''}dB，馈线损耗${r.feederLossResult || ''}dB，上行C/N为${r.uplinkCN || ''}dB。`
        : `Uplink: Transmit station at ${lp.earthStationLocation || ''}, antenna diameter ${r.earthAntennaDiameterResult || ''}m, antenna gain ${r.txAntennaGainResult || ''}dB, transmit power ${r.selectedPowerWResult || ''}W (${r.selectedPowerResult || ''}dBW), ground station EIRP ${r.stationEIRPResult || ''}dBW, elevation ${r.elevationResult || ''}°, azimuth ${r.azimuthResult || ''}°, free space loss ${r.uplinkFSLResult || ''}dB, rain attenuation ${r.uplinkRainAttenuation || ''}dB, feeder loss ${r.feederLossResult || ''}dB, uplink C/N ${r.uplinkCN || ''}dB.`;
      
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: uplinkText,
              font: 'FangSong',
              size: 28
            })
          ],
          indent: { firstLine: 560 },
          spacing: { line: 240 }
        })
      );
      
      // 下行链路段落
      const downlinkText = lang === 'zh'
        ? `下行链路：收信站位于${lp.rxEarthStationLocation || ''}，天线口径${r.rxAntennaDiameterResult || ''}m，天线增益${r.rxAntennaGainResult || ''}dB，G/T值${r.gOverTeResult || ''}dB/K，仰角${r.rxElevationResult || ''}°，方位角${r.rxAzimuthResult || ''}°，自由空间损耗${r.downlinkFSLResult || ''}dB，降雨衰减${r.downlinkRainAttenuationResult || ''}dB，馈线损耗${r.rxFeederLossResult || ''}dB，下行C/N为${r.downlinkCN || ''}dB。`
        : `Downlink: Receive station at ${lp.rxEarthStationLocation || ''}, antenna diameter ${r.rxAntennaDiameterResult || ''}m, antenna gain ${r.rxAntennaGainResult || ''}dB, G/T ${r.gOverTeResult || ''}dB/K, elevation ${r.rxElevationResult || ''}°, azimuth ${r.rxAzimuthResult || ''}°, free space loss ${r.downlinkFSLResult || ''}dB, rain attenuation ${r.downlinkRainAttenuationResult || ''}dB, feeder loss ${r.rxFeederLossResult || ''}dB, downlink C/N ${r.downlinkCN || ''}dB.`;
      
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: downlinkText,
              font: 'FangSong',
              size: 28
            })
          ],
          indent: { firstLine: 560 },
          spacing: { line: 240 }
        })
      );
      
      // 结论段落
      const availabilityWeather = parseFloat(r.systemAvailabilityResult) >= 100 ? (lang === 'zh' ? '（晴天）' : ' (Clear Sky)') : (lang === 'zh' ? '（雨天）' : ' (Rain)');
      const equivalentBWFormatted = formatBandwidth(equivalentBW);
      const conclusionText = lang === 'zh'
        ? `结论：该链路综合C/N为${r.carrierTotalCN || ''}dB，门限C/N为${r.thresholdCN || ''}dB，链路余量${linkMargin}dB，链路状态${statusText}，系统可用度${r.systemAvailabilityResult || ''}%${availabilityWeather}，带宽占用${r.bandwidthUsageRatio || ''}%，功率占用${r.powerUsageRatio || ''}%，推荐功放功率${r.paRecommendation || ''}W，等效占用带宽${equivalentBWFormatted}。`
        : `Conclusion: The link has total C/N of ${r.carrierTotalCN || ''}dB, threshold C/N ${r.thresholdCN || ''}dB, link margin ${linkMargin}dB, link status ${statusText}, system availability ${r.systemAvailabilityResult || ''}%${availabilityWeather}, bandwidth usage ${r.bandwidthUsageRatio || ''}%, power usage ${r.powerUsageRatio || ''}%, recommended PA power ${r.paRecommendation || ''}W, equivalent bandwidth ${equivalentBWFormatted}.`;
      
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: conclusionText,
              font: 'FangSong',
              size: 28
            })
          ],
          indent: { firstLine: 560 },
          spacing: { line: 240, after: 120 }
        })
      );
    }
  }
  
  // 添加总计结论
  const totalEquivalentBWFormatted = formatBandwidth(totalEquivalentBW);
  const summaryText = lang === 'zh'
    ? `本报告共包含${linkIndex}条链路，等效转发器带宽占用总计为${totalEquivalentBWFormatted}。`
    : `This report contains ${linkIndex} links with a total equivalent transponder bandwidth of ${totalEquivalentBWFormatted}.`;
  
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: summaryText,
          font: 'FangSong',
          size: 28,
          bold: true
        })
      ],
      indent: { firstLine: 560 },
      spacing: { before: 240, line: 240 }
    })
  );
  
  // 创建文档
  const doc = new Document({
    sections: [{
      properties: {},
      children: children
    }]
  });
  
  // 生成Buffer
  const buffer = await Packer.toBuffer(doc);
  return buffer;
}

// 生成 Word 参数设置文档（仅包含输入参数，不含计算结果）
// 获取配置中第一条有效链路参数
function getFirstLinkParams(config) {
  const links = config.linkParams || {};
  const nums = Object.keys(links).filter(k => typeof links[k] === 'object');
  return nums.length > 0 ? links[nums[0]] : {};
}

// 生成 Excel 参数设置文档（学术三线表风格，Times New Roman 11pt）
async function generateExcelParams(configs, lang) {
  const isZh = (lang !== 'en');
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Satellite Link Budget System';
  workbook.created = new Date();

  const sheetName = isZh ? '参数设置' : 'Parameters';
  const sheet = workbook.addWorksheet(sheetName);

  // 紧凑4列
  sheet.columns = [
    { width: 16 }, { width: 17 }, { width: 16 }, { width: 17 }
  ];

  // 值+单位格式化
  const u = (val, unit) => {
    if (val === undefined || val === null || val === '') return '--';
    return unit ? `${val} ${unit}` : String(val);
  };

  // 学术三线表配色 & 字体
  const FONT = 'Times New Roman';
  const headerFont = { bold: true, size: 11, name: FONT, color: { argb: 'FF000000' } };
  const sectionFont = { bold: true, italic: true, size: 11, name: FONT, color: { argb: 'FF000000' } };
  const labelFont = { size: 11, name: FONT, color: { argb: 'FF333333' } };
  const valFont = { size: 11, name: FONT, color: { argb: 'FF000000' } };
  const dateFont = { size: 10, name: FONT, color: { argb: 'FF666666' } };
  // 三线表边框：顶粗线、底粗线、节线细线
  const topRule = { style: 'medium', color: { argb: 'FF000000' } };
  const bottomRule = { style: 'medium', color: { argb: 'FF000000' } };
  const thinRule = { style: 'thin', color: { argb: 'FF000000' } };
  const noBorder = { style: 'none' };
  // 标题行下方：粗线
  const headerBorder = { top: topRule, bottom: thinRule, left: noBorder, right: noBorder };
  // 分节行：上下细线
  const sectionBorder = { top: thinRule, bottom: thinRule, left: noBorder, right: noBorder };
  // 普通行：无左右线
  const dataBorder = { top: noBorder, bottom: noBorder, left: noBorder, right: noBorder };
  // 最后一行：底粗线
  const lastRowBorder = { top: noBorder, bottom: bottomRule, left: noBorder, right: noBorder };

  for (const config of configs) {
    const sat = config.satelliteParams || {};
    const lp = getFirstLinkParams(config);
    const dvbLabel = lp.dvbStandard === 'DVB-S' ? 'DVB-S' : lp.dvbStandard === 'DVB-S2' ? 'DVB-S2' : lp.dvbStandard === 'DVB-S2X' ? 'DVB-S2X' : (isZh ? '自定义' : 'Custom');
    const isForward = lp.calcMode === 'forward';

    let row = 1;
    let lastDataRow = row; // 跟踪最后数据行

    // 标题行（名称 + 日期同行，顶粗线）
    sheet.mergeCells(row, 1, row, 4);
    const titleCell = sheet.getCell(row, 1);
    const configTitle = config.configName || (isZh ? '卫星链路参数设置' : 'Link Parameters');
    titleCell.value = `${configTitle}    ${new Date().toISOString().slice(0, 10)}`;
    titleCell.font = headerFont;
    titleCell.alignment = { horizontal: 'center', vertical: 'middle' };
    titleCell.border = headerBorder;
    sheet.getRow(row).height = 20;
    row++;

    // 辅助函数：添加分节标题行（斜体加粗，上下细线）
    const addSection = (title) => {
      sheet.mergeCells(row, 1, row, 4);
      const cell = sheet.getCell(row, 1);
      cell.value = title;
      cell.font = sectionFont;
      cell.border = sectionBorder;
      cell.alignment = { vertical: 'middle' };
      sheet.getRow(row).height = 18;
      row++;
    };

    // 辅助函数：添加参数行（无垂直线，纯净）
    const addParam = (label1, val1, label2, val2) => {
      const r = sheet.getRow(row);
      r.getCell(1).value = label1;
      r.getCell(1).font = labelFont;
      r.getCell(1).border = dataBorder;
      r.getCell(1).alignment = { vertical: 'middle' };
      r.getCell(2).value = val1;
      r.getCell(2).font = valFont;
      r.getCell(2).border = dataBorder;
      r.getCell(2).alignment = { vertical: 'middle' };
      if (label2 !== undefined) {
        r.getCell(3).value = label2;
        r.getCell(3).font = labelFont;
        r.getCell(3).border = dataBorder;
        r.getCell(3).alignment = { vertical: 'middle' };
        r.getCell(4).value = val2;
        r.getCell(4).font = valFont;
        r.getCell(4).border = dataBorder;
        r.getCell(4).alignment = { vertical: 'middle' };
      } else {
        sheet.mergeCells(row, 3, row, 4);
        r.getCell(3).border = dataBorder;
      }
      sheet.getRow(row).height = 17;
      lastDataRow = row;
      row++;
    };

    // 卫星参数
    addSection(isZh ? '卫星参数' : 'Satellite Parameters');
    addParam(isZh ? '卫星名称' : 'Satellite', u(sat.satelliteName), isZh ? '轨道位置' : 'Orbit', u(sat.orbitPosition, '°E'));
    addParam(isZh ? '工作频段' : 'Band', u(sat.frequencyBand), 'SFD', u(sat.sfdRef, 'dBW/m²'));
    addParam(isZh ? '转发器带宽' : 'Xpdr BW', u(sat.transponderBandwidth, 'MHz'), isZh ? '邻星离轴角' : 'Isolation', u(sat.deltaTheta, '°'));
    addParam(isZh ? '转发器IBO' : 'BOi', u(sat.BOi, 'dB'), isZh ? '转发器OBO' : 'BOo', u(sat.BOo, 'dB'));

    // 干扰因子
    addSection(isZh ? '干扰因子' : 'Interference Factors');
    addParam(isZh ? '上行C/ACI' : 'UL C/ACI', u(sat.aciUplinkFactor, 'dB'), isZh ? '上行C/ASI' : 'UL C/ASI', u(sat.adjUplinkFactor, 'dB'));
    addParam(isZh ? '上行C/XPI' : 'UL C/XPI', u(sat.xpolUplinkFactor, 'dB'), 'HPA C/IM', u(sat.hpaIntermodFactor, 'dB'));
    addParam(isZh ? '下行C/ACI' : 'DL C/ACI', u(sat.aciDownlinkFactor, 'dB'), isZh ? '下行C/ASI' : 'DL C/ASI', u(sat.adjDownlinkFactor, 'dB'));
    addParam(isZh ? '下行C/XPI' : 'DL C/XPI', u(sat.xpolDownlinkFactor, 'dB'), 'Xpdr C/IM', u(sat.xpdrIntermodFactor, 'dB'));

    // 上行站参数
    addSection(isZh ? '上行站参数' : 'Uplink Station');
    addParam(isZh ? '地面站位置' : 'Station', u(lp.earthStationLocation), isZh ? '极化方式' : 'Polarization', u(lp.uplinkPolarization));
    addParam(isZh ? '天线口径' : 'Antenna Dia.', u(lp.antennaDiameter, 'm'), isZh ? '天线效率' : 'Efficiency', u(lp.antennaEfficiency, '%'));
    addParam(isZh ? '经度' : 'Longitude', u(lp.longitude, '°E'), isZh ? '纬度' : 'Latitude', u(lp.latitude, '°N'));
    addParam(isZh ? '上行频率' : 'UL Freq.', u(lp.centerFrequency, 'GHz'), isZh ? '卫星G/T' : 'Sat. G/T', u(lp.G_Ts, 'dB/K'));
    addParam(isZh ? '海拔' : 'Altitude', u(lp.altitude, 'm'), isZh ? '降雨率' : 'Rain Rate', u(lp.rainRate, 'mm/h'));
    addParam(isZh ? '功放回退' : 'PA Backoff', u(lp.paBackoff, 'dB'), isZh ? '馈线损耗' : 'Feeder Loss', u(lp.feederLoss, 'dB'));
    addParam('UPC', lp.uplinkPowerControl === '自定义' ? (isZh ? '自定义 ' + u(lp.upcValue, 'dB') : 'Custom ' + u(lp.upcValue, 'dB')) : u(lp.uplinkPowerControl), isZh ? '可用度' : 'Availability', u(lp.uplinkAvailability, '%'));

    // 接收站参数
    addSection(isZh ? '接收站参数' : 'Downlink Station');
    addParam(isZh ? '地面站位置' : 'Station', u(lp.rxEarthStationLocation), isZh ? '极化方式' : 'Polarization', u(lp.downlinkPolarization));
    addParam(isZh ? '天线口径' : 'Antenna Dia.', u(lp.rxAntennaDiameter, 'm'), isZh ? '天线效率' : 'Efficiency', u(lp.rxAntennaEfficiency, '%'));
    addParam(isZh ? '经度' : 'Longitude', u(lp.rxLongitude, '°E'), isZh ? '纬度' : 'Latitude', u(lp.rxLatitude, '°N'));
    addParam(isZh ? '下行频率' : 'DL Freq.', u(lp.rxCenterFrequency, 'GHz'), isZh ? '卫星EIRP' : 'Sat. EIRP', u(lp.rxEIRP, 'dBW'));
    addParam(isZh ? '海拔' : 'Altitude', u(lp.rxAltitude, 'm'), isZh ? '降雨率' : 'Rain Rate', u(lp.rxRainRate, 'mm/h'));
    addParam(isZh ? '天线噪温' : 'Ant. Noise T', u(lp.rxAntennaNoiseTemp, 'K'), isZh ? '接收机噪温' : 'Rx Noise T', u(lp.rxReceiverNoiseTemp, 'K'));
    addParam(isZh ? '馈线损耗' : 'Feeder Loss', u(lp.rxFeederLoss, 'dB'), isZh ? '可用度' : 'Availability', u(lp.rxDownlinkAvailability, '%'));

    // 载波参数
    addSection(isZh ? '载波参数' : 'Carrier Parameters');
    addParam(isZh ? '标准' : 'DVB Std', dvbLabel, isZh ? '调制方式' : 'Modulation', u(lp.modulation));
    addParam(isZh ? '信息速率' : 'Info Rate', u(lp.infoRate, 'kbps'), isZh ? 'FEC码率' : 'FEC Rate', u(lp.fec));
    addParam(isZh ? '帧效率' : 'Frame Eff.', u(lp.rsCode), isZh ? '滚降系数' : 'Roll-off (1+α)', u(lp.bandwidthFactor));
    const noiseMode = config.noiseRatioMode || 'ebno';
    const noiseLabel = noiseMode === 'esno' ? 'Es/N0' : 'Eb/N0';
    addParam(isZh ? '误码率' : 'BER', '1E-' + u(lp.ber), noiseLabel, u(lp.ebno, 'dB'));
    const lastLabel = isForward ? (isZh ? '功放功率' : 'PA Power') : (isZh ? '余量' : 'Margin');
    const lastVal = isForward ? u(lp.inputPaPower, 'W') : u(lp.margin, 'dB');
    addParam(lastLabel, lastVal);

    // 给最后数据行加底粗线
    for (let c = 1; c <= 4; c++) {
      sheet.getCell(lastDataRow, c).border = lastRowBorder;
    }
  }

  // Sheet2: 计算结果（与多选导出 Excel 内容一致，4列三线表）
  _writeResultsToSheet(workbook, isZh ? '计算结果' : 'Results', configs, lang, false);

  const buffer = await workbook.xlsx.writeBuffer();
  return buffer;
}

// 生成 PDF 参数设置文档（学术三线表风格，紧凑专业）
async function generatePdfParams(configs, lang) {
  const isZh = (lang !== 'en');

  // 加载字体
  const chineseFontPath = path.join(__dirname, 'fonts', 'NotoSansSC-Regular.ttf');
  const hasChinese = fs.existsSync(chineseFontPath);

  return new Promise((resolve, reject) => {
    const chunks = [];
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 28, bottom: 28, left: 32, right: 32 },
      info: { Title: isZh ? '参数设置' : 'Link Parameters', Author: 'LinkLab Satellite Analysis' }
    });

    if (hasChinese) {
      doc.registerFont('Chinese', chineseFontPath);
    }
    // Times New Roman 系列 — PDFKit 内置 Times-Roman / Times-Bold
    const font = (size) => { doc.font(hasChinese ? 'Chinese' : 'Times-Roman').fontSize(size); return doc; };
    const fontBold = (size) => { doc.font(hasChinese ? 'Chinese' : 'Times-Bold').fontSize(size); return doc; };
    const fontItalic = (size) => { doc.font(hasChinese ? 'Chinese' : 'Times-Italic').fontSize(size); return doc; };

    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // 学术配色（极简黑白灰）
    const C = {
      black: '#000000',
      text: '#1a1a1a',
      label: '#333333',
      gray: '#666666',
      light: '#999999',
      rule: '#000000'
    };

    const W = 531;  // A4-32*2 边距
    const L = 32;
    const u = (val, unit) => {
      if (val === undefined || val === null || val === '') return '--';
      return unit ? `${val} ${unit}` : String(val);
    };

    let page = 0;

    for (const config of configs) {
      const sat = config.satelliteParams || {};
      const lp = getFirstLinkParams(config);
      const dvbLabel = lp.dvbStandard === 'DVB-S' ? 'DVB-S' : lp.dvbStandard === 'DVB-S2' ? 'DVB-S2' : lp.dvbStandard === 'DVB-S2X' ? 'DVB-S2X' : (isZh ? '自定义' : 'Custom');
      const isForward = lp.calcMode === 'forward';

      if (page > 0) doc.addPage();
      page++;

      let y = 26;

      // === 顶粗线 ===
      doc.lineWidth(1.5).moveTo(L, y).lineTo(L + W, y).stroke(C.rule);
      y += 4;

      // 标题行（名称 + 日期同行）
      const configTitle = config.configName || (isZh ? '卫星链路参数设置' : 'Link Parameters');
      fontBold(11).fillColor(C.black).text(configTitle, L + 2, y, { width: W * 0.7, continued: false });
      font(9).fillColor(C.gray).text(new Date().toISOString().slice(0, 10), L + W * 0.7, y + 1, { width: W * 0.3, align: 'right' });
      y += 16;

      // 标题下细线
      doc.lineWidth(0.5).moveTo(L, y).lineTo(L + W, y).stroke(C.rule);
      y += 3;

      // 紧凑列宽（比例：0.19 / 0.31 / 0.19 / 0.31）
      const colW = [W * 0.19, W * 0.31, W * 0.19, W * 0.31];
      const rowH = 13;

      // 绘制分节标题（斜体加粗，上下细线）
      const drawSection = (title) => {
        if (y + rowH + 6 > 790) { doc.addPage(); y = 28; doc.lineWidth(1.5).moveTo(L, y).lineTo(L + W, y).stroke(C.rule); y += 4; }
        y += 2;
        doc.lineWidth(0.5).moveTo(L, y).lineTo(L + W, y).stroke(C.rule);
        y += 2;
        fontBold(8).fillColor(C.black).text(title, L + 2, y, { width: W });
        y += 12;
        doc.lineWidth(0.3).moveTo(L, y).lineTo(L + W, y).stroke(C.rule);
        y += 2;
      };

      // 绘制参数行（无垂直线，纯净三线表内容区）
      const drawParam = (label1, val1, label2, val2) => {
        if (y + rowH > 790) { doc.addPage(); y = 28; doc.lineWidth(1.5).moveTo(L, y).lineTo(L + W, y).stroke(C.rule); y += 4; }
        let x = L;
        // 标签1
        font(7).fillColor(C.label).text(label1, x + 2, y + 2, { width: colW[0] - 4 });
        x += colW[0];
        // 值1
        font(7).fillColor(C.text).text(val1, x + 2, y + 2, { width: colW[1] - 4 });
        x += colW[1];
        if (label2 !== undefined) {
          // 标签2
          font(7).fillColor(C.label).text(label2, x + 2, y + 2, { width: colW[2] - 4 });
          x += colW[2];
          // 值2
          font(7).fillColor(C.text).text(val2 || '--', x + 2, y + 2, { width: colW[3] - 4 });
        }
        y += rowH;
      };

      // 卫星参数
      drawSection(isZh ? '卫星参数' : 'Satellite Parameters');
      drawParam(isZh ? '卫星名称' : 'Satellite', u(sat.satelliteName), isZh ? '轨道位置' : 'Orbit', u(sat.orbitPosition, '°E'));
      drawParam(isZh ? '工作频段' : 'Band', u(sat.frequencyBand), 'SFD', u(sat.sfdRef, 'dBW/m²'));
      drawParam(isZh ? '转发器带宽' : 'Xpdr BW', u(sat.transponderBandwidth, 'MHz'), isZh ? '邻星离轴角' : 'Isolation', u(sat.deltaTheta, '°'));
      drawParam(isZh ? '转发器IBO' : 'BOi', u(sat.BOi, 'dB'), isZh ? '转发器OBO' : 'BOo', u(sat.BOo, 'dB'));

      // 干扰因子
      drawSection(isZh ? '干扰因子' : 'Interference Factors');
      drawParam(isZh ? '上行C/ACI' : 'UL C/ACI', u(sat.aciUplinkFactor, 'dB'), isZh ? '上行C/ASI' : 'UL C/ASI', u(sat.adjUplinkFactor, 'dB'));
      drawParam(isZh ? '上行C/XPI' : 'UL C/XPI', u(sat.xpolUplinkFactor, 'dB'), 'HPA C/IM', u(sat.hpaIntermodFactor, 'dB'));
      drawParam(isZh ? '下行C/ACI' : 'DL C/ACI', u(sat.aciDownlinkFactor, 'dB'), isZh ? '下行C/ASI' : 'DL C/ASI', u(sat.adjDownlinkFactor, 'dB'));
      drawParam(isZh ? '下行C/XPI' : 'DL C/XPI', u(sat.xpolDownlinkFactor, 'dB'), 'Xpdr C/IM', u(sat.xpdrIntermodFactor, 'dB'));

      // 上行站参数
      drawSection(isZh ? '上行站参数' : 'Uplink Station');
      drawParam(isZh ? '地面站位置' : 'Station', u(lp.earthStationLocation), isZh ? '极化方式' : 'Polarization', u(lp.uplinkPolarization));
      drawParam(isZh ? '天线口径' : 'Antenna Dia.', u(lp.antennaDiameter, 'm'), isZh ? '天线效率' : 'Efficiency', u(lp.antennaEfficiency, '%'));
      drawParam(isZh ? '经度' : 'Longitude', u(lp.longitude, '°E'), isZh ? '纬度' : 'Latitude', u(lp.latitude, '°N'));
      drawParam(isZh ? '上行频率' : 'UL Freq.', u(lp.centerFrequency, 'GHz'), isZh ? '卫星G/T' : 'Sat. G/T', u(lp.G_Ts, 'dB/K'));
      drawParam(isZh ? '海拔' : 'Altitude', u(lp.altitude, 'm'), isZh ? '降雨率' : 'Rain Rate', u(lp.rainRate, 'mm/h'));
      drawParam(isZh ? '功放回退' : 'PA Backoff', u(lp.paBackoff, 'dB'), isZh ? '馈线损耗' : 'Feeder Loss', u(lp.feederLoss, 'dB'));
      drawParam('UPC', lp.uplinkPowerControl === '自定义' ? (isZh ? '自定义 ' + u(lp.upcValue, 'dB') : 'Custom ' + u(lp.upcValue, 'dB')) : u(lp.uplinkPowerControl), isZh ? '可用度' : 'Availability', u(lp.uplinkAvailability, '%'));

      // 接收站参数
      drawSection(isZh ? '接收站参数' : 'Downlink Station');
      drawParam(isZh ? '地面站位置' : 'Station', u(lp.rxEarthStationLocation), isZh ? '极化方式' : 'Polarization', u(lp.downlinkPolarization));
      drawParam(isZh ? '天线口径' : 'Antenna Dia.', u(lp.rxAntennaDiameter, 'm'), isZh ? '天线效率' : 'Efficiency', u(lp.rxAntennaEfficiency, '%'));
      drawParam(isZh ? '经度' : 'Longitude', u(lp.rxLongitude, '°E'), isZh ? '纬度' : 'Latitude', u(lp.rxLatitude, '°N'));
      drawParam(isZh ? '下行频率' : 'DL Freq.', u(lp.rxCenterFrequency, 'GHz'), isZh ? '卫星EIRP' : 'Sat. EIRP', u(lp.rxEIRP, 'dBW'));
      drawParam(isZh ? '海拔' : 'Altitude', u(lp.rxAltitude, 'm'), isZh ? '降雨率' : 'Rain Rate', u(lp.rxRainRate, 'mm/h'));
      drawParam(isZh ? '天线噪温' : 'Ant. Noise T', u(lp.rxAntennaNoiseTemp, 'K'), isZh ? '接收机噪温' : 'Rx Noise T', u(lp.rxReceiverNoiseTemp, 'K'));
      drawParam(isZh ? '馈线损耗' : 'Feeder Loss', u(lp.rxFeederLoss, 'dB'), isZh ? '可用度' : 'Availability', u(lp.rxDownlinkAvailability, '%'));

      // 载波参数
      drawSection(isZh ? '载波参数' : 'Carrier Parameters');
      drawParam(isZh ? '标准' : 'DVB Std', dvbLabel, isZh ? '调制方式' : 'Modulation', u(lp.modulation));
      drawParam(isZh ? '信息速率' : 'Info Rate', u(lp.infoRate, 'kbps'), isZh ? 'FEC码率' : 'FEC Rate', u(lp.fec));
      drawParam(isZh ? '帧效率' : 'Frame Eff.', u(lp.rsCode), isZh ? '滚降系数' : 'Roll-off (1+α)', u(lp.bandwidthFactor));
      const noiseMode = config.noiseRatioMode || 'ebno';
      const noiseLabel = noiseMode === 'esno' ? 'Es/N0' : 'Eb/N0';
      drawParam(isZh ? '误码率' : 'BER', '1E-' + u(lp.ber), noiseLabel, u(lp.ebno, 'dB'));
      const lastLabel = isForward ? (isZh ? '功放功率' : 'PA Power') : (isZh ? '余量' : 'Margin');
      const lastVal = isForward ? u(lp.inputPaPower, 'W') : u(lp.margin, 'dB');
      drawParam(lastLabel, lastVal);

      // === 底粗线 ===
      y += 2;
      doc.lineWidth(1.5).moveTo(L, y).lineTo(L + W, y).stroke(C.rule);

      // 页脚
      font(6).fillColor(C.light).text('LinkLab Satellite Analysis', L, 800, { width: W * 0.7 });
      font(6).fillColor(C.light).text(`- ${page} -`, L, 800, { width: W, align: 'right' });
    }

    doc.end();
  });
}

// 生成 Word 参数设置文档（表格样式，与主页面排版一致）
async function generateWordParams(configs, lang) {
  const isZh = (lang !== 'en');
  const children = [];
  const FONT = isZh ? 'SimSun' : 'Arial';
  const FONT_TITLE = isZh ? 'SimHei' : 'Arial';
  const SZ = 18;       // 9pt
  const SZ_SEC = 19;   // 分节标题略大
  const SZ_TITLE = 26; // 文档标题

  // 深色主题色（深蓝灰，严肃科技感）
  const C_SECTION_BG = 'D6DCE4';  // 分节行底色
  const C_LABEL_BG = 'F2F4F7';    // 标签列底色
  const C_BORDER = '8D9AAF';      // 边框色（蓝灰）
  const C_SECTION_TEXT = '1F3864'; // 分节标题文字色（深蓝）

  const cellBorders = {
    top: { style: BorderStyle.SINGLE, size: 1, color: C_BORDER },
    bottom: { style: BorderStyle.SINGLE, size: 1, color: C_BORDER },
    left: { style: BorderStyle.SINGLE, size: 1, color: C_BORDER },
    right: { style: BorderStyle.SINGLE, size: 1, color: C_BORDER },
  };

  // A4纵向: 11906 DXA, 页边距各567, 可用宽度 = 11906 - 567*2 = 10772
  const PAGE_W = 11906;
  const PAGE_M = 567;
  const TBL_W = PAGE_W - PAGE_M * 2; // 10772
  // 4列: 标签2400 + 值3000 + 标签2400 + 值2972 = 10772
  const W_LABEL = 2400;
  const W_VAL = 3000;
  const W_LABEL2 = 2400;
  const W_VAL2 = TBL_W - W_LABEL - W_VAL - W_LABEL2; // 2972

  // 标签单元格（浅灰底 + 加粗）
  function labelCell(text, w) {
    return new TableCell({
      children: [new Paragraph({
        children: [new TextRun({ text: String(text), font: FONT, size: SZ, bold: true })],
        spacing: { line: 260 },
      })],
      width: { size: w, type: WidthType.DXA },
      borders: cellBorders,
      verticalAlign: VerticalAlign.CENTER,
      shading: { type: ShadingType.SOLID, color: C_LABEL_BG, fill: C_LABEL_BG },
    });
  }

  // 值单元格（白底）
  function valCell(text, w) {
    return new TableCell({
      children: [new Paragraph({
        children: [new TextRun({ text: String(text), font: FONT, size: SZ })],
        spacing: { line: 260 },
      })],
      width: { size: w, type: WidthType.DXA },
      borders: cellBorders,
      verticalAlign: VerticalAlign.CENTER,
    });
  }

  // 分节标题行（深蓝灰底 + 深蓝字）
  function sectionRow(text, cols) {
    return new TableRow({
      children: [
        new TableCell({
          children: [new Paragraph({
            children: [new TextRun({ text, font: FONT_TITLE, size: SZ_SEC, bold: true, color: C_SECTION_TEXT })],
            spacing: { line: 260 },
          })],
          columnSpan: cols,
          borders: cellBorders,
          verticalAlign: VerticalAlign.CENTER,
          shading: { type: ShadingType.SOLID, color: C_SECTION_BG, fill: C_SECTION_BG },
        }),
      ]
    });
  }

  // 参数行（4列固定DXA宽度）
  function paramRow(label1, val1, label2, val2) {
    const cells = [
      labelCell(label1, W_LABEL),
      valCell(val1, W_VAL),
    ];
    if (label2 !== undefined) {
      cells.push(labelCell(label2, W_LABEL2));
      cells.push(valCell(val2, W_VAL2));
    } else {
      cells.push(new TableCell({
        children: [new Paragraph({ children: [], spacing: { line: 260 } })],
        columnSpan: 2,
        width: { size: W_LABEL2 + W_VAL2, type: WidthType.DXA },
        borders: cellBorders,
      }));
    }
    return new TableRow({ children: cells });
  }

  const v = (val) => (val !== undefined && val !== null && val !== '') ? String(val) : '--';

  for (const config of configs) {
    const sat = config.satelliteParams || {};
    const lp = getFirstLinkParams(config);
    const dvbLabel = lp.dvbStandard === 'DVB-S' ? 'DVB-S' : lp.dvbStandard === 'DVB-S2' ? 'DVB-S2' : lp.dvbStandard === 'DVB-S2X' ? 'DVB-S2X' : (isZh ? '自定义' : 'Custom');
    const isForward = lp.calcMode === 'forward';

    // 文档标题
    children.push(new Paragraph({
      children: [new TextRun({ text: config.configName || (isZh ? '卫星链路参数设置' : 'Link Parameters'), font: FONT_TITLE, size: SZ_TITLE, bold: true, color: C_SECTION_TEXT })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 80, line: 276 },
    }));
    // 副标题（生成时间）
    children.push(new Paragraph({
      children: [new TextRun({ text: new Date().toISOString().slice(0, 10), font: FONT, size: 16, color: '808080' })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 160, line: 240 },
    }));

    const rows = [];
    const COL = 4;

    // 卫星参数
    rows.push(sectionRow(isZh ? '卫星参数' : 'Satellite Parameters', COL));
    rows.push(paramRow(isZh ? '卫星名称' : 'Satellite', v(sat.satelliteName), isZh ? '轨道位置(°E)' : 'Orbit(°E)', v(sat.orbitPosition)));
    rows.push(paramRow(isZh ? '工作频段' : 'Band', v(sat.frequencyBand), isZh ? 'SFD(dBW/m²)' : 'SFD(dBW/m²)', v(sat.sfdRef)));
    rows.push(paramRow(isZh ? '转发器带宽(MHz)' : 'Xpdr BW(MHz)', v(sat.transponderBandwidth), isZh ? '邻星离轴角(°)' : 'Isolation(°)', v(sat.deltaTheta)));
    rows.push(paramRow(isZh ? '转发器IBO(dB)' : 'BOi(dB)', v(sat.BOi), isZh ? '转发器OBO(dB)' : 'BOo(dB)', v(sat.BOo)));

    // 干扰因子
    rows.push(sectionRow(isZh ? '干扰因子(dB)' : 'Interference(dB)', COL));
    rows.push(paramRow(isZh ? '上行C/ACI' : 'UL C/ACI', v(sat.aciUplinkFactor), isZh ? '上行C/ASI' : 'UL C/ASI', v(sat.adjUplinkFactor)));
    rows.push(paramRow(isZh ? '上行C/XPI' : 'UL C/XPI', v(sat.xpolUplinkFactor), 'HPA C/IM', v(sat.hpaIntermodFactor)));
    rows.push(paramRow(isZh ? '下行C/ACI' : 'DL C/ACI', v(sat.aciDownlinkFactor), isZh ? '下行C/ASI' : 'DL C/ASI', v(sat.adjDownlinkFactor)));
    rows.push(paramRow(isZh ? '下行C/XPI' : 'DL C/XPI', v(sat.xpolDownlinkFactor), 'Xpdr C/IM', v(sat.xpdrIntermodFactor)));

    // 上行站参数
    rows.push(sectionRow(isZh ? '上行站参数' : 'Uplink Station', COL));
    rows.push(paramRow(isZh ? '地面站位置' : 'Station', v(lp.earthStationLocation), isZh ? '极化方式' : 'Pol', v(lp.uplinkPolarization)));
    rows.push(paramRow(isZh ? '天线口径(m)' : 'Dia(m)', v(lp.antennaDiameter), isZh ? '天线效率(%)' : 'Eff(%)', v(lp.antennaEfficiency)));
    rows.push(paramRow(isZh ? '经度(°E)' : 'Lon(°E)', v(lp.longitude), isZh ? '纬度(°N)' : 'Lat(°N)', v(lp.latitude)));
    rows.push(paramRow(isZh ? '上行频率(GHz)' : 'Freq(GHz)', v(lp.centerFrequency), isZh ? '卫星G/T(dB/K)' : 'G/T(dB/K)', v(lp.G_Ts)));
    rows.push(paramRow(isZh ? '海拔(m)' : 'Alt(m)', v(lp.altitude), isZh ? '降雨率(mm/h)' : 'Rain(mm/h)', v(lp.rainRate)));
    rows.push(paramRow(isZh ? '功放回退(dB)' : 'PA BO(dB)', v(lp.paBackoff), isZh ? '馈线损耗(dB)' : 'Feeder(dB)', v(lp.feederLoss)));
    rows.push(paramRow('UPC', lp.uplinkPowerControl === '自定义' ? (isZh ? '自定义(' + v(lp.upcValue) + 'dB)' : 'Custom(' + v(lp.upcValue) + 'dB)') : v(lp.uplinkPowerControl), isZh ? '可用度(%)' : 'Avail(%)', v(lp.uplinkAvailability)));

    // 接收站参数
    rows.push(sectionRow(isZh ? '接收站参数' : 'Downlink Station', COL));
    rows.push(paramRow(isZh ? '地面站位置' : 'Station', v(lp.rxEarthStationLocation), isZh ? '极化方式' : 'Pol', v(lp.downlinkPolarization)));
    rows.push(paramRow(isZh ? '天线口径(m)' : 'Dia(m)', v(lp.rxAntennaDiameter), isZh ? '天线效率(%)' : 'Eff(%)', v(lp.rxAntennaEfficiency)));
    rows.push(paramRow(isZh ? '经度(°E)' : 'Lon(°E)', v(lp.rxLongitude), isZh ? '纬度(°N)' : 'Lat(°N)', v(lp.rxLatitude)));
    rows.push(paramRow(isZh ? '下行频率(GHz)' : 'Freq(GHz)', v(lp.rxCenterFrequency), isZh ? '卫星EIRP(dBW)' : 'EIRP(dBW)', v(lp.rxEIRP)));
    rows.push(paramRow(isZh ? '海拔(m)' : 'Alt(m)', v(lp.rxAltitude), isZh ? '降雨率(mm/h)' : 'Rain(mm/h)', v(lp.rxRainRate)));
    rows.push(paramRow(isZh ? '天线噪温(K)' : 'AntT(K)', v(lp.rxAntennaNoiseTemp), isZh ? '接收机噪温(K)' : 'RxT(K)', v(lp.rxReceiverNoiseTemp)));
    rows.push(paramRow(isZh ? '馈线损耗(dB)' : 'Feeder(dB)', v(lp.rxFeederLoss), isZh ? '可用度(%)' : 'Avail(%)', v(lp.rxDownlinkAvailability)));

    // 载波参数
    rows.push(sectionRow(isZh ? '载波参数' : 'Carrier Parameters', COL));
    rows.push(paramRow(isZh ? '标准' : 'DVB Std', dvbLabel, isZh ? '调制方式' : 'Mod', v(lp.modulation)));
    rows.push(paramRow(isZh ? '信息速率(kbps)' : 'Rate(kbps)', v(lp.infoRate), isZh ? 'FEC码率' : 'FEC', v(lp.fec)));
    rows.push(paramRow(isZh ? '帧效率' : 'Frame Eff', v(lp.rsCode), isZh ? '滚降系数(1+α)' : '1+α', v(lp.bandwidthFactor)));
    const noiseMode = config.noiseRatioMode || 'ebno';
    const noiseLabel = noiseMode === 'esno' ? 'Es/N₀(dB)' : 'Eb/N₀(dB)';
    rows.push(paramRow(isZh ? '误码率' : 'BER', '1E-' + v(lp.ber), noiseLabel, v(lp.ebno)));
    const lastLabel = isForward ? (isZh ? '功放功率(W)' : 'PA(W)') : (isZh ? '余量(dB)' : 'Margin(dB)');
    const lastVal = isForward ? v(lp.inputPaPower) : v(lp.margin);
    rows.push(paramRow(lastLabel, lastVal));

    const table = new Table({
      rows,
      width: { size: TBL_W, type: WidthType.DXA },
      layout: TableLayoutType.FIXED,
    });

    children.push(table);
  }

  const doc = new Document({
    sections: [{
      properties: {
        page: {
          size: { width: PAGE_W, height: 16838 },
          margin: { top: PAGE_M, bottom: PAGE_M, left: PAGE_M, right: PAGE_M },
        },
      },
      children,
    }]
  });
  return await Packer.toBuffer(doc);
}

// 删除指定的云存储文件
async function deleteCloudFile(fileID) {
  if (!fileID) return false;
  try {
    await cloud.deleteFile({ fileList: [fileID] });
    return true;
  } catch (error) {
    console.log('删除文件失败:', error.message);
    return false;
  }
}

// 云函数入口函数
exports.main = async (event, context) => {
  const { configs, format, lang = 'zh', oldFileID, compareMode = false } = event;
  
  if (!configs || !Array.isArray(configs) || configs.length === 0) {
    return {
      success: false,
      error: '未提供配置数据'
    };
  }
  
  if (!['excel', 'pdf', 'word', 'word-params', 'excel-params', 'pdf-params'].includes(format)) {
    return {
      success: false,
      error: '无效的导出格式，请使用 excel、pdf、word、word-params、excel-params 或 pdf-params'
    };
  }
  
  try {
    // 如果提供了旧文件ID，先删除旧文件
    if (oldFileID) {
      await deleteCloudFile(oldFileID);
    }
    
    let buffer;
    let fileName;
    let contentType;
    
    const timestamp = formatDateTime(new Date(), 'YYYYMMDD_HHmmss');
    
    if (format === 'excel') {
      buffer = await generateExcel(configs, lang, compareMode);
      fileName = `reports/LinkBudget_${timestamp}.xlsx`;
      contentType = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
    } else if (format === 'excel-params') {
      buffer = await generateExcelParams(configs, lang);
      fileName = `reports/LinkParams_${timestamp}.xlsx`;
      contentType = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
    } else if (format === 'pdf') {
      buffer = await generatePDF(configs, lang);
      fileName = `reports/LinkBudgetReport_${timestamp}.pdf`;
      contentType = 'application/pdf';
    } else if (format === 'pdf-params') {
      buffer = await generatePdfParams(configs, lang);
      fileName = `reports/LinkParams_${timestamp}.pdf`;
      contentType = 'application/pdf';
    } else if (format === 'word-params') {
      buffer = await generateWordParams(configs, lang);
      fileName = `reports/LinkParams_${timestamp}.docx`;
      contentType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
    } else {
      buffer = await generateWord(configs, lang);
      fileName = `reports/LinkBudgetReport_${timestamp}.docx`;
      contentType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
    }
    
    // 上传到云存储
    const uploadResult = await cloud.uploadFile({
      cloudPath: fileName,
      fileContent: buffer
    });
    
    // 获取临时下载链接（有效期2小时）
    const tempUrlResult = await cloud.getTempFileURL({
      fileList: [uploadResult.fileID]
    });
    
    const tempFileURL = tempUrlResult.fileList[0].tempFileURL;
    
    return {
      success: true,
      fileID: uploadResult.fileID,
      tempFileURL: tempFileURL,
      fileName: fileName.split('/').pop(),
      format: format
    };
    
  } catch (error) {
    console.error('生成报告失败:', error);
    return {
      success: false,
      error: error.message || '生成报告失败'
    };
  }
};
