// 云函数入口文件 - 生成卫星链路预算报告（Excel/PDF/Word）
const cloud = require('wx-server-sdk');
const ExcelJS = require('exceljs');
const PDFDocument = require('pdfkit');
const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, Table, TableRow, TableCell, WidthType, BorderStyle, TableLayoutType, VerticalAlign, ShadingType } = require('docx');
const path = require('path');
const fs = require('fs');

cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV });

// 翻译文本（与报告页面完全一致）
const TRANSLATIONS = {
  zh: {
    // 标题区
    reportTitle: '卫星通信链路预算分析报告',
    institutionLine: 'LinkLab Satellite Analysis',
    frequencyBandSuffix: '频段',
    // 链路评估
    linkStatus: '链路状态',
    linkMargin: '链路余量',
    systemAvailability: '系统可用度',
    // 状态文本
    statusExcellent: '优秀',
    statusGood: '良好',
    statusQualified: '合格',
    statusPoor: '不足',
    // 系统配置
    sectionSystemConfig: 'I. 系统配置',
    infoRate: '信息速率',
    modulation: '调制方式',
    fecCode: 'FEC编码',
    symbolRate: '符号速率',
    allocBandwidth: '占用带宽',
    uplinkFreq: '上行中心频率',
    downlinkFreq: '下行中心频率',
    threshold: '门限',
    // 卫星参数
    sectionSatellite: 'II. 卫星参数',
    sfdRef: '卫星SFD',
    transponderBW: '转发器带宽',
    inputBackoff: '输入回退',
    outputBackoff: '输出回退',
    satelliteEIRP: 'EIRPs',
    satelliteSFD: '信号到星通量密度',
    satellitePSD: '卫星输出功率谱密度',
    groundPFD: '卫星到地通量密度',
    // 链路质量
    sectionLinkQuality: 'III. 链路质量',
    totalCN: '综合C/N',
    thresholdCN: '门限C/N',
    availability: '可用度',
    ber: '误码率',
    bwUsage: '带宽占用',
    pwrUsage: '功率占用',
    // 上下行链路
    sectionUplink: 'IV. 上行链路',
    sectionDownlink: 'V. 下行链路',
    antennaDiameter: '天线口径',
    antennaGain: '天线增益',
    txPower: '发射功率',
    gtValue: 'G/T值',
    stationEIRP: '地面站EIRP',
    eirpOutput: 'EIRP输出',
    polarization: '极化方式',
    elevation: '仰角',
    polarAngle: '方位角',
    fsl: '自由空间损耗',
    rainAtten: '降雨衰减',
    feederLoss: '馈线损耗',
    uplinkCN: '上行C/N',
    downlinkCN: '下行C/N',
    // 功放配置
    sectionPA: 'VI. 功放配置建议',
    recommendedPower: '推荐功率',
    carrierBW: '载波带宽',
    powerBW: '功率带宽',
    // 汇总
    summaryTitle: '汇总',
    equivalentBwTotal: '等效转发器带宽占用总计',
    linkCount: '链路数量',
    // 页脚
    footerText: '本报告由卫星链路预算计算系统自动生成',
    excelSheetName: '链路预算报告',
    // Excel 专用
    configName: '配置名称',
    satellite: '卫星',
    orbitPosition: '轨道位置',
    frequencyBand: '频段',
    parameter: '参数',
    value: '数值',
    unit: '单位'
  },
  en: {
    // 标题区
    reportTitle: 'Satellite Link Budget Analysis Report',
    institutionLine: 'LinkLab Satellite Analysis',
    frequencyBandSuffix: 'Band',
    // 链路评估
    linkStatus: 'Link Status',
    linkMargin: 'Link Margin',
    systemAvailability: 'Availability',
    // 状态文本
    statusExcellent: 'Excellent',
    statusGood: 'Good',
    statusQualified: 'Qualified',
    statusPoor: 'Poor',
    // 系统配置
    sectionSystemConfig: 'I. System Config',
    infoRate: 'Info Rate',
    modulation: 'Modulation',
    fecCode: 'FEC Code',
    symbolRate: 'Symbol Rate',
    allocBandwidth: 'Bandwidth',
    uplinkFreq: 'Uplink Freq',
    downlinkFreq: 'Downlink Freq',
    threshold: 'Threshold',
    // 卫星参数
    sectionSatellite: 'II. Satellite Params',
    sfdRef: 'Effective SFD',
    transponderBW: 'Transponder BW',
    inputBackoff: 'Input Backoff',
    outputBackoff: 'Output Backoff',
    satelliteEIRP: 'EIRPs',
    satelliteSFD: 'Flux to Satellite',
    satellitePSD: 'Sat Output PSD',
    groundPFD: 'Sat to Ground PFD',
    // 链路质量
    sectionLinkQuality: 'III. Link Quality',
    totalCN: 'Total C/N',
    thresholdCN: 'Threshold C/N',
    availability: 'Availability',
    ber: 'BER',
    bwUsage: 'BW Usage',
    pwrUsage: 'Power Usage',
    // 上下行链路
    sectionUplink: 'IV. Uplink',
    sectionDownlink: 'V. Downlink',
    antennaDiameter: 'Antenna Dia.',
    antennaGain: 'Antenna Gain',
    txPower: 'TX Power',
    gtValue: 'G/T',
    stationEIRP: 'Ground Station EIRP',
    eirpOutput: 'EIRP Output',
    polarization: 'Polarization',
    elevation: 'Elevation',
    polarAngle: 'Azimuth',
    fsl: 'Free Space Loss',
    rainAtten: 'Rain Atten.',
    feederLoss: 'Feeder Loss',
    uplinkCN: 'Uplink C/N',
    downlinkCN: 'Downlink C/N',
    // 功放配置
    sectionPA: 'VI. PA Recommendation',
    recommendedPower: 'Rec. Power',
    carrierBW: 'Carrier BW',
    powerBW: 'Power BW',
    // 汇总
    summaryTitle: 'Summary',
    equivalentBwTotal: 'Total Equivalent Transponder BW',
    linkCount: 'Link Count',
    // 页脚
    footerText: 'Generated by Satellite Link Budget System',
    excelSheetName: 'Link Budget Report',
    // Excel 专用
    configName: 'Config Name',
    satellite: 'Satellite',
    orbitPosition: 'Orbit Position',
    frequencyBand: 'Freq Band',
    parameter: 'Parameter',
    value: 'Value',
    unit: 'Unit'
  }
};

// 获取链路状态
function getLinkStatus(linkMargin) {
  try {
    const margin = parseFloat(linkMargin);
    if (margin >= 3) return 'excellent';
    if (margin >= 1) return 'good';
    if (margin >= 0) return 'qualified';
    return 'poor';
  } catch (e) {
    return 'poor';
  }
}

// 格式化日期时间
function formatDateTime(date, format) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  const hours = String(date.getHours()).padStart(2, '0');
  const minutes = String(date.getMinutes()).padStart(2, '0');
  const seconds = String(date.getSeconds()).padStart(2, '0');
  
  return format
    .replace('YYYY', year)
    .replace('MM', month)
    .replace('DD', day)
    .replace('HH', hours)
    .replace('mm', minutes)
    .replace('ss', seconds);
}

// 自适应格式化带宽（输入为kHz，自动选择合适的单位）
function formatBandwidth(bandwidthKHz) {
  const bw = parseFloat(bandwidthKHz) || 0;
  
  // 转换为MHz
  const bwMHz = bw / 1000;
  if (bwMHz >= 0.01) {
    // MHz显示（保留2位小数，至少0.01MHz）
    return `${bwMHz.toFixed(2)}MHz`;
  }
  
  // kHz显示
  if (bw >= 0.01) {
    return `${bw.toFixed(2)}kHz`;
  }
  
  // Hz显示
  const bwHz = bw * 1000;
  return `${bwHz.toFixed(2)}Hz`;
}

// 生成 Excel 报告（简洁格式：两列布局，左标题右数值+单位）
async function generateExcel(configs, lang, compareMode = false) {
  const t = TRANSLATIONS[lang] || TRANSLATIONS.zh;
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Satellite Link Budget System';
  workbook.created = new Date();
  
  const sheet = workbook.addWorksheet(t.excelSheetName.substring(0, 31));
  
  // 计算需要多少列（每个配置占2列）
  const totalConfigs = configs.reduce((sum, config) => {
    const results = config.calculationResults || {};
    return sum + Object.keys(results).length;
  }, 0);
  
  // 设置列宽（每个配置2列：标题列20，数值列25）
  const columns = [];
  for (let i = 0; i < totalConfigs; i++) {
    columns.push({ width: 20 }); // 标题列
    columns.push({ width: 25 }); // 数值+单位列
  }
  sheet.columns = columns;
  
  // 辅助函数：格式化数值+单位
  const formatValue = (value, unit) => {
    if (value === '' || value === null || value === undefined) return '';
    return unit ? `${value} ${unit}` : String(value);
  };
  
  // 准备所有配置的数据
  const allConfigsData = [];
  
  for (const config of configs) {
    const calculationResults = config.calculationResults || {};
    if (Object.keys(calculationResults).length === 0) continue;
    
    const satelliteParams = config.satelliteParams || {};
    const linkParams = config.linkParams || {};
    
    for (const linkNum of Object.keys(calculationResults)) {
      const results = calculationResults[linkNum];
      const linkParam = linkParams[linkNum] || {};
      
      // 配置名称
      const configTitle = `${config.configName || 'Unknown'} | ${satelliteParams.satelliteName || ''} | ${satelliteParams.frequencyBand || ''}${t.frequencyBandSuffix}`;
      
      // 链路状态
      const linkMargin = results.linkmargin || '0';
      const status = getLinkStatus(linkMargin);
      const statusText = t[`status${status.charAt(0).toUpperCase() + status.slice(1)}`];
      
      // 构建数据行（标题, 数值+单位）- 与报告页面完全一致
      const rows = [
        // 系统配置
        [t.sectionSystemConfig, ''],
        [t.linkStatus, statusText],
        [t.linkMargin, formatValue(linkMargin, 'dB')],
        [t.systemAvailability, formatValue(results.systemAvailabilityResult, '%') + (parseFloat(results.systemAvailabilityResult) >= 100 ? (lang === 'zh' ? '（晴天）' : ' (Clear Sky)') : (lang === 'zh' ? '（雨天）' : ' (Rain)'))],
        [t.infoRate, formatValue(results.infoRateResult, 'kbps')],
        [t.modulation, results.modulationResult || ''],
        [t.fecCode, results.fecResult || ''],
        [t.symbolRate, formatValue(results.symbolRateResult, 'ksps')],
        [t.allocBandwidth, formatValue(results.allocBandwidthResult, 'kHz')],
        [t.threshold, formatValue(results.ebnoResult, 'dB')],
        [t.uplinkFreq, formatValue(results.uplinkFrequencyResult, 'GHz')],
        [t.downlinkFreq, formatValue(results.downlinkFrequencyResult, 'GHz')],
        // 卫星参数
        [t.sectionSatellite, ''],
        [t.sfdRef, formatValue(results.SFDsResult, 'dBW/m²')],
        [t.transponderBW, formatValue(satelliteParams.transponderBandwidth, 'MHz')],
        [t.inputBackoff, formatValue(satelliteParams.BOi, 'dB')],
        [t.outputBackoff, formatValue(satelliteParams.BOo, 'dB')],
        [t.satelliteEIRP, formatValue(results.EIRPsResult, 'dBW')],
        [t.satelliteSFD, formatValue(results.PFDcResult, 'dBW/m²')],
        [t.satellitePSD, formatValue(results.satellitePSDResult, 'dBW/Hz')],
        [t.groundPFD, formatValue(results.satellitePFD, 'dBW/m²')],
        // 链路质量
        [t.sectionLinkQuality, ''],
        [t.totalCN, formatValue(results.carrierTotalCN, 'dB')],
        [t.thresholdCN, formatValue(results.thresholdCN, 'dB')],
        ['Es/N0', formatValue(results.esnoResult, 'dB')],
        [t.ber, results.berResult || ''],
        [t.bwUsage, formatValue(results.bandwidthUsageRatio, '%')],
        [t.pwrUsage, formatValue(results.powerUsageRatio, '%')],
        // 上行链路
        [`${t.sectionUplink} - ${linkParam.earthStationLocation || ''}`, ''],
        [t.antennaDiameter, formatValue(results.earthAntennaDiameterResult, 'm')],
        [t.antennaGain, formatValue(results.txAntennaGainResult, 'dB')],
        [t.txPower, `${results.selectedPowerWResult || ''} W (${results.selectedPowerResult || ''}dBW)`],
        [t.stationEIRP, formatValue(results.stationEIRPResult, 'dBW')],
        [t.polarization, results.uplinkPolarizationResult || ''],
        [t.elevation, formatValue(results.elevationResult, '°')],
        [t.polarAngle, formatValue(results.azimuthResult, '°')],
        [t.fsl, formatValue(results.uplinkFSLResult, 'dB')],
        [t.rainAtten, formatValue(results.uplinkRainAttenuation, 'dB')],
        [t.feederLoss, formatValue(results.feederLossResult, 'dB')],
        [t.uplinkCN, formatValue(results.uplinkCN, 'dB')],
        // 下行链路
        [`${t.sectionDownlink} - ${linkParam.rxEarthStationLocation || ''}`, ''],
        [t.antennaDiameter, formatValue(results.rxAntennaDiameterResult, 'm')],
        [t.antennaGain, formatValue(results.rxAntennaGainResult, 'dB')],
        [t.gtValue, formatValue(results.gOverTeResult, 'dB/K')],
        [t.eirpOutput, formatValue(results.RXeirpPerCarrierResult, 'dBW')],
        [t.polarization, results.downlinkPolarizationResult || ''],
        [t.elevation, formatValue(results.rxElevationResult, '°')],
        [t.polarAngle, formatValue(results.rxAzimuthResult, '°')],
        [t.fsl, formatValue(results.downlinkFSLResult, 'dB')],
        [t.rainAtten, formatValue(results.downlinkRainAttenuationResult, 'dB')],
        [t.feederLoss, formatValue(results.rxFeederLossResult, 'dB')],
        [t.downlinkCN, formatValue(results.downlinkCN, 'dB')],
        // 功放配置
        [t.sectionPA, ''],
        [t.recommendedPower, `${results.paRecommendation || ''} W (${results.paRecommendationdBResult || ''} dBW)`],
        [t.carrierBW, formatValue(results.allocBandwidthResult, 'kHz')],
        [t.powerBW, formatValue(results.PowerBWResult, 'kHz')]
      ];
      
      // 计算等效转发器带宽（取占用带宽和功率带宽的较大值）
      const allocBW = parseFloat(results.allocBandwidthResult) || 0;
      const powerBW = parseFloat(results.PowerBWResult) || 0;
      const equivalentBW = Math.max(allocBW, powerBW);
      
      allConfigsData.push({ configTitle, rows, equivalentBW });
    }
  }
  
  if (allConfigsData.length === 0) {
    const buffer = await workbook.xlsx.writeBuffer();
    return buffer;
  }
  
  // 计算等效转发器带宽总计
  const totalEquivalentBW = allConfigsData.reduce((sum, config) => sum + config.equivalentBW, 0);
  const linkCount = allConfigsData.length;
  
  // 第一行：配置名称（合并单元格）
  let colIndex = 1;
  for (const configData of allConfigsData) {
    sheet.mergeCells(1, colIndex, 1, colIndex + 1);
    const cell = sheet.getCell(1, colIndex);
    cell.value = configData.configTitle;
    cell.font = { bold: true };
    cell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };
    colIndex += 2;
  }
  sheet.getRow(1).height = 30;
  
  // 数据行
  const maxRows = Math.max(...allConfigsData.map(c => c.rows.length));
  
  // 对比模式下的黄色高亮填充
  const yellowFill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FFFFFF00' }
  };
  
  // 获取第一个配置的数据作为基准（对比模式）
  const baselineRows = compareMode && allConfigsData.length > 1 ? allConfigsData[0].rows : null;
  
  for (let rowIdx = 0; rowIdx < maxRows; rowIdx++) {
    const rowNum = rowIdx + 2; // 从第2行开始（第1行是配置名称）
    colIndex = 1;
    
    for (let configIdx = 0; configIdx < allConfigsData.length; configIdx++) {
      const configData = allConfigsData[configIdx];
      const rowData = configData.rows[rowIdx] || ['', ''];
      
      // 左列：标题
      const titleCell = sheet.getCell(rowNum, colIndex);
      titleCell.value = rowData[0];
      
      // 判断是否是分节标题（系统配置、卫星参数、链路质量、上行链路、下行链路、功放配置）
      const isSectionHeader = rowData[0] && (
        rowData[0] === t.sectionSystemConfig ||
        rowData[0] === t.sectionSatellite ||
        rowData[0] === t.sectionLinkQuality ||
        rowData[0] === t.sectionPA ||
        rowData[0].startsWith(t.sectionUplink.split(' ')[0]) ||
        rowData[0].startsWith(t.sectionDownlink.split(' ')[0])
      );
      
      if (isSectionHeader) {
        titleCell.font = { bold: true };
      }
      
      // 右列：数值+单位
      const valueCell = sheet.getCell(rowNum, colIndex + 1);
      valueCell.value = rowData[1];
      
      // 对比模式：非第一个配置且值与基准不同时，高亮标黄
      if (compareMode && baselineRows && configIdx > 0 && !isSectionHeader) {
        const baselineValue = (baselineRows[rowIdx] || ['', ''])[1];
        if (rowData[1] !== '' && baselineValue !== '' && rowData[1] !== baselineValue) {
          titleCell.fill = yellowFill;
          valueCell.fill = yellowFill;
        }
      }
      
      colIndex += 2;
    }
  }
  
  // 非对比模式时才添加汇总行
  if (!compareMode) {
  // 添加汇总行（等效转发器带宽占用总计）
  const summaryRowNum = maxRows + 3; // 空一行后添加汇总
  sheet.mergeCells(summaryRowNum, 1, summaryRowNum, allConfigsData.length * 2);
  const summaryCell = sheet.getCell(summaryRowNum, 1);
  // 自适应单位显示带宽
  const totalEquivalentBWFormatted = formatBandwidth(totalEquivalentBW);
  // 结论性的一句话
  const summaryText = lang === 'zh' 
    ? `本报告共包含 ${linkCount} 条链路，等效转发器带宽占用总计为 ${totalEquivalentBWFormatted}。`
    : `This report contains ${linkCount} links with a total equivalent transponder bandwidth of ${totalEquivalentBWFormatted}.`;
  summaryCell.value = summaryText;
  summaryCell.font = { bold: true, size: 11 };
  summaryCell.alignment = { horizontal: 'center', vertical: 'middle' };
  // 使用加粗边框而非背景色
  const thickBorder = { style: 'medium', color: { argb: 'FF4472C4' } };
  summaryCell.border = {
    top: thickBorder,
    bottom: thickBorder,
    left: thickBorder,
    right: thickBorder
  };
  sheet.getRow(summaryRowNum).height = 25;
  } // end if (!compareMode)
  
  // 生成 Buffer
  const buffer = await workbook.xlsx.writeBuffer();
  return buffer;
}

// 生成 PDF 报告（优化版 - 专业样式）
async function generatePDF(configs, lang) {
  const t = TRANSLATIONS[lang] || TRANSLATIONS.zh;
  
  // 加载字体
  const chineseFontPath = path.join(__dirname, 'fonts', 'NotoSansSC-Regular.ttf');
  const englishFontPath = path.join(__dirname, 'fonts', 'GoogleSansFlex-VariableFont_GRAD,ROND,opsz,slnt,wdth,wght.ttf');
  const hasChinese = fs.existsSync(chineseFontPath);
  const hasEnglish = fs.existsSync(englishFontPath);
  
  return new Promise((resolve, reject) => {
    const chunks = [];
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 40, bottom: 40, left: 45, right: 45 },
      info: { Title: t.reportTitle, Author: 'LinkLab Satellite Analysis' }
    });
    
    // 注册中文字体和英文字体
    if (hasChinese) {
      doc.registerFont('Chinese', chineseFontPath);
    }
    if (hasEnglish) {
      doc.registerFont('English', englishFontPath);
    }
    
    // 字体辅助函数
    const font = (size) => {
      doc.font(hasChinese ? 'Chinese' : 'Helvetica').fontSize(size);
      return doc;
    };
    const fontBold = (size) => {
      doc.font(hasChinese ? 'Chinese' : 'Helvetica-Bold').fontSize(size);
      return doc;
    };
    const fontEn = (size) => {
      doc.font(hasEnglish ? 'English' : 'Helvetica').fontSize(size);
      return doc;
    };
    const fontEnBold = (size) => {
      doc.font(hasEnglish ? 'English' : 'Helvetica-Bold').fontSize(size);
      return doc;
    };
    
    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    
    // 颜色
    const C = {
      primary: '#0d47a1',
      accent: '#c9a227',
      excellent: '#1b5e20',
      good: '#f57f17',
      qualified: '#e65100',
      poor: '#b71c1c',
      text: '#1a1a2e',
      gray: '#546e7a',
      light: '#90a4ae',
      bg: '#f5f5f5',
      white: '#ffffff',
      border: '#e0e0e0'
    };
    
    const W = 505; // page width
    const L = 45;  // left margin
    let page = 0;
    
    // ===== 预定义格式化函数（移到循环外部提升性能）=====
    const formatPFD = (val) => {
      if (!val) return '';
      const num = String(val).replace(/[^0-9.-]/g, '');
      return num ? `${num} dBW/m2` : val;
    };
    const formatPSD = (val) => {
      if (!val) return '';
      const num = String(val).replace(/[^0-9.-]/g, '');
      return num ? `${num} dBW/Hz` : val;
    };
    const superscriptToNormal = {
      '⁰': '0', '¹': '1', '²': '2', '³': '3', '⁴': '4',
      '⁵': '5', '⁶': '6', '⁷': '7', '⁸': '8', '⁹': '9', '⁻': '-'
    };
    const formatBER = (val) => {
      if (!val) return '';
      let str = String(val);
      for (const [sup, norm] of Object.entries(superscriptToNormal)) {
        str = str.replace(new RegExp(sup, 'g'), norm);
      }
      return str.replace(/×/g, 'x');
    };
    
    // 预先计算等效转发器带宽总计
    let totalEquivalentBW = 0;
    let totalLinkCount = 0;
    for (const config of configs) {
      const calc = config.calculationResults || {};
      for (const linkNum of Object.keys(calc)) {
        const r = calc[linkNum];
        const allocBW = parseFloat(r.allocBandwidthResult) || 0;
        const powerBW = parseFloat(r.PowerBWResult) || 0;
        totalEquivalentBW += Math.max(allocBW, powerBW);
        totalLinkCount++;
      }
    }
    const totalEquivalentBWFormatted = formatBandwidth(totalEquivalentBW);
    
    for (const config of configs) {
      const calc = config.calculationResults || {};
      if (Object.keys(calc).length === 0) continue;
      
      const sat = config.satelliteParams || {};
      const links = config.linkParams || {};
      
      for (const linkNum of Object.keys(calc)) {
        const r = calc[linkNum];
        const lp = links[linkNum] || {};
        
        if (page > 0) doc.addPage();
        page++;
        
        let y = 35;
        
        // ===== 页眉装饰 =====
        doc.rect(L, y, W, 3).fill(C.primary);
        doc.rect(L, y + 3, W * 0.25, 1).fill(C.accent);
        
        // 左上角配置名称
        const configName = config.configName || 'Configuration';
        font(8).fillColor(C.gray).text(configName, L + 5, y + 6, { width: W * 0.4 });
        
        // 右上角品牌标识
        fontEnBold(7).fillColor(C.light).text('LINKLAB', L + W - 100, y + 6, { width: 100, align: 'right' });
        
        y += 18;
        
        // ===== 标题 =====
        fontBold(20).fillColor(C.primary).text(t.reportTitle, L, y, { width: W, align: 'center' });
        y += 28;
        
        // 分隔线
        doc.rect(L + W * 0.35, y, W * 0.3, 2).fill(C.accent);
        y += 10;
        
        // 副标题
        font(10).fillColor(C.gray).text(
          `${sat.satelliteName || ''} · ${sat.orbitPosition || ''}°E · ${sat.frequencyBand || ''} ${t.frequencyBandSuffix}`,
          L, y, { width: W, align: 'center' }
        );
        y += 14;
        font(8).fillColor(C.light).text(formatDateTime(new Date(), 'YYYY-MM-DD HH:mm'), L, y, { width: W, align: 'center' });
        y += 20;
        
        // ===== 核心指标 =====
        const margin = r.linkmargin || '0';
        const status = getLinkStatus(margin);
        const statusText = t[`status${status.charAt(0).toUpperCase() + status.slice(1)}`];
        const statusColor = C[status] || C.qualified;
        
        doc.rect(L, y, W, 50).fill(C.bg);
        
        const cw = W / 3;
        // 链路状态
        font(8).fillColor(C.light).text(t.linkStatus, L + 10, y + 8, { width: cw - 20 });
        fontBold(16).fillColor(statusColor).text(statusText, L + 10, y + 24, { width: cw - 20 });
        
        // 链路余量
        doc.rect(L + cw, y, cw, 50).fill(C.primary);
        font(8).fillColor(C.white).text(t.linkMargin, L + cw + 10, y + 8, { width: cw - 20 });
        fontBold(18).fillColor(C.white).text(`${margin} dB`, L + cw + 10, y + 24, { width: cw - 20 });
        
        // 可用度
        const weatherText = parseFloat(r.systemAvailabilityResult) >= 100 ? (lang === 'zh' ? '（晴天）' : ' (Clear)') : (lang === 'zh' ? '（雨天）' : ' (Rain)');
        font(8).fillColor(C.light).text(t.systemAvailability, L + cw * 2 + 10, y + 8, { width: cw - 20 });
        fontBold(16).fillColor(C.text).text(`${r.systemAvailabilityResult || ''}%${weatherText}`, L + cw * 2 + 10, y + 24, { width: cw - 20 });
        
        y += 58;
        
        // ===== 简化的表格绘制函数 =====
        const drawTable = (x, ty, w, title, rows, color = C.primary) => {
          doc.rect(x, ty, w, 20).fill(color);
          doc.rect(x, ty + 4, 3, 12).fill(C.accent);
          fontBold(9).fillColor(C.white).text(title, x + 10, ty + 5, { width: w - 15 });
          ty += 22;
          
          rows.forEach((row, i) => {
            doc.rect(x, ty, w, 16).fill(i % 2 === 0 ? C.white : C.bg);
            font(7).fillColor(C.gray).text(row[0], x + 5, ty + 4, { width: w * 0.55 });
            font(7).fillColor(row[2] ? C.primary : C.text).text(row[1], x + w * 0.55, ty + 4, { width: w * 0.42, align: 'right' });
            ty += 16;
          });
          doc.rect(x, y + 22, w, ty - y - 22).lineWidth(0.5).stroke(C.border);
          return ty + 5;
        };
        
        // ===== 三列表格 =====
        const c3w = (W - 12) / 3;
        
        const sysRows = [
          [t.infoRate, `${r.infoRateResult || ''} kbps`],
          [t.modulation, r.modulationResult || ''],
          [t.fecCode, r.fecResult || ''],
          [t.symbolRate, `${r.symbolRateResult || ''} ksps`],
          [t.allocBandwidth, `${r.allocBandwidthResult || ''} kHz`],
          [t.uplinkFreq, `${r.uplinkFrequencyResult || ''} GHz`],
          [t.downlinkFreq, `${r.downlinkFrequencyResult || ''} GHz`],
          [t.threshold, `${r.ebnoResult || ''} dB`]
        ];
        
        const satRows = [
          [t.sfdRef, r.SFDsResult || ''],
          [t.transponderBW, `${sat.transponderBandwidth || ''} MHz`],
          [t.inputBackoff, `${sat.BOi || ''} dB`],
          [t.outputBackoff, `${sat.BOo || ''} dB`],
          [t.satelliteEIRP, `${r.EIRPsResult || ''} dBW`],
          [t.satelliteSFD, formatPFD(r.PFDcResult)],
          [t.satellitePSD, formatPSD(r.satellitePSDResult)],
          [t.groundPFD, formatPFD(r.satellitePFD)]
        ];
        
        const qualRows = [
          [t.totalCN, `${r.carrierTotalCN || ''} dB`, true],
          [t.thresholdCN, `${r.thresholdCN || ''} dB`],
          [t.linkMargin, `${r.linkmargin || ''} dB`, true],
          ['Es/N0', `${r.esnoResult || ''} dB`],
          [t.availability, `${r.systemAvailabilityResult || ''}%` + (parseFloat(r.systemAvailabilityResult) >= 100 ? (lang === 'zh' ? '（晴天）' : '(Clear)') : (lang === 'zh' ? '（雨天）' : '(Rain)'))],
          [t.ber, formatBER(r.berResult)],
          [t.bwUsage, `${r.bandwidthUsageRatio || ''}%`],
          [t.pwrUsage, `${r.powerUsageRatio || ''}%`]
        ];
        
        const y1 = drawTable(L, y, c3w, t.sectionSystemConfig, sysRows);
        const y2 = drawTable(L + c3w + 6, y, c3w, t.sectionSatellite, satRows, '#1565c0');
        const y3 = drawTable(L + c3w * 2 + 12, y, c3w, t.sectionLinkQuality, qualRows);
        y = Math.max(y1, y2, y3);
        
        // ===== 双列表格：上下行链路 =====
        const c2w = (W - 8) / 2;
        
        const upRows = [
          [t.antennaDiameter, `${r.earthAntennaDiameterResult || ''} m`],
          [t.antennaGain, `${r.txAntennaGainResult || ''} dB`],
          [t.txPower, `${r.selectedPowerWResult || ''} W`],
          [t.stationEIRP, `${r.stationEIRPResult || ''} dBW`],
          [t.polarization, r.uplinkPolarizationResult || ''],
          [t.elevation, `${r.elevationResult || ''}°`],
          [t.polarAngle, `${r.azimuthResult || ''}°`],
          [t.fsl, `${r.uplinkFSLResult || ''} dB`],
          [t.rainAtten, `${r.uplinkRainAttenuation || ''} dB`],
          [t.feederLoss, `${r.feederLossResult || ''} dB`],
          [t.uplinkCN, `${r.uplinkCN || ''} dB`, true]
        ];
        
        const downRows = [
          [t.antennaDiameter, `${r.rxAntennaDiameterResult || ''} m`],
          [t.antennaGain, `${r.rxAntennaGainResult || ''} dB`],
          [t.gtValue, `${r.gOverTeResult || ''} dB/K`],
          [t.eirpOutput, `${r.RXeirpPerCarrierResult || ''} dBW`],
          [t.polarization, r.downlinkPolarizationResult || ''],
          [t.elevation, `${r.rxElevationResult || ''}°`],
          [t.polarAngle, `${r.rxAzimuthResult || ''}°`],
          [t.fsl, `${r.downlinkFSLResult || ''} dB`],
          [t.rainAtten, `${r.downlinkRainAttenuationResult || ''} dB`],
          [t.feederLoss, `${r.rxFeederLossResult || ''} dB`],
          [t.downlinkCN, `${r.downlinkCN || ''} dB`, true]
        ];
        
        const upY = drawTable(L, y, c2w, `${t.sectionUplink} · ${lp.earthStationLocation || ''}`, upRows, '#1565c0');
        const downY = drawTable(L + c2w + 8, y, c2w, `${t.sectionDownlink} · ${lp.rxEarthStationLocation || ''}`, downRows, '#1565c0');
        y = Math.max(upY, downY);
        
        // ===== 功放配置 =====
        doc.rect(L, y, W, 42).fill(C.bg);
        doc.rect(L, y, 3, 42).fill(C.accent);
        fontBold(9).fillColor(C.primary).text(t.sectionPA, L + 12, y + 6);
        
        const pw = (W - 140) / 3;
        font(7).fillColor(C.light).text(t.recommendedPower, L + 130, y + 6);
        fontBold(11).fillColor(C.text).text(`${r.paRecommendation || ''} W`, L + 130, y + 18);
        font(7).fillColor(C.gray).text(`(${r.paRecommendationdBResult || ''} dBW)`, L + 130, y + 32);
        
        font(7).fillColor(C.light).text(t.carrierBW, L + 130 + pw, y + 6);
        fontBold(11).fillColor(C.text).text(`${r.allocBandwidthResult || ''} kHz`, L + 130 + pw, y + 18);
        
        font(7).fillColor(C.light).text(t.powerBW, L + 130 + pw * 2, y + 6);
        fontBold(11).fillColor(C.text).text(`${r.PowerBWResult || ''} kHz`, L + 130 + pw * 2, y + 18);
        
        y += 50;
        
        // ===== 页脚 =====
        doc.rect(L, 780, W, 0.5).fill(C.border);
        font(7).fillColor(C.light).text(t.footerText, L, 785, { width: W * 0.7 });
        font(7).fillColor(C.light).text(`Page ${page}`, L, 785, { width: W, align: 'right' });
        doc.rect(L, 795, W, 2).fill(C.primary);
        doc.rect(L + W * 0.75, 795, W * 0.25, 2).fill(C.accent);
      }
    }
    
    // ===== 在最后一页末尾添加汇总信息 =====
    if (totalLinkCount > 1) {
      // 获取当前页面的y位置（功放配置后，页脚前）
      // 在页脚上方添加汇总信息
      const summaryY = 745; // 页脚上方位置
      
      const summaryText = lang === 'zh' 
        ? `本报告共包含 ${totalLinkCount} 条链路，等效转发器带宽占用总计为 ${totalEquivalentBWFormatted}。`
        : `This report contains ${totalLinkCount} links with a total equivalent transponder bandwidth of ${totalEquivalentBWFormatted}.`;
      
      // 绘制汇总框
      doc.rect(L, summaryY, W, 28).fill(C.bg);
      doc.rect(L, summaryY, 3, 28).fill(C.accent);
      fontBold(10).fillColor(C.text).text(summaryText, L + 10, summaryY + 8, { width: W - 20, align: 'center' });
    }
    
    doc.end();
  });
}

// 生成 Word 报告（仿宋四号字，单倍行距，首行缩进）
async function generateWord(configs, lang) {
  const t = TRANSLATIONS[lang] || TRANSLATIONS.zh;
  
  // 计算等效转发器带宽总计
  let totalEquivalentBW = 0;
  let linkIndex = 0;
  
  const children = [];
  
  for (const config of configs) {
    const calc = config.calculationResults || {};
    if (Object.keys(calc).length === 0) continue;
    
    const sat = config.satelliteParams || {};
    const links = config.linkParams || {};
    
    for (const linkNum of Object.keys(calc)) {
      const r = calc[linkNum];
      const lp = links[linkNum] || {};
      linkIndex++;
      
      // 计算等效带宽
      const allocBW = parseFloat(r.allocBandwidthResult) || 0;
      const powerBW = parseFloat(r.PowerBWResult) || 0;
      const equivalentBW = Math.max(allocBW, powerBW);
      totalEquivalentBW += equivalentBW;
      
      // 链路状态
      const linkMargin = r.linkmargin || '0';
      const status = getLinkStatus(linkMargin);
      const statusText = t[`status${status.charAt(0).toUpperCase() + status.slice(1)}`];
      
      // 链路标题
      const linkTitle = lang === 'zh' 
        ? `链路${linkIndex}：${config.configName || '未命名配置'}`
        : `Link ${linkIndex}: ${config.configName || 'Unnamed Config'}`;
      
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: linkTitle,
              font: 'FangSong',
              size: 28, // 四号字 = 14pt = 28 half-points
              bold: true
            })
          ],
          spacing: { before: 240, after: 120, line: 240 } // 单倍行距
        })
      );
      
      // 卫星参数段落
      const satParamsText = lang === 'zh'
        ? `卫星参数：本链路使用${sat.satelliteName || ''}卫星，轨道位置${sat.orbitPosition || ''}°E，${sat.frequencyBand || ''}频段，频率：${r.uplinkFrequencyResult || ''}GHz（${r.uplinkPolarizationResult || ''}）/${r.downlinkFrequencyResult || ''}GHz（${r.downlinkPolarizationResult || ''}），转发器带宽${sat.transponderBandwidth || ''}MHz，卫星EIRP为${r.EIRPsResult || ''}dBW，卫星SFD为${r.SFDsResult || ''}dBW/m²，输入回退${sat.BOi || ''}dB，输出回退${sat.BOo || ''}dB。`
        : `Satellite Parameters: This link uses ${sat.satelliteName || ''} satellite at ${sat.orbitPosition || ''}°E, ${sat.frequencyBand || ''} band, frequency: ${r.uplinkFrequencyResult || ''}GHz (${r.uplinkPolarizationResult || ''}) / ${r.downlinkFrequencyResult || ''}GHz (${r.downlinkPolarizationResult || ''}), transponder bandwidth ${sat.transponderBandwidth || ''}MHz, satellite EIRP ${r.EIRPsResult || ''}dBW, satellite SFD ${r.SFDsResult || ''}dBW/m², input backoff ${sat.BOi || ''}dB, output backoff ${sat.BOo || ''}dB.`;
      
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: satParamsText,
              font: 'FangSong',
              size: 28
            })
          ],
          indent: { firstLine: 560 }, // 首行缩进2字符 (280 twips per char)
          spacing: { line: 240 }
        })
      );
      
      // 载波参数段落
      const carrierParamsText = lang === 'zh'
        ? `载波参数：信息速率${r.infoRateResult || ''}kbps，调制方式${r.modulationResult || ''}，FEC编码${r.fecResult || ''}，符号速率${r.symbolRateResult || ''}ksps，占用带宽${r.allocBandwidthResult || ''}kHz，功率带宽${r.PowerBWResult || ''}kHz，上行中心频率${r.uplinkFrequencyResult || ''}GHz，下行中心频率${r.downlinkFrequencyResult || ''}GHz，门限Eb/N0为${r.ebnoResult || ''}dB，门限Es/N0为${r.esnoResult || ''}dB。`
        : `Carrier Parameters: Information rate ${r.infoRateResult || ''}kbps, modulation ${r.modulationResult || ''}, FEC code ${r.fecResult || ''}, symbol rate ${r.symbolRateResult || ''}ksps, allocated bandwidth ${r.allocBandwidthResult || ''}kHz, power bandwidth ${r.PowerBWResult || ''}kHz, uplink frequency ${r.uplinkFrequencyResult || ''}GHz, downlink frequency ${r.downlinkFrequencyResult || ''}GHz, threshold Eb/N0 ${r.ebnoResult || ''}dB, threshold Es/N0 ${r.esnoResult || ''}dB.`;
      
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: carrierParamsText,
              font: 'FangSong',
              size: 28
            })
          ],
          indent: { firstLine: 560 },
          spacing: { line: 240 }
        })
      );
      
      // 上行链路段落
      const uplinkText = lang === 'zh'
        ? `上行链路：发信站位于${lp.earthStationLocation || ''}，天线口径${r.earthAntennaDiameterResult || ''}m，天线增益${r.txAntennaGainResult || ''}dB，发射功率${r.selectedPowerWResult || ''}W（${r.selectedPowerResult || ''}dBW），地面站EIRP${r.stationEIRPResult || ''}dBW，仰角${r.elevationResult || ''}°，方位角${r.azimuthResult || ''}°，自由空间损耗${r.uplinkFSLResult || ''}dB，降雨衰减${r.uplinkRainAttenuation || ''}dB，馈线损耗${r.feederLossResult || ''}dB，上行C/N为${r.uplinkCN || ''}dB。`
        : `Uplink: Transmit station at ${lp.earthStationLocation || ''}, antenna diameter ${r.earthAntennaDiameterResult || ''}m, antenna gain ${r.txAntennaGainResult || ''}dB, transmit power ${r.selectedPowerWResult || ''}W (${r.selectedPowerResult || ''}dBW), ground station EIRP ${r.stationEIRPResult || ''}dBW, elevation ${r.elevationResult || ''}°, azimuth ${r.azimuthResult || ''}°, free space loss ${r.uplinkFSLResult || ''}dB, rain attenuation ${r.uplinkRainAttenuation || ''}dB, feeder loss ${r.feederLossResult || ''}dB, uplink C/N ${r.uplinkCN || ''}dB.`;
      
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: uplinkText,
              font: 'FangSong',
              size: 28
            })
          ],
          indent: { firstLine: 560 },
          spacing: { line: 240 }
        })
      );
      
      // 下行链路段落
      const downlinkText = lang === 'zh'
        ? `下行链路：收信站位于${lp.rxEarthStationLocation || ''}，天线口径${r.rxAntennaDiameterResult || ''}m，天线增益${r.rxAntennaGainResult || ''}dB，G/T值${r.gOverTeResult || ''}dB/K，仰角${r.rxElevationResult || ''}°，方位角${r.rxAzimuthResult || ''}°，自由空间损耗${r.downlinkFSLResult || ''}dB，降雨衰减${r.downlinkRainAttenuationResult || ''}dB，馈线损耗${r.rxFeederLossResult || ''}dB，下行C/N为${r.downlinkCN || ''}dB。`
        : `Downlink: Receive station at ${lp.rxEarthStationLocation || ''}, antenna diameter ${r.rxAntennaDiameterResult || ''}m, antenna gain ${r.rxAntennaGainResult || ''}dB, G/T ${r.gOverTeResult || ''}dB/K, elevation ${r.rxElevationResult || ''}°, azimuth ${r.rxAzimuthResult || ''}°, free space loss ${r.downlinkFSLResult || ''}dB, rain attenuation ${r.downlinkRainAttenuationResult || ''}dB, feeder loss ${r.rxFeederLossResult || ''}dB, downlink C/N ${r.downlinkCN || ''}dB.`;
      
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: downlinkText,
              font: 'FangSong',
              size: 28
            })
          ],
          indent: { firstLine: 560 },
          spacing: { line: 240 }
        })
      );
      
      // 结论段落
      const availabilityWeather = parseFloat(r.systemAvailabilityResult) >= 100 ? (lang === 'zh' ? '（晴天）' : ' (Clear Sky)') : (lang === 'zh' ? '（雨天）' : ' (Rain)');
      const equivalentBWFormatted = formatBandwidth(equivalentBW);
      const conclusionText = lang === 'zh'
        ? `结论：该链路综合C/N为${r.carrierTotalCN || ''}dB，门限C/N为${r.thresholdCN || ''}dB，链路余量${linkMargin}dB，链路状态${statusText}，系统可用度${r.systemAvailabilityResult || ''}%${availabilityWeather}，带宽占用${r.bandwidthUsageRatio || ''}%，功率占用${r.powerUsageRatio || ''}%，推荐功放功率${r.paRecommendation || ''}W，等效占用带宽${equivalentBWFormatted}。`
        : `Conclusion: The link has total C/N of ${r.carrierTotalCN || ''}dB, threshold C/N ${r.thresholdCN || ''}dB, link margin ${linkMargin}dB, link status ${statusText}, system availability ${r.systemAvailabilityResult || ''}%${availabilityWeather}, bandwidth usage ${r.bandwidthUsageRatio || ''}%, power usage ${r.powerUsageRatio || ''}%, recommended PA power ${r.paRecommendation || ''}W, equivalent bandwidth ${equivalentBWFormatted}.`;
      
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: conclusionText,
              font: 'FangSong',
              size: 28
            })
          ],
          indent: { firstLine: 560 },
          spacing: { line: 240, after: 120 }
        })
      );
    }
  }
  
  // 添加总计结论
  const totalEquivalentBWFormatted = formatBandwidth(totalEquivalentBW);
  const summaryText = lang === 'zh'
    ? `本报告共包含${linkIndex}条链路，等效转发器带宽占用总计为${totalEquivalentBWFormatted}。`
    : `This report contains ${linkIndex} links with a total equivalent transponder bandwidth of ${totalEquivalentBWFormatted}.`;
  
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: summaryText,
          font: 'FangSong',
          size: 28,
          bold: true
        })
      ],
      indent: { firstLine: 560 },
      spacing: { before: 240, line: 240 }
    })
  );
  
  // 创建文档
  const doc = new Document({
    sections: [{
      properties: {},
      children: children
    }]
  });
  
  // 生成Buffer
  const buffer = await Packer.toBuffer(doc);
  return buffer;
}

// 生成 Word 参数设置文档（仅包含输入参数，不含计算结果）
// 获取配置中第一条有效链路参数
function getFirstLinkParams(config) {
  const links = config.linkParams || {};
  const nums = Object.keys(links).filter(k => typeof links[k] === 'object');
  return nums.length > 0 ? links[nums[0]] : {};
}

// 生成 Word 参数设置文档（表格样式，与主页面排版一致）
async function generateWordParams(configs, lang) {
  const isZh = (lang !== 'en');
  const children = [];
  const FONT = 'FangSong';
  const SZ = 21; // 五号字 = 10.5pt
  const SZ_TITLE = 28;

  // 统一黑色细线边框
  const cellBorders = {
    top: { style: BorderStyle.SINGLE, size: 1, color: '000000' },
    bottom: { style: BorderStyle.SINGLE, size: 1, color: '000000' },
    left: { style: BorderStyle.SINGLE, size: 1, color: '000000' },
    right: { style: BorderStyle.SINGLE, size: 1, color: '000000' },
  };

  // 普通单元格（无底色）
  function cell(text, width, opts = {}) {
    return new TableCell({
      children: [new Paragraph({
        children: [new TextRun({ text: String(text), font: FONT, size: SZ, bold: !!opts.bold })],
        spacing: { line: 240 },
        alignment: opts.center ? AlignmentType.CENTER : AlignmentType.LEFT,
      })],
      width: width ? { size: width, type: WidthType.PERCENTAGE } : undefined,
      borders: cellBorders,
      verticalAlign: VerticalAlign.CENTER,
    });
  }

  // 分节标题行（黑字加粗，无底色，合并整行）
  function sectionRow(text, cols) {
    return new TableRow({
      children: [
        new TableCell({
          children: [new Paragraph({
            children: [new TextRun({ text, font: FONT, size: SZ, bold: true })],
            spacing: { line: 240 },
          })],
          columnSpan: cols,
          borders: cellBorders,
          verticalAlign: VerticalAlign.CENTER,
        }),
      ]
    });
  }

  // 参数行（4列：参数名加粗，值普通）
  function paramRow(label1, val1, label2, val2) {
    const cells = [
      cell(label1, 22, { bold: true }),
      cell(val1, 28),
    ];
    if (label2 !== undefined) {
      cells.push(cell(label2, 22, { bold: true }));
      cells.push(cell(val2, 28));
    } else {
      cells.push(new TableCell({
        children: [new Paragraph({ children: [], spacing: { line: 240 } })],
        columnSpan: 2,
        borders: cellBorders,
      }));
    }
    return new TableRow({ children: cells });
  }

  const v = (val) => (val !== undefined && val !== null && val !== '') ? String(val) : '--';

  for (const config of configs) {
    const sat = config.satelliteParams || {};
    const lp = getFirstLinkParams(config);
    const dvbLabel = lp.dvbStandard === 'DVB-S' ? 'DVB-S' : lp.dvbStandard === 'DVB-S2' ? 'DVB-S2' : (isZh ? '自定义' : 'Custom');

    // 文档标题
    children.push(new Paragraph({
      children: [new TextRun({ text: config.configName || (isZh ? '卫星链路参数设置' : 'Link Parameters'), font: FONT, size: SZ_TITLE, bold: true })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 160, line: 240 },
    }));

    const rows = [];
    const C = 4;

    // 卫星参数
    rows.push(sectionRow(isZh ? '卫星参数' : 'Satellite Parameters', C));
    rows.push(paramRow(isZh ? '卫星名称' : 'Satellite', v(sat.satelliteName), isZh ? '轨道位置(°E)' : 'Orbit(°E)', v(sat.orbitPosition)));
    rows.push(paramRow(isZh ? '工作频段' : 'Band', v(sat.frequencyBand), isZh ? 'SFD(dBW/m²)' : 'SFD(dBW/m²)', v(sat.sfdRef)));
    rows.push(paramRow(isZh ? '转发器带宽(MHz)' : 'Xpdr BW(MHz)', v(sat.transponderBandwidth), isZh ? '邻星离轴角(°)' : 'Isolation(°)', v(sat.deltaTheta)));
    rows.push(paramRow(isZh ? '输入回退(dB)' : 'BOi(dB)', v(sat.BOi), isZh ? '输出回退(dB)' : 'BOo(dB)', v(sat.BOo)));

    // 干扰因子
    rows.push(sectionRow(isZh ? '干扰因子(dB)' : 'Interference Factors(dB)', C));
    rows.push(paramRow(isZh ? '上行C/ACI' : 'UL C/ACI', v(sat.aciUplinkFactor), isZh ? '上行C/ASI' : 'UL C/ASI', v(sat.adjUplinkFactor)));
    rows.push(paramRow(isZh ? '上行C/XPI' : 'UL C/XPI', v(sat.xpolUplinkFactor), isZh ? 'HPA C/IM' : 'HPA C/IM', v(sat.hpaIntermodFactor)));
    rows.push(paramRow(isZh ? '下行C/ACI' : 'DL C/ACI', v(sat.aciDownlinkFactor), isZh ? '下行C/ASI' : 'DL C/ASI', v(sat.adjDownlinkFactor)));
    rows.push(paramRow(isZh ? '下行C/XPI' : 'DL C/XPI', v(sat.xpolDownlinkFactor), isZh ? 'Xpdr C/IM' : 'Xpdr C/IM', v(sat.xpdrIntermodFactor)));

    // 上行站参数
    rows.push(sectionRow(isZh ? '上行站参数' : 'Uplink Station', C));
    rows.push(paramRow(isZh ? '发信站' : 'Station', v(lp.earthStationLocation), isZh ? '极化方式' : 'Polarization', v(lp.uplinkPolarization)));
    rows.push(paramRow(isZh ? '天线口径(m)' : 'Ant Dia(m)', v(lp.antennaDiameter), isZh ? '天线效率(%)' : 'Efficiency(%)', v(lp.antennaEfficiency)));
    rows.push(paramRow(isZh ? '经度(°E)' : 'Lon(°E)', v(lp.longitude), isZh ? '纬度(°N)' : 'Lat(°N)', v(lp.latitude)));
    rows.push(paramRow(isZh ? '上行频率(GHz)' : 'UL Freq(GHz)', v(lp.centerFrequency), isZh ? '卫星G/T(dB/K)' : 'G/T(dB/K)', v(lp.G_Ts)));
    rows.push(paramRow(isZh ? '海拔(m)' : 'Alt(m)', v(lp.altitude), isZh ? '降雨率(mm/h)' : 'Rain(mm/h)', v(lp.rainRate)));
    rows.push(paramRow(isZh ? '功放回退(dB)' : 'PA BO(dB)', v(lp.paBackoff), isZh ? '馈线损耗(dB)' : 'Feeder(dB)', v(lp.feederLoss)));
    rows.push(paramRow(isZh ? 'UPC' : 'UPC', v(lp.uplinkPowerControl), isZh ? '可用度(%)' : 'Avail(%)', v(lp.uplinkAvailability)));

    // 接收站参数
    rows.push(sectionRow(isZh ? '接收站参数' : 'Downlink Station', C));
    rows.push(paramRow(isZh ? '收信站' : 'Station', v(lp.rxEarthStationLocation), isZh ? '极化方式' : 'Polarization', v(lp.downlinkPolarization)));
    rows.push(paramRow(isZh ? '天线口径(m)' : 'Ant Dia(m)', v(lp.rxAntennaDiameter), isZh ? '天线效率(%)' : 'Efficiency(%)', v(lp.rxAntennaEfficiency)));
    rows.push(paramRow(isZh ? '经度(°E)' : 'Lon(°E)', v(lp.rxLongitude), isZh ? '纬度(°N)' : 'Lat(°N)', v(lp.rxLatitude)));
    rows.push(paramRow(isZh ? '下行频率(GHz)' : 'DL Freq(GHz)', v(lp.rxCenterFrequency), isZh ? '卫星EIRP(dBW)' : 'EIRP(dBW)', v(lp.rxEIRP)));
    rows.push(paramRow(isZh ? '海拔(m)' : 'Alt(m)', v(lp.rxAltitude), isZh ? '降雨率(mm/h)' : 'Rain(mm/h)', v(lp.rxRainRate)));
    rows.push(paramRow(isZh ? '天线噪温(K)' : 'Ant Temp(K)', v(lp.rxAntennaNoiseTemp), isZh ? '接收机噪温(K)' : 'Rx Temp(K)', v(lp.rxReceiverNoiseTemp)));
    rows.push(paramRow(isZh ? '馈线损耗(dB)' : 'Feeder(dB)', v(lp.rxFeederLoss), isZh ? '可用度(%)' : 'Avail(%)', v(lp.rxDownlinkAvailability)));

    // 载波参数
    rows.push(sectionRow(isZh ? '载波参数' : 'Carrier Parameters', C));
    rows.push(paramRow(isZh ? 'DVB标准' : 'DVB Std', dvbLabel, isZh ? '调制方式' : 'Modulation', v(lp.modulation)));
    rows.push(paramRow(isZh ? '信息速率(kbps)' : 'Info Rate(kbps)', v(lp.infoRate), isZh ? 'FEC编码' : 'FEC', v(lp.fec)));
    rows.push(paramRow(isZh ? 'RS编码' : 'RS Code', v(lp.rsCode), isZh ? '滚降系数(1+α)' : 'Roll-off(1+α)', v(lp.bandwidthFactor)));
    rows.push(paramRow(isZh ? '误码率(1×10⁻ⁿ)' : 'BER(1E-n)', v(lp.ber), isZh ? 'Eb/N₀门限(dB)' : 'Eb/N₀(dB)', v(lp.ebno)));
    const isForward = lp.calcMode === 'forward';
    const lastLabel = isForward ? (isZh ? '功放功率(W)' : 'PA Power(W)') : (isZh ? '链路余量(dB)' : 'Margin(dB)');
    const lastVal = isForward ? v(lp.inputPaPower) : v(lp.margin);
    rows.push(paramRow(lastLabel, lastVal));

    const table = new Table({
      rows,
      width: { size: 100, type: WidthType.PERCENTAGE },
      layout: TableLayoutType.FIXED,
    });

    children.push(table);
  }

  const doc = new Document({
    sections: [{ properties: {}, children }]
  });
  return await Packer.toBuffer(doc);
}

// 删除指定的云存储文件
async function deleteCloudFile(fileID) {
  if (!fileID) return false;
  try {
    await cloud.deleteFile({ fileList: [fileID] });
    return true;
  } catch (error) {
    console.log('删除文件失败:', error.message);
    return false;
  }
}

// 云函数入口函数
exports.main = async (event, context) => {
  const { configs, format, lang = 'zh', oldFileID, compareMode = false } = event;
  
  if (!configs || !Array.isArray(configs) || configs.length === 0) {
    return {
      success: false,
      error: '未提供配置数据'
    };
  }
  
  if (!['excel', 'pdf', 'word', 'word-params'].includes(format)) {
    return {
      success: false,
      error: '无效的导出格式，请使用 excel、pdf、word 或 word-params'
    };
  }
  
  try {
    // 如果提供了旧文件ID，先删除旧文件
    if (oldFileID) {
      await deleteCloudFile(oldFileID);
    }
    
    let buffer;
    let fileName;
    let contentType;
    
    const timestamp = formatDateTime(new Date(), 'YYYYMMDD_HHmmss');
    
    if (format === 'excel') {
      buffer = await generateExcel(configs, lang, compareMode);
      fileName = `reports/LinkBudget_${timestamp}.xlsx`;
      contentType = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
    } else if (format === 'pdf') {
      buffer = await generatePDF(configs, lang);
      fileName = `reports/LinkBudgetReport_${timestamp}.pdf`;
      contentType = 'application/pdf';
    } else if (format === 'word-params') {
      buffer = await generateWordParams(configs, lang);
      fileName = `reports/LinkParams_${timestamp}.docx`;
      contentType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
    } else {
      buffer = await generateWord(configs, lang);
      fileName = `reports/LinkBudgetReport_${timestamp}.docx`;
      contentType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
    }
    
    // 上传到云存储
    const uploadResult = await cloud.uploadFile({
      cloudPath: fileName,
      fileContent: buffer
    });
    
    // 获取临时下载链接（有效期2小时）
    const tempUrlResult = await cloud.getTempFileURL({
      fileList: [uploadResult.fileID]
    });
    
    const tempFileURL = tempUrlResult.fileList[0].tempFileURL;
    
    return {
      success: true,
      fileID: uploadResult.fileID,
      tempFileURL: tempFileURL,
      fileName: fileName.split('/').pop(),
      format: format
    };
    
  } catch (error) {
    console.error('生成报告失败:', error);
    return {
      success: false,
      error: error.message || '生成报告失败'
    };
  }
};
